(() => {
  'use strict';
  const $=(s,r)=> (r||document).querySelector(s);
  const $$=(s,r)=> Array.from((r||document).querySelectorAll(s));
  const txt=v=>String(v==null?'':v).trim();
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const api=()=>window.AERIONFicha||window.AERION_FICHA;
  const assets=()=>window.AERIONPersonagemAssets||null;
  const SKIN=[['Muito claro','#f1d7c1','Tom bem claro.'],['Claro','#dfb995','Claro e suave.'],['Médio','#b9825e','Tom intermediário.'],['Bronzeado','#9b684b','Tom quente e bronzeado.'],['Escuro','#6e4836','Tom profundo.'],['Muito escuro','#432f29','Tom muito profundo.']];
  const HAIR=[['Preto','#181411'],['Castanho','#5b3b26'],['Loiro','#c6a45b'],['Ruivo','#9c4c2e'],['Branco','#ddddda'],['Cinza','#7e7c7a']];
  const EYES=[['Castanhos','#6e4a2f'],['Âmbar','#c79032'],['Azuis','#5a88bd'],['Verdes','#5d9464'],['Cinza','#8f989f'],['Violetas','#8c6da7']];
  const titles=['Identidade','Raça','Aparência','Classe','Atributos','Poder & Mana','Perícias','Técnicas','Inventário','Revisão'];
  const descriptions=[
    'Defina quem é o seu aventureiro.',
    'Escolha seu povo e, quando aplicável, sua linhagem.',
    'Ajuste altura e características visuais dentro dos limites do personagem.',
    'Escolha seu estilo de jogo e os recursos da classe.',
    'Distribua os dados entre os sete atributos.',
    'Defina sua afinidade de Poder e a reserva de Mana da classe.',
    'Escolha onde seu personagem possui treinamento.',
    'Registre técnicas que fazem parte do seu estilo.',
    'Monte sua carga e acompanhe slots e peso.',
    'Confira o personagem antes de torná-lo uma ficha pronta.'
  ];
  function imageFor(s){var a=assets();if(!a)return '';if(txt(s.race).toLowerCase()==='animalha'&&s.animalha){var an=a.getAnimalha&&a.getAnimalha(s.animalha);return an&&an.images&&(an.images.default||an.images.masculino||an.images.feminino)||'';}return a.getRaceImage&&a.getRaceImage(s.race,s.gender)||'';}
  function renderProgress(s){var i=Math.max(0,Math.min(9,Number(s.currentStep)||0)),p=Math.round((i+1)*10);$$('[data-current-step]').forEach(e=>e.textContent=i+1);$$('[data-total-steps]').forEach(e=>e.textContent='10');$('[data-current-step-title]').forEach(e=>e.textContent=titles[i]);
    $('[data-current-step-description]').forEach(e=>e.textContent=descriptions[i]);var b=$('#progressBar');if(b)b.style.width=p+'%';var tr=$('.progress-track');if(tr)tr.setAttribute('aria-valuenow',p);var pe=$('#progressPercent');if(pe)pe.textContent=p+'%';$('.creation-step').forEach(e=>{var n=Number(e.dataset.step),complete=!!s.completedSteps?.[n];e.classList.toggle('is-active',n===i);e.classList.toggle('is-complete',complete);e.setAttribute('aria-current',n===i?'step':'false');e.setAttribute('aria-label',(n+1)+'. '+titles[n]+(complete?' — concluída':''));e.setAttribute('aria-disabled',n>i+1&&!complete?'true':'false');});var panels=$$('[data-panel]');panels.forEach(e=>{var id=['identity','race','appearance','class','attributes','power','skills','techniques','inventory','review'][i];e.hidden=e.dataset.panel!==id;e.classList.toggle('is-active',e.dataset.panel===id);});var next=$('[data-action="next-step"]'),prev=$('[data-action="previous-step"]');if(next){next.hidden=i===9;next.disabled=i===9;}if(prev)prev.disabled=i===0;var fb=$('#aerion-finalize-bottom');if(fb)fb.hidden=i!==9;var hf=$('#aerion-header-finalize');if(hf)hf.hidden=i!==9;}
  function renderPreview(s){var name=txt(s.name)||'Sem nome',a=assets(),race=a?.getRace?.(s.race),animal=a?.getAnimalha?.(s.animalha),klass=api()?.getClasses?.()?.[s.class];$('#preview-name').textContent=name;$('#preview-initial').textContent=name.slice(0,1).toUpperCase();$('#preview-subtitle').textContent=[race?.name||s.race,animal?'Animalha '+(animal.name||s.animalha):'',klass?.name||''].filter(Boolean).join(' · ')||'Comece definindo identidade, raça e classe.';$('#preview-hp').textContent=String(Number(s.hp?.current||10));$('#preview-defense').textContent=String(Number(s.defense||10));$('#preview-mana').textContent=String(Number(s.mana?.current||0))+'/'+String(Number(s.mana?.max||0));var img=$('#preview-image'),u=imageFor(s);if(u){img.src=u;img.hidden=false;}else img.hidden=true;}
  function renderIdentity(s){var map=[['[data-field="name"]',s.name],['[data-field="age"]',s.age],['[data-field="origin"]',s.origin],['[data-field="description"]',s.description],['[data-concept-field="personality"]',s.personality],['[data-concept-field="objective"]',s.objective],['[data-concept-field="fear"]',s.fear],['[data-concept-field="importantBond"]',s.importantBond],['[data-concept-field="history"]',s.history],['[data-concept-field="region"]',s.region]];map.forEach(x=>{var e=$(x[0]);if(e&&document.activeElement!==e)e.value=x[1]??'';});$$('[data-field-choice="gender"]').forEach(e=>e.classList.toggle('is-selected',e.dataset.value===s.gender));}
  function renderRaces(s){var a=assets(),grid=$('#race-grid');if(!a||!grid)return;var q=txt($('#race-search')?.value).toLowerCase(),races=(a.races||[]).filter(r=>!q||txt(r.name).toLowerCase().includes(q)||txt(r.description).toLowerCase().includes(q));$('#race-count').textContent=races.length+' opções';grid.replaceChildren();races.forEach(r=>{var b=document.createElement('button');b.type='button';b.className='race-card'+(r.id===s.race?' is-selected':'');b.dataset.raceId=r.id;var u=a.getRaceImage?.(r.id,s.gender)||'';b.innerHTML='<div class="race-art">'+(u?'<img src="'+esc(u)+'" alt="">':'<span>'+esc(txt(r.name).slice(0,1))+'</span>')+'</div><div><strong>'+esc(r.name)+'</strong><small>'+esc(r.description||r.profile||'')+'</small></div><i class="check">✓</i>';grid.appendChild(b);});var block=$('#animalha-block'),isAnimal=txt(s.race).toLowerCase()==='animalha';if(block)block.hidden=!isAnimal;if(isAnimal)renderAnimalha(s);var info=$('#race-info'),race=a.getRace?.(s.race);if(info&&race&&!isAnimal){info.hidden=false;info.innerHTML='<div><span>ESCOLHIDA</span><h3>'+esc(race.name)+'</h3><p>'+esc(race.description||race.profile||'')+'</p></div>';}else if(info)info.hidden=true;}
  function renderAnimalha(s){var a=assets(),cg=$('#animalha-category-grid');if(!a||!cg)return;cg.replaceChildren();(a.animalhaCategories||[]).forEach(c=>{var b=document.createElement('button');b.type='button';b.className='lineage-card'+(s.animalhaCategory===c.id?' is-selected':'');b.dataset.animalhaCategory=c.id;b.innerHTML='<span>'+esc(c.icon||'✦')+'</span><div><strong>'+esc(c.name)+'</strong><small>'+esc(c.description||'')+'</small></div><i class="check">✓</i>';cg.appendChild(b);});var animals=s.animalhaCategory?a.getAnimalhaAnimals?.(s.animalhaCategory)||[]:[],wrap=$('#animalha-variation-wrap'),vg=$('#animalha-variation-grid');if(wrap)wrap.hidden=!animals.length;$('#animalha-category-label').textContent=(a.animalhaCategories||[]).find(x=>x.id===s.animalhaCategory)?.name||'';vg?.replaceChildren();animals.forEach(an=>{var b=document.createElement('button');b.type='button';b.className='animal-card'+(s.animalha===an.id?' is-selected':'');b.dataset.animalhaId=an.id;b.innerHTML='<span class="animal-icon">'+esc(an.icon||'✦')+'</span><div><strong>'+esc(an.name)+'</strong><small>'+esc(an.description||an.lineage||'')+'</small></div><i class="check">✓</i>';vg.appendChild(b);});}
  function renderAppearance(s){var u=imageFor(s),img=$('#appearance-image');if(u){img.src=u;img.hidden=false;$('#appearance-placeholder').hidden=true;}else{img.hidden=true;$('#appearance-placeholder').hidden=false;}var a=assets(),race=a?.getRace?.(s.race);$('#appearance-race-label').textContent=(race?.name||s.race||'Sem raça definida')+(s.animalha?' · '+(a?.getAnimalha?.(s.animalha)?.name||s.animalha):'');$('#appearance-size-label').textContent=s.derivedStats?.size||'—';var rr=a?.getRaceHeight?.(s.race)||{min:90,max:320},range=$('#height-range');range.min=rr.min;range.max=rr.max;range.value=Math.min(Math.max(Number(s.appearance?.height||rr.min),Number(rr.min)),Number(rr.max));$('#height-value').textContent=range.value;$('#height-min-label').textContent=rr.min;$('#height-max-label').textContent=rr.max;renderSkin(s);renderMini('#hair-grid',HAIR,'hairColor','hair',s);renderMini('#eyes-grid',EYES,'eyeColor','eyes',s);}
  function renderSkin(s){var p=$('#skin-picker'),sel=SKIN.find(x=>x[0]===s.appearance?.skinTone);$('#skin-value').textContent=sel?.[0]||'Escolher';$('#skin-swatch').style.background=sel?.[1]||'transparent';p.replaceChildren();SKIN.forEach(x=>{var b=document.createElement('button');b.type='button';b.className='swatch-option'+(sel?.[0]===x[0]?' is-selected':'');b.dataset.skin=x[0];b.innerHTML='<i style="background:'+x[1]+'"></i><span><strong>'+esc(x[0])+'</strong><small>'+esc(x[2])+'</small></span>'+(sel?.[0]===x[0]?'<b>✓</b>':'');p.appendChild(b);});}
  function renderMini(sel,data,stateKey,dataKey,s){var r=$(sel);if(!r)return;r.replaceChildren();data.forEach(x=>{var b=document.createElement('button');b.type='button';b.className='mini-choice'+(s.appearance?.[stateKey]===x[0]?' is-selected':'');b.dataset[dataKey]=x[0];b.innerHTML='<i style="background:'+x[1]+'"></i><span>'+esc(x[0])+'</span>';r.appendChild(b);});}
  function renderClasses(s){var r=$('#class-grid');if(!r)return;r.replaceChildren();Object.values(api()?.getClasses?.()||{}).forEach(k=>{var b=document.createElement('button');b.type='button';b.className='class-card'+(s.class===k.id?' is-selected':'');b.dataset.classId=k.id;b.innerHTML='<div class="class-icon">'+esc(k.icon)+'</div><div class="class-body"><span>'+esc(k.role)+'</span><strong>'+esc(k.name)+'</strong><p>'+esc(k.description)+'</p></div><aside><small>Mana</small><b>'+esc(k.mana)+'</b><em>'+esc(k.skillCount)+' perícias</em></aside><i class="check">✓</i>';r.appendChild(b);});}
  function renderAttributes(s){var ds=api()?.getDice?.()||[],pool=$('#dice-pool');pool?.replaceChildren();ds.forEach(d=>{var taken=Object.values(s.assignedDice||{}).includes(d.id),b=document.createElement('span');b.className='pool-die'+(taken?' is-used':'');b.textContent=d.label;pool?.appendChild(b);});var grid=$('#attribute-grid');if(!grid)return;grid.replaceChildren();var attrs=api()?.getAttributes?.()||[];attrs.forEach(a=>{var assigned=s.assignedDice?.[a.id]||'',d=ds.find(x=>x.id===assigned),bonus=Number(s.derivedStats?.racialModifiers?.[a.id]||0),card=document.createElement('article');card.className='attribute-card'+(assigned?' is-assigned':'');card.innerHTML='<header><div><span>'+esc(a.short)+'</span><strong>'+esc(a.name)+'</strong></div>'+(bonus?'<b class="racial-bonus">'+(bonus>0?'+':'')+bonus+'</b>':'')+'</header><div class="attribute-value"><strong>'+esc(d?.label||'—')+'</strong>'+(assigned?'<button type="button" data-remove-die="'+esc(a.id)+'">×</button>':'')+'</div><div class="attribute-dice">'+ds.map(x=>{var taken=Object.entries(s.assignedDice||{}).some(y=>y[0]!==a.id&&y[1]===x.id);return '<button type="button" class="mini-die '+(assigned===x.id?'is-selected':'')+'" data-assign-die="'+x.id+'" data-attribute="'+a.id+'" '+(taken?'disabled':'')+'>'+x.label+'</button>';}).join('')+'</div>';grid.appendChild(card);});$('#attributes-status').textContent=Object.keys(s.assignedDice||{}).length===7?'✓ Atributos completos.':' '+Object.keys(s.assignedDice||{}).length+'/7 atributos preenchidos.';}
  function renderPower(s){$('#power-roll-result').textContent=s.powerRoll==null?'—':String(s.powerRoll);$('#mana-value').textContent=String(s.mana?.max||0);$('#mana-class-label').textContent=s.class?((api()?.getClasses?.()?.[s.class]?.name||s.class)+' · '+(s.mana?.max||0)+' Mana'):'Escolha uma classe.';var mc=$('#mana-current');if(mc&&document.activeElement!==mc){mc.value=String(s.mana?.current||0);mc.max=String(s.mana?.max||0);}var root=$('#uncommon-powers');root?.replaceChildren();(api()?.getUncommonPowers?.()||[]).forEach(p=>{var b=document.createElement('button');b.type='button';b.className=(s.primaryPower===p.name?'is-selected':'');b.dataset.uncommonPower=p.name;b.textContent=p.name;root?.appendChild(b);});var cp=$('[data-power="customPower"]'),cd=$('[data-power="customDescription"]');if(cp&&document.activeElement!==cp)cp.value=s.powerMode==='custom'?s.primaryPower:'';if(cd&&document.activeElement!==cd)cd.value=s.customPowerDescription||'';var sum=$('#power-summary');if(sum){sum.hidden=!s.primaryPower;if(s.primaryPower)sum.innerHTML='<div><span>PODER ESCOLHIDO</span><h3>'+esc(s.primaryPower)+'</h3><p>'+esc(s.customPowerDescription||'Afinidade definida pelo personagem.')+'</p></div><strong>'+(s.powerRoll!=null?'D100 · '+s.powerRoll:(s.powerMode||'Escolhido'))+'</strong>';}}
  function renderSkills(s){var root=$('#skills-grid');if(!root)return;root.replaceChildren();var attrs=Object.fromEntries((api()?.getAttributes?.()||[]).map(x=>[x.id,x])),ds=api()?.getDice?.()||[],count=0;(api()?.getSkills?.()||[]).forEach(sk=>{var v=s.skills?.[sk.id]||{trained:false,bonus:0};if(v.trained)count++;var d=ds.find(x=>x.id===s.assignedDice?.[sk.attribute]),card=document.createElement('article');card.className='skill-card'+(v.trained?' is-trained':'');card.innerHTML='<div class="skill-main"><span>'+esc(attrs[sk.attribute]?.name||sk.attribute)+'</span><h3>'+esc(sk.name)+'</h3><p>'+esc(sk.description)+'</p></div><div class="skill-die">'+esc(d?.label||'—')+'</div><div class="skill-foot"><button type="button" class="training-toggle '+(v.trained?'is-trained':'')+'" data-skill-id="'+sk.id+'">'+(v.trained?'✓ Treinada':'Treinar')+'</button><label class="skill-bonus"><span>Bônus</span><input type="number" min="0" max="20" value="'+esc(v.bonus||0)+'" data-skill-bonus="'+sk.id+'"></label></div>';root.appendChild(card);});$('#skills-trained-count').textContent=String(count);}
  function renderTechniques(s){var root=$('#techniques-list');if(!root)return;root.replaceChildren();if(!s.techniques?.length){root.innerHTML='<div class="empty-state">Nenhuma técnica adicionada.</div>';return;}s.techniques.forEach(t=>{var c=document.createElement('article');c.className='technique-card';c.innerHTML='<div class="technique-head"><div><span>TÉCNICA</span><h3>'+esc(t.name||'Nova técnica')+'</h3></div><button type="button" data-remove-technique="'+t.id+'">×</button></div><div class="technique-grid"><label class="wide">Nome<input data-technique-id="'+t.id+'" data-technique-field="name" value="'+esc(t.name||'')+'" placeholder="Nome da técnica"></label><label>Nível<select data-technique-id="'+t.id+'" data-technique-field="level">'+[1,2,3,4,5].map(l=>'<option value="'+l+'" '+(Number(t.level)===l?'selected':'')+'>'+l+'</option>').join('')+'</select></label><label>XP<input type="number" min="0" data-technique-id="'+t.id+'" data-technique-field="xp" value="'+esc(t.xp||0)+'"></label><label>Mana<input type="number" min="0" data-technique-id="'+t.id+'" data-technique-field="cost" value="'+esc(t.cost||0)+'"></label><label>Ação<select data-technique-id="'+t.id+'" data-technique-field="action">'+['Ação Principal','Ação de Movimento','Ação Rápida','Reação'].map(a=>'<option '+(t.action===a?'selected':'')+'>'+esc(a)+'</option>').join('')+'</select></label><label>Alcance<input data-technique-id="'+t.id+'" data-technique-field="range" value="'+esc(t.range||'')+'" placeholder="Ex.: 15 m"></label><label class="wide">Efeito<textarea rows="3" data-technique-id="'+t.id+'" data-technique-field="effect">'+esc(t.effect||'')+'</textarea></label></div>';root.appendChild(c);});}
  function renderInventory(s){var root=$('#inventory-list');if(!root)return;root.replaceChildren();if(!s.inventory?.length)root.innerHTML='<div class="empty-state">Inventário vazio.</div>';else s.inventory.forEach(i=>{var c=document.createElement('article');c.className='item-card';c.innerHTML='<label class="wide">Item<input data-item-id="'+i.id+'" data-item-field="name" value="'+esc(i.name||'')+'" placeholder="Ex.: Poção"></label><label>Qtd.<input type="number" min="1" data-item-id="'+i.id+'" data-item-field="quantity" value="'+esc(i.quantity||1)+'"></label><label>Slots<input type="number" min="0" step="0.5" data-item-id="'+i.id+'" data-item-field="slots" value="'+esc(i.slots||0)+'"></label><label>Peso kg<input type="number" min="0" step="0.1" data-item-id="'+i.id+'" data-item-field="weight" value="'+esc(i.weight||0)+'"></label><button type="button" data-remove-item="'+i.id+'">×</button>';root.appendChild(c);});var usedSlots=(s.inventory||[]).reduce((a,i)=>a+Number(i.slots||0)*Number(i.quantity||1),0),usedWeight=(s.inventory||[]).reduce((a,i)=>a+Number(i.weight||0)*Number(i.quantity||1),0),k=api()?.getClasses?.()?.[s.class],maxSlots=k?.slots||0,maxWeight=k?.weight||0;$('#slots-used').textContent=usedSlots;$('#slots-max').textContent=maxSlots||'—';$('#weight-used').textContent=usedWeight.toFixed(1);$('#weight-max').textContent=maxWeight||'—';var e=$('#encumbrance-state');if(e){e.textContent=usedWeight>maxWeight*1.5&&maxWeight?'Excesso extremo':usedWeight>maxWeight&&maxWeight?'Sobrecarregado':'Normal';e.className=usedWeight>maxWeight*1.5?'status-danger':usedWeight>maxWeight?'status-warn':'status-normal';}}
  function renderReview(s){var r=$('#review-grid');if(!r)return;var trained=Object.values(s.skills||{}).filter(v=>v?.trained).length,tech=s.techniques?.length||0,items=s.inventory?.length||0,vals=[['IDENTIDADE',s.name||'Sem nome',s.gender?'✓ Completa':'⚠ Falta gênero'],['RAÇA',(assets()?.getRace?.(s.race)?.name||s.race||'—'),s.animalha?'Animalha · '+(assets()?.getAnimalha?.(s.animalha)?.name||s.animalha):'Base racial'],['CLASSE',api()?.getClasses?.()?.[s.class]?.name||'Não escolhida',s.class?'✓ Definida':'⚠ Falta classe'],['ATRIBUTOS',Object.keys(s.assignedDice||{}).length+'/7 preenchidos',Object.keys(s.assignedDice||{}).length===7?'✓ Completo':'⚠ Incompleto'],['PODER',s.primaryPower||'Não escolhido',s.primaryPower?'✓ Definido':'⚠ Falta poder'],['MANA',(s.mana?.current||0)+' / '+(s.mana?.max||0),'Reserva da classe'],['PERÍCIAS',trained+' treinadas','14 disponíveis'],['TÉCNICAS',tech+'','Personalize durante o jogo'],['INVENTÁRIO',items+' itens','Carga atual'],['COMBATE','HP '+(s.hp?.current||10)+' · DEF '+(s.defense||10),'Movimento '+(s.movement||9)+' m']];r.replaceChildren();vals.forEach(v=>{var c=document.createElement('article');c.className='review-card';c.innerHTML='<span>'+esc(v[0])+'</span><h3>'+esc(v[1])+'</h3><small>'+esc(v[2])+'</small>';r.appendChild(c);});var f=$('#aerion-finalize-bottom');if(f)f.disabled=![0,1,2,3,4,5].every(i=>s.completedSteps?.[i]);}
  function render(s){renderProgress(s);renderPreview(s);renderIdentity(s);renderRaces(s);renderAppearance(s);renderClasses(s);renderAttributes(s);renderPower(s);renderSkills(s);renderTechniques(s);renderInventory(s);renderReview(s);}
  window.addEventListener('aerion:ficha:render',e=>e.detail?.state&&render(e.detail.state));
  window.addEventListener('aerion:ficha:update',e=>e.detail?.state&&render(e.detail.state));
  window.addEventListener('aerion:ficha:filter-race',()=>{var s=api()?.getState?.();if(s)renderRaces(s);});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{var s=api()?.getState?.();if(s)render(s);},{once:true});else{var s=api()?.getState?.();if(s)render(s);}
})();