import { getSupabase } from "./supabase.js";

(() => {
  "use strict";
  const TABS=[["summary","Resumo","◈"],["description","Descrição","✎"],["appearance","Aparência","◌"],["attributes","Atributos","◆"],["skills","Perícias","◇"],["powers","Poderes","✦"],["techniques","Técnicas","⚔"],["inventory","Inventário","▣"],["conditions","Condições","●"],["story","História","📖"]];
  const ATTRIBUTES=[["forca","Força","FOR"],["agilidade","Agilidade","AGI"],["percepcao","Percepção","PER"],["vigor","Vigor","VIG"],["intelecto","Intelecto","INT"],["presenca","Presença","PRE"],["controle","Controle","CON"],["precisao","Precisão","PRI"]];
  const SKILLS=[["acrobacia","Acrobacia","agilidade"],["atletismo","Atletismo","forca"],["furtividade","Furtividade","agilidade"],["pontaria","Pontaria","agilidade"],["percepcao","Percepção","percepcao"],["investigacao","Investigação","intelecto"],["conhecimento","Conhecimento","intelecto"],["medicina","Medicina","intelecto"],["sobrevivencia","Sobrevivência","percepcao"],["persuasao","Persuasão","presenca"],["enganacao","Enganação","presenca"],["intuicao","Intuição","percepcao"],["tatica","Tática","intelecto"],["oficio","Ofício / Crafting","controle"]];
  const ATTRIBUTES=[["forca","Força","FOR"],["agilidade","Agilidade","AGI"],["percepcao","Percepção","PER"],["vigor","Vigor","VIG"],["intelecto","Intelecto","INT"],["presenca","Presença","PRE"],["controle","Controle","CON"],["precisao","Precisão","PRI"]];
  const SKILLS=[["acrobacia","Acrobacia","agilidade"],["atletismo","Atletismo","forca"],["furtividade","Furtividade","agilidade"],["pontaria","Pontaria","agilidade"],["percepcao","Percepção","percepcao"],["investigacao","Investigação","intelecto"],["conhecimento","Conhecimento","intelecto"],["medicina","Medicina","intelecto"],["sobrevivencia","Sobrevivência","percepcao"],["persuasao","Persuasão","presenca"],["enganacao","Enganação","presenca"],["intuicao","Intuição","percepcao"],["tatica","Tática","intelecto"],["oficio","Ofício / Crafting","controle"]];
  let menuOpen=false,character=null,state={},currentTab="summary",supabase=null;
  const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
  const ctx=()=>window.AERIOM_CAMPAIGN?.getContext?.()||null;
  const own=()=>{const c=ctx(),list=Array.isArray(c?.presentCharacters)?c.presentCharacters:[];const mine=list.find(x=>String(x?.character?.userId||"")===String(c?.user?.id||""));return mine?.character||null;};
  function ensure(){if(document.getElementById("aerion-sheet-fab"))return;const fab=document.createElement("button");fab.id="aerion-sheet-fab";fab.className="aerion-sheet-fab";fab.type="button";fab.textContent="A";fab.setAttribute("aria-label","Abrir ficha do AERION");fab.setAttribute("aria-expanded","false");const menu=document.createElement("div");menu.id="aerion-sheet-menu";menu.className="aerion-sheet-menu";TABS.slice(0,7).forEach((t,i)=>{const w=document.createElement("div");w.className="aerion-sheet-menu__item item-"+(i+1);const l=document.createElement("span");l.className="aerion-sheet-menu__label";l.textContent=t[1];const b=document.createElement("button");b.type="button";b.className="aerion-sheet-menu__button";b.textContent=t[2];b.setAttribute("aria-label","Abrir "+t[1]);b.addEventListener("click",()=>openSheet(t[0]));w.append(l,b);menu.append(w);});const more=document.createElement("div");more.className="aerion-sheet-menu__item item-7";more.innerHTML='<span class="aerion-sheet-menu__label">Mais</span><button type="button" class="aerion-sheet-menu__button" aria-label="Abrir ficha completa">＋</button>';more.querySelector("button").addEventListener("click",()=>openSheet(currentTab));menu.append(more);fab.addEventListener("click",()=>{menuOpen=!menuOpen;fab.classList.toggle("is-open",menuOpen);menu.classList.toggle("is-open",menuOpen);fab.setAttribute("aria-expanded",String(menuOpen));});document.body.append(fab,menu);const modal=document.createElement("div");modal.id="aerion-sheet-modal";modal.className="aerion-sheet-modal";modal.innerHTML='<section class="aerion-sheet-card" role="dialog" aria-modal="true" aria-label="Ficha do personagem"><div id="aerion-sheet-inner"></div></section>';modal.addEventListener("click",e=>{if(e.target===modal)closeSheet();});document.body.appendChild(modal);const flash=document.createElement("div");flash.id="aerion-sheet-flash";flash.className="aerion-sheet-flash";document.body.appendChild(flash);}
  async function loadCharacter(){const c=own();if(!c){character=null;state={};return;}character=c;try{if(!supabase)supabase=await getSupabase();const r=await supabase.from("characters").select("*").eq("id",c.id).maybeSingle();if(!r.error&&r.data){character={...c,id:String(r.data.id),avatarPath:r.data.avatar_path||c.avatarPath||"",name:r.data.name||c.name};state=r.data.creation_state||{};}else state={};}catch{state={};}}
  const stat=(label,value,sub)=>'<article class="aerion-sheet-stat"><span>'+esc(sub)+'</span><strong>'+esc(value)+'</strong><small style="color:rgba(255,255,255,.42);font-size:6px">'+esc(label)+'</small></article>';
  const textPanel=(title,value)=>'<article class="aerion-sheet-text-card"><span>'+esc(title)+'</span><p>'+esc(value)+'</p></article>';
  function rollList(items,empty){if(!items.length)return '<div class="aerion-sheet-empty">'+esc(empty)+'</div>';return '<div class="aerion-sheet-card-grid">'+items.map(x=>{const d=x.dietype?String(x.dietype).replace(/^d/i,""):"";const label=x.bonus?((x.dietype?"D"+d:"")+" +"+x.bonus):(x.dietype?"D"+d:"—");return '<article class="aerion-sheet-list-card"><div class="aerion-sheet-list-card__copy"><span>'+esc(x.sub||"Teste")+'</span><strong>'+esc(x.label)+'</strong><small>'+esc(label)+(x.trained?" · Treinada":"")+'</small></div><button class="aerion-roll-button" type="button" data-roll="'+esc(x.dietype||"")+'" data-bonus="'+esc(x.bonus||0)+'" data-label="'+esc(x.label)+'" '+(!x.dietype?"disabled":"")+' >🎲</button></article>';}).join("")+'</div>';}
  function panel(){const s=state||{};if(currentTab==="summary"){return '<div class="aerion-sheet-overview">'+stat("HP",(s.hp?.current??character?.hpCurrent??0)+"/"+(s.hp?.max??character?.hpMax??0),"Vida")+stat("Defesa",s.defense??character?.defense??10,"Combate")+stat("Mana",(s.mana?.current??character?.manaCurrent??0)+"/"+(s.mana?.max??character?.manaMax??0),"Recurso")+stat("Movimento",s.movement??9,"Deslocamento")+'</div>'+textPanel("Poder",s.primaryPower||"Nenhum poder definido.")+textPanel("Raça / Classe",[character?.race,character?.class].filter(Boolean).join(" • ")||"Aventureiro");}
    if(currentTab==="description")return textPanel("Descrição",s.description||"Sem descrição adicionada.");
    if(currentTab==="appearance"){const a=s.appearance||{};return '<div class="aerion-sheet-card-grid">'+stat("Altura",a.height?String(a.height)+" cm":"—","Aparência")+stat("Tom de pele",a.skinTone||"—","Aparência")+stat("Cabelo",a.hairColor||"—","Aparência")+stat("Olhos",a.eyeColor||"—","Aparência")+'</div>'+textPanel("Detalhes",a.description||"Sem detalhes de aparência.");}
    if(currentTab==="attributes")return rollList(ATTRIBUTES.map(a=>({label:a[1],sub:a[2],dietype:(s.assignedDice||{})[a[0]]})),"Nenhum atributo configurado.");
    if(currentTab==="skills"){const attrs=Object.fromEntries(ATTRIBUTES.map(a=>[a[0],a]));return rollList(SKILLS.map(k=>{const v=s.skills?.[k[0]]||{};return {label:k[1],sub:attrs[k[2]]?.[1]||k[2],dietype:(s.assignedDice||{})[k[2]],bonus:Number(v.bonus||0),trained:Boolean(v.trained)};}),"Nenhuma perícia configurada.");}
    if(currentTab==="powers")return textPanel("Poder principal",s.primaryPower||"Nenhum poder definido.")+'<div class="aerion-sheet-overview">'+stat("Mana",(s.mana?.current??0)+"/"+(s.mana?.max??0),"Recurso")+stat("Cor",s.mana?.color||"azul","Afinidade")+'</div>';
    if(currentTab==="techniques"){const list=Array.isArray(s.techniques)?s.techniques:[];return list.length?list.map(t=>textPanel("Técnica",(t.name||"Nova técnica")+" · Nível "+(t.level||1)+" · Custo "+(t.cost||0)+" Mana")).join(""):'<div class="aerion-sheet-empty">Nenhuma técnica registrada.</div>';}
    if(currentTab==="inventory"){const list=Array.isArray(s.inventory)?s.inventory:[];return list.length?'<div class="aerion-sheet-card-grid">'+list.map(i=>textPanel("Item",(i.name||"Item")+" · Qtd. "+(i.quantity||1)+" · "+(i.weight||0)+" kg")).join("")+'</div>':'<div class="aerion-sheet-empty">Inventário vazio.</div>';}
    if(currentTab==="conditions"){const list=Array.isArray(s.conditions)?s.conditions:[];return list.length?list.map(c=>textPanel("Condição",typeof c==="string"?c:(c.name||"Condição"))).join(""):'<div class="aerion-sheet-empty">Nenhuma condição.</div>';}
    if(currentTab==="story")return textPanel("Personalidade",s.personality||"—")+textPanel("Objetivo",s.objective||"—")+textPanel("Medo",s.fear||"—")+textPanel("Vínculo importante",s.importantBond||"—")+textPanel("Região",s.region||"—")+textPanel("História",s.history||"—");
    return "";
  }
  function render(){const inner=document.getElementById("aerion-sheet-inner");if(!inner)return;const tabs=TABS.map(t=>'<button type="button" class="'+(t[0]===currentTab?"is-active":"")+'" data-tab="'+t[0]+'">'+esc(t[2])+" "+esc(t[1])+"</button>").join("");if(!character){inner.innerHTML='<div class="aerion-sheet-head"><div class="aerion-sheet-avatar">A</div><div><h2>Minha ficha</h2><p>Nenhuma ficha foi vinculada a esta campanha.</p></div><button class="aerion-sheet-close" type="button" data-close>×</button></div><div class="aerion-sheet-body"><div class="aerion-sheet-empty">Adicione uma ficha finalizada à campanha para usar a ficha de jogo.</div></div>';}else{const meta=[character.race,character.class].filter(Boolean).join(" • ");const avatar=character.avatarPath?'<img src="'+esc(character.avatarPath)+'" alt="">':esc((character.name||"A").charAt(0).toUpperCase());inner.innerHTML='<div class="aerion-sheet-head"><div class="aerion-sheet-avatar">'+avatar+'</div><div><div style="color:#e3c36d;font-size:5px;font-weight:900;letter-spacing:.12em">MINHA FICHA</div><h2>'+esc(character.name||"Personagem")+'</h2><p>'+esc(meta||"Aventureiro")+'</p></div><button class="aerion-sheet-close" type="button" data-close>×</button></div><div class="aerion-sheet-tabs">'+tabs+'</div><div class="aerion-sheet-body">'+panel()+'</div>';}inner.querySelector("[data-close]")?.addEventListener("click",closeSheet);inner.querySelectorAll("[data-tab]").forEach(b=>b.addEventListener("click",()=>{currentTab=b.dataset.tab;render();}));inner.querySelectorAll("[data-roll]").forEach(b=>b.addEventListener("click",()=>roll(b)));}
  async function roll(button){const dice=window.AERIOM_DICE;if(!dice?.roll){flash("Rolador da mesa ainda está carregando.");return;}const sides=Number(button.dataset.roll||0);if(!sides)return;button.disabled=true;try{const id=character.id;dice.setCharacter?.(id);dice.setContext?.(button.dataset.label||"Teste de ficha");const r=await dice.roll({die:sides,modifier:Number(button.dataset.bonus||0),characterId:id,context:button.dataset.label||"Teste de ficha"});flash((button.dataset.label||"Teste")+": "+(r?.notation||("D"+sides))+" → "+(r?.totalResult??"—"));}catch(e){flash(e?.message||"Não foi possível realizar a rolagem.");}finally{button.disabled=false;}}
  function flash(msg){const el=document.getElementById("aerion-sheet-flash");if(!el)return;el.textContent=msg;el.classList.add("is-show");clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove("is-show"),2400);}
  async function openSheet(tab){menuOpen=false;document.getElementById("aerion-sheet-fab")?.classList.remove("is-open");document.getElementById("aerion-sheet-menu")?.classList.remove("is-open");currentTab=TABS.some(x=>x[0]===tab)?tab:"summary";await loadCharacter();render();document.getElementById("aerion-sheet-modal")?.classList.add("is-open");}
  function closeSheet(){document.getElementById("aerion-sheet-modal")?.classList.remove("is-open");}
  async function boot(){ensure();document.addEventListener("click",e=>{const a=e.target.closest(".campaign-character-card a[href*=\"./ficha.html\"]");if(!a)return;const c=own();const id=new URL(a.href,location.href).searchParams.get("id");if(c&&id&&String(c.id)===String(id)){e.preventDefault();openSheet("summary");}});window.addEventListener("aeriom:campaign:ready",()=>loadCharacter().catch(()=>{}));window.addEventListener("aeriom:campaign:characterschange",()=>loadCharacter().catch(()=>{}));}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();