(() => {
  "use strict";
  const STEPS=[
    ["identity","Identidade"],["race","Raça"],["appearance","Aparência"],["class","Classe"],
    ["attributes","Atributos"],["power","Poder & Mana"],["skills","Perícias"],["techniques","Técnicas"],
    ["inventory","Inventário"],["review","Revisão"]
  ];
  const ATTRIBUTES=[["forca","Força","FOR"],["agilidade","Agilidade","AGI"],["percepcao","Percepção","PER"],["vigor","Vigor","VIG"],["intelecto","Intelecto","INT"],["presenca","Presença","PRS"],["controle","Controle","CON"]].map(([id,name,short])=>({id,name,short}));
  const DICE=[["d4","D4",4],["d6a","D6",6],["d6b","D6",6],["d8","D8",8],["d10","D10",10],["d12","D12",12],["d20a","D20",20],["d20b","D20",20]].map(([id,label,sides])=>({id,label,sides}));
  const CLASSES={
    guerreiro:{id:"guerreiro",name:"Guerreiro",role:"Combatente",icon:"⚔",mana:50,slots:16,weight:40,description:"Especialista em combate físico, armas e presença no campo de batalha."},
    feiticeiro:{id:"feiticeiro",name:"Feiticeiro",role:"Mágico",icon:"✦",mana:100,slots:12,weight:25,description:"Especialista em controle, canalização e manipulação de Mana."},
    curandeiro:{id:"curandeiro",name:"Curandeiro",role:"Suporte",icon:"✚",mana:80,slots:14,weight:30,description:"Especialista em suporte, recuperação e uso de Mana sobre aliados."},
    monge:{id:"monge",name:"Monge",role:"Marcial",icon:"◈",mana:30,slots:10,weight:20,description:"Transforma Mana em capacidade corporal, mobilidade e força física."}
  };
  const SKILLS=[["acrobacia","Acrobacia","agilidade","Equilíbrio, saltos e movimentos difíceis."],["atletismo","Atletismo","forca","Corrida, escalada, natação e feitos físicos."],["furtividade","Furtividade","agilidade","Mover-se sem chamar atenção."],["pontaria","Pontaria","agilidade","Mira, ataques à distância e arremessos."],["percepcao","Percepção","percepcao","Notar ameaças, sons e detalhes."],["investigacao","Investigação","intelecto","Buscar pistas e analisar evidências."],["conhecimento","Conhecimento","intelecto","Criaturas, história, magia e geografia."],["medicina","Medicina","intelecto","Primeiros socorros e tratamento."],["sobrevivencia","Sobrevivência","percepcao","Rastrear, navegar e encontrar recursos."],["persuasao","Persuasão","presenca","Convencer e negociar."],["enganacao","Enganação","presenca","Blefar e disfarçar intenções."],["intuicao","Intuição","percepcao","Perceber intenções e comportamentos estranhos."],["tatica","Tática","intelecto","Planejamento e leitura de combate."],["oficio","Ofício / Crafting","controle","Criar, reparar e aprimorar equipamentos."]].map(([id,name,attribute,desc])=>({id,name,attribute,desc}));
  const UNCOMMON=["Gelo","Magnetismo","Vegetação","Tecnologia","Gravidade"];
  const STORAGE="aerion:ficha:draft:v30";
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const text=v=>String(v??"").trim(),num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
  const clone=v=>{try{return structuredClone(v);}catch{return JSON.parse(JSON.stringify(v));}};
  const emit=(name,detail={})=>window.dispatchEvent(new CustomEvent(name,{detail}));
  const notify=(message,type="info")=>emit("aerion:toast",{message,type});
  const DEFAULT=()=>({currentStep:0,completedSteps:Array(10).fill(false),finalized:false,saved:false,name:"",age:"",gender:"",origin:"",description:"",history:"",region:"",objective:"",fear:"",importantBond:"",race:"",animalha:"",animalhaCategory:"",class:"",appearance:{height:170,skinTone:"",hairColor:"",eyeColor:""},assignedDice:{},primaryPower:"",parallelPower:"",powerRoll:null,powerMode:"",customPowerDescription:"",mana:{current:0,max:0},skills:{},techniques:[],inventory:[],equipment:[],conditions:[],hp:{current:10,max:10},defense:10,movement:9,derivedStats:{hpMax:10,defense:10,movement:9,size:"Médio",racialModifiers:{},abilities:[],resistances:[],senses:[]}});
  let state=DEFAULT(),timer=null,started=false;
  function calculateRules(){const racial=window.AERION_RACIAL_RULES?.calculate?.(state)||{};state.derivedStats={...state.derivedStats,...racial,hpMax:num(racial.hp,10),racialModifiers:racial.mods||{},abilities:racial.abilities||[],resistances:racial.resistances||[],senses:racial.senses||[]};state.hp.max=num(racial.hp,10);state.hp.current=Math.min(num(state.hp.current,10),state.hp.max);state.defense=num(racial.defense,10);state.movement=num(racial.movement,9);return state.derivedStats;}
  function computeCompletion(){state.completedSteps[0]=!!(text(state.name)&&text(state.gender));state.completedSteps[1]=!!text(state.race)&&(text(state.race).toLowerCase()!=="animalha"||!!(text(state.animalhaCategory)&&text(state.animalha)));state.completedSteps[2]=num(state.appearance?.height)>0;state.completedSteps[3]=!!text(state.class);state.completedSteps[4]=ATTRIBUTES.every(a=>!!state.assignedDice[a.id]);state.completedSteps[5]=!!text(state.primaryPower);}
  function setSaveLabel(v){const e=$("#saveStatusText");if(e)e.textContent=v;}
  function saveLocal(immediate=false){clearTimeout(timer);const run=()=>{try{state.saved=true;localStorage.setItem(STORAGE,JSON.stringify(state));emit("aerion:save",{state:clone(state)});setSaveLabel("Salvo agora");}catch(e){console.error(e);setSaveLabel("Erro ao salvar");}};setSaveLabel("Salvando…");if(immediate)run();else timer=setTimeout(run,350);}
  function commit(eventName="aerion:ficha:update"){calculateRules();computeCompletion();state.saved=false;saveLocal();emit(eventName,{state:clone(state)});render();}
  function loadLocal(){try{const raw=localStorage.getItem(STORAGE);if(raw){const p=JSON.parse(raw),d=DEFAULT();state={...d,...p,appearance:{...d.appearance,...p.appearance},mana:{...d.mana,...p.mana},hp:{...d.hp,...p.hp},derivedStats:{...d.derivedStats,...p.derivedStats}};}}catch(e){console.warn("[AERION][FICHA] rascunho local",e);}calculateRules();computeCompletion();}
  function chooseGender(v){state.gender=text(v);commit("aerion:gender:selected");}
  function chooseRace(v){state.race=text(v);state.animalha="";state.animalhaCategory="";const r=window.AERIONPersonagemAssets?.getRace?.(v);if(r?.height)state.appearance.height=Math.round((num(r.height.min,150)+num(r.height.max,200))/2);commit("aerion:race:selected");}
  function chooseAnimalCategory(v){state.animalhaCategory=text(v);state.animalha="";commit("aerion:animalha:category");}
  function chooseAnimal(v){state.animalha=text(v);commit("aerion:animalha:selected");}
  function chooseClass(v){const c=CLASSES[text(v)];if(!c)return false;state.class=c.id;state.mana.max=c.mana;state.mana.current=c.mana;commit("aerion:class:selected");return true;}
  function assignDie(attr,dieId){if(!ATTRIBUTES.some(a=>a.id===attr)||!DICE.some(d=>d.id===dieId))return false;const old=Object.entries(state.assignedDice).find(([a,d])=>d===dieId);if(old&&old[0]!==attr)delete state.assignedDice[old[0]];state.assignedDice[attr]=dieId;commit("aerion:attributes:update");return true;}
  function removeDie(attr){delete state.assignedDice[attr];commit("aerion:attributes:update");}
  function rollPowerD100(){const roll=Math.floor(Math.random()*100)+1,power=roll<=25?"Fogo":roll<=50?"Terra":roll<=75?"Água":"Ar";state.powerRoll=roll;state.primaryPower=power;state.powerMode="d100";state.customPowerDescription="";commit("aerion:power:selected");notify(`D100: ${roll} — ${power}.`,"success");return{roll,power};}
  function selectUncommonPower(p){if(!UNCOMMON.includes(text(p)))return false;state.primaryPower=text(p);state.powerMode="uncommon";state.powerRoll=null;state.customPowerDescription="";commit("aerion:power:selected");return true;}
  function setPowerValue(key,v){if(key==="customPower"){state.primaryPower=text(v);state.powerMode="custom";state.powerRoll=null;}else state.customPowerDescription=text(v);commit("aerion:power:update");}
  function setAppearance(k,v){state.appearance[k]=k==="height"?num(v):text(v);commit("aerion:appearance:update");}
  function toggleSkill(id){const v=state.skills[id]||{trained:false,bonus:0};state.skills[id]={...v,trained:!v.trained};commit("aerion:skills:update");}
  function setSkillBonus(id,v){state.skills[id]={...(state.skills[id]||{}),trained:true,bonus:Math.max(0,num(v))};commit("aerion:skills:update");}
  function addTechnique(){state.techniques.push({id:crypto.randomUUID(),name:"Nova técnica",level:1,xp:0,cost:0,action:"Ação Principal",range:"",effect:""});commit("aerion:technique:add");}
  function updateTechnique(id,key,v){const t=state.techniques.find(x=>x.id===id);if(!t)return;t[key]=["level","xp","cost"].includes(key)?num(v):text(v);commit("aerion:technique:update");}
  function removeTechnique(id){state.techniques=state.techniques.filter(x=>x.id!==id);commit("aerion:technique:remove");}
  function addItem(){state.inventory.push({id:crypto.randomUUID(),name:"Novo item",slots:1,weight:1,quantity:1});commit("aerion:inventory:add");}
  function updateItem(id,key,v){const i=state.inventory.find(x=>x.id===id);if(!i)return;i[key]=["slots","weight","quantity"].includes(key)?Math.max(key==="quantity"?1:0,num(v)):text(v);commit("aerion:inventory:update");}
  function removeItem(id){state.inventory=state.inventory.filter(x=>x.id!==id);commit("aerion:inventory:remove");}
  function validateStep(i=state.currentStep){computeCompletion();const messages=["Preencha nome e gênero.","Escolha a raça e, para Animalha, categoria e animal.","Defina a altura.","Escolha uma classe.","Distribua os 8 dados nos atributos.","Escolha ou sorteie um poder."];if(i<6&&!state.completedSteps[i]){notify(messages[i],"warning");return false;}return true;}
  function goToStep(i,strict=true){i=num(i,-1);if(i<0||i>9)return false;if(strict&&i>state.currentStep&&!validateStep())return false;state.currentStep=i;saveLocal();render();window.scrollTo({top:0,behavior:"smooth"});return true;}
  function nextStep(){return state.currentStep<9?goToStep(state.currentStep+1,true):false;}
  function previousStep(){return state.currentStep>0?goToStep(state.currentStep-1,false):false;}
  function finalizeCharacter(){for(let i=0;i<6;i++)if(!validateStep(i))return false;state.currentStep=9;state.completedSteps[9]=true;state.finalized=true;saveLocal(true);emit("aerion:ficha:finalize",{state:clone(state)});render();return true;}
  function reset(){state=DEFAULT();localStorage.removeItem(STORAGE);saveLocal(true);emit("aerion:ficha:update",{state:clone(state)});render();}
  function setState(partial){const d=DEFAULT(),p=clone(partial)||{};state={...d,...state,...p,appearance:{...d.appearance,...state.appearance,...(p.appearance||{})},mana:{...d.mana,...state.mana,...(p.mana||{})},hp:{...d.hp,...state.hp,...(p.hp||{})},derivedStats:{...d.derivedStats,...state.derivedStats,...(p.derivedStats||{})}};calculateRules();computeCompletion();saveLocal();emit("aerion:ficha:update",{state:clone(state)});render();}
  function handleInput(e){const t=e.target;if(!t)return;if(t.dataset.field){state[t.dataset.field]=t.dataset.field==="age"?num(t.value):t.value;commit();}if(t.dataset.appearance)setAppearance(t.dataset.appearance,t.value);if(t.dataset.power)setPowerValue(t.dataset.power,t.value);if(t.dataset.skillBonus)setSkillBonus(t.dataset.id,t.value);if(t.dataset.technique)updateTechnique(t.dataset.id,t.dataset.technique,t.value);if(t.dataset.item)updateItem(t.dataset.id,t.dataset.item,t.value);}
  function handleClick(e){const a=e.target.closest("[data-action]");if(a){const x=a.dataset.action;if(x==="next-step")nextStep();else if(x==="previous-step")previousStep();else if(x==="roll-power")rollPowerD100();else if(x==="select-race")chooseRace(a.dataset.race);else if(x==="select-animalha-category")chooseAnimalCategory(a.dataset.category);else if(x==="select-animalha")chooseAnimal(a.dataset.animal);else if(x==="select-class")chooseClass(a.dataset.class);else if(x==="assign-die")assignDie(a.dataset.attribute,a.dataset.die);else if(x==="remove-die")removeDie(a.dataset.attribute);else if(x==="select-uncommon-power")selectUncommonPower(a.dataset.power);else if(x==="toggle-skill")toggleSkill(a.dataset.skill);else if(x==="remove-technique")removeTechnique(a.dataset.id);else if(x==="add-technique")addTechnique();else if(x==="remove-item")removeItem(a.dataset.id);else if(x==="add-item")addItem();else if(x==="select-skin")setAppearance("skinTone",a.dataset.value);else if(x==="select-hair")setAppearance("hairColor",a.dataset.value);else if(x==="select-eyes")setAppearance("eyeColor",a.dataset.value);else if(x==="finalize")finalizeCharacter();}
    const g=e.target.closest("[data-field-choice]");if(g&&g.dataset.field==="gender")chooseGender(g.dataset.value);const step=e.target.closest(".creation-step");if(step)goToStep(num(step.dataset.step),false);if(e.target.id==="skin-picker-button"){const p=$("#skin-picker");if(p)p.hidden=!p.hidden;}}
  function render(){calculateRules();computeCompletion();const current=state.currentStep,key=STEPS[current][0];$$(".creation-panel").forEach(p=>p.hidden=p.dataset.panel!==key);$$(".creation-step").forEach(b=>{const i=num(b.dataset.step);b.classList.toggle("is-active",i===current);b.classList.toggle("is-done",!!state.completedSteps[i]);b.disabled=i>current+1;});const pct=Math.round(current/9*100);$("#progressBar")&&($("#progressBar").style.width=pct+"%");$("#progressPercent")&&($("#progressPercent").textContent=pct+"%");$(".progress-track")?.setAttribute("aria-valuenow",pct);$$('[data-current-step]').forEach(e=>e.textContent=current+1);$$('[data-total-steps]').forEach(e=>e.textContent=10);$$('[data-current-step-title]').forEach(e=>e.textContent=STEPS[current][1]);const next=$('[data-action="next-step"]');if(next)next.hidden=current===9;$("#aerion-finalize-bottom")?.toggleAttribute("hidden",current!==9);$("#aerion-header-finalize")?.toggleAttribute("hidden",current!==9);emit("aerion:ficha:render",{state:clone(state)});}
  document.addEventListener("input",handleInput);document.addEventListener("change",handleInput);document.addEventListener("click",handleClick);
  function start(){if(started)return;started=true;loadLocal();window.AERIONFicha=API;window.AERION_FICHA=API;render();emit("aerion:ficha:ready",{state:clone(state)});}
  const API={getState:()=>clone(state),setState,reset,nextStep,previousStep,goToStep,validateCurrentStep:()=>validateStep(),finalizeCharacter,rollPowerD100,selectUncommonPower,setPowerValue:setPowerValue,setAppearance,chooseGender,chooseRace,chooseAnimalCategory,chooseAnimal,chooseClass,assignDie,removeDie,toggleSkill,setSkillBonus,addTechnique,updateTechnique,removeTechnique,addItem,updateItem,removeItem,getAttributes:()=>clone(ATTRIBUTES),getSkills:()=>clone(SKILLS),getClasses:()=>clone(CLASSES),getDice:()=>clone(DICE),getSteps:()=>clone(STEPS)};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
})();
