import { aeriom, ensureAfterlifeSession } from './aeriom-client-v2.js?v=20260915-6';

(() => {
  'use strict';
  const $=id=>document.getElementById(id);const qs=new URLSearchParams(location.search);
  const getCampaignId=()=>qs.get('campaign')||qs.get('id')||sessionStorage.getItem('afterlife_current_campaign_id')||'';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const labels={setup:'PREPARAÇÃO',active:'EM COMBATE',ended:'ENCERRADO'};
  let campaign=null,role='player',userId=null,combat=null,combatants=[],events=[],rewards=[],characters=[];let busy=false,combatChannel=null,detailChannel=null,poll=null;
  const actor=()=>combatants.find(x=>x.id===combat?.turn_combatant_id)||null;
  const ownNow=()=>combatants.find(x=>x.owner_user_id===userId&&x.id===combat?.turn_combatant_id&&!x.defeated_at)||null;
  const nameOf=id=>combatants.find(x=>x.id===id)?.display_name||'—';
  const attrTechCost=t=>Math.max(0,Number(t?.manaCost??t?.mana_cost??t?.cost) || 0);

  function status(text){if($('combatSubtitle'))$('combatSubtitle').textContent=text||'';}
  function actionList(c){if(!c||c.defeated_at)return[];const s=c.action_state||{},list=[];if(s.main!==false){list.push(['basic_attack','👊 ATAQUE',true]);list.push(['ranged_attack','🎯 DISTÂNCIA',true]);list.push(['kick','🦵 CHUTE',true]);}if(s.quick!==false)list.push(['quick_strike','⚡ GOLPE RÁPIDO',true]);if(s.reaction!==false)list.push(['defend','◇ DEFENDER',false]);if(s.move!==false)list.push(['move','↗ MOVIMENTO',false]);(Array.isArray(c.metadata?.techniques)?c.metadata.techniques:[]).forEach((t,i)=>{if(t&&typeof t==='object')list.push([`technique:${i}`,`✦ ${String(t.name||`Técnica ${i+1}`).slice(0,25)}${attrTechCost(t)?` · ${attrTechCost(t)}M`:''}`,true]);});return list;}
  function allowed(c){return Boolean(c&&role==='master'||c&&c.owner_user_id===userId&&c.id===combat?.turn_combatant_id);}

  async function bootData(){
    const session=await ensureAfterlifeSession();if(!session?.user)throw new Error('Sessão Afterlife não encontrada.');userId=session.user.id;const id=getCampaignId();if(!id)throw new Error('Campanha não definida.');
    const c=await aeriom.from('campaigns').select('id,name').eq('id',id).maybeSingle();if(c.error)throw c.error;if(!c.data)throw new Error('Campanha não encontrada.');campaign=c.data;sessionStorage.setItem('afterlife_current_campaign_id',id);
    const m=await aeriom.from('campaign_members').select('role').eq('campaign_id',id).eq('user_id',userId).maybeSingle();if(m.error)throw m.error;if(!m.data)throw new Error('Você não participa desta campanha.');role=m.data.role==='master'?'master':'player';
    $('combatTitle').textContent=campaign.name;$('combatCrumb').textContent=campaign.name;$('combatBack').href=`./campanha.html?campaign=${encodeURIComponent(id)}`;$('combatBackBtn').onclick=()=>location.href=`./campanha.html?campaign=${encodeURIComponent(id)}`;$('createCombat').hidden=role!=='master';$('masterSetup').hidden=role!=='master';
  }
  async function loadCharacters(){if(role!=='master')return;const r=await aeriom.rpc('list_campaign_available_characters',{p_campaign_id:campaign.id});if(r.error)throw r.error;characters=r.data||[];const el=$('characterSelect');if(el)el.innerHTML=characters.length?characters.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join(''):'<option value="">Nenhum personagem elegível</option>';}
  async function loadCombats(preferredId=null){const r=await aeriom.rpc('list_campaign_combats',{p_campaign_id:campaign.id,p_limit:15});if(r.error)throw r.error;const list=r.data||[];const next=list.find(x=>x.id===preferredId)||list.find(x=>x.status==='active'||x.status==='setup')||list[0]||null;combat=next;if(combat)await loadDetails();else{combatants=[];events=[];rewards=[];render();}}
  async function loadDetails(){const [a,e,r]=await Promise.all([aeriom.rpc('list_campaign_combatants',{p_combat_id:combat.id}),aeriom.rpc('list_campaign_combat_events',{p_combat_id:combat.id,p_limit:100}),aeriom.rpc('list_campaign_combat_rewards',{p_combat_id:combat.id})]);if(a.error)throw a.error;if(e.error)throw e.error;if(r.error)throw r.error;combatants=a.data||[];events=(e.data||[]).reverse();rewards=r.data||[];render();}

  function renderState(){
    $('combatStatus').textContent=combat?labels[combat.status]||combat.status:'SEM COMBATE';$('combatRound').textContent=combat?.status==='setup'?'—':String(combat?.round??'—');$('combatTurn').textContent=actor()?.display_name||'—';
    const box=$('turnCard');if(!combat){box.innerHTML='<div class="combat-empty"><strong>Nenhum combate ativo</strong><span>O Mestre pode criar um novo encontro.</span></div>';return;}if(combat.status==='setup'){box.innerHTML='<div class="combat-empty"><strong>Combate em preparação</strong><span>Adicione sobreviventes e ameaças antes de iniciar.</span></div>';return;}const a=actor();box.innerHTML=`<div class="combat-turn"><div><span>VEZ DE</span><strong>${esc(a?.display_name||'—')}</strong><small>${a?.entity_type==='character'?'Sobrevivente':'Ameaça'} · iniciativa ${a?.initiative_roll??'—'}</small></div><b>RODADA ${combat.round}</b></div>`;
  }
  function renderRoster(){const host=$('combatRoster');host.replaceChildren();combatants.slice().sort((a,b)=>(Number(b.initiative_roll)-Number(a.initiative_roll))||(Number(a.sort_order)-Number(b.sort_order))).forEach(c=>{const row=document.createElement('article');row.className='combatant-card';if(c.id===combat?.turn_combatant_id)row.classList.add('is-turn');if(c.defeated_at)row.classList.add('is-defeated');const hp=Math.max(0,Number(c.hp_current)||0),max=Math.max(1,Number(c.hp_max)||1),pct=Math.min(100,Math.round(hp/max*100));row.innerHTML=`<div class="combatant-card__top"><div><span>${c.entity_type==='character'?'SOBREVIVENTE':c.entity_type==='npc'?'NPC':'CRIATURA'}</span><strong>${esc(c.display_name)}</strong></div><b class="initiative">${combat?.status==='setup'?'—':c.initiative_roll}</b></div><div class="combatant-hp"><div><span>PV</span><strong>${hp}/${max}</strong></div><i><em style="width:${pct}%"></em></i></div><div class="combatant-meta"><span>DEF ${c.defense}</span><span>MOV ${c.movement}</span>${c.mana_max?`<span>MANA ${c.mana_current}/${c.mana_max}</span>`:''}${c.defeated_at?'<b>DERROTADO</b>':''}</div>${role==='master'?`<button class="mini-btn" data-remove="${esc(c.id)}">REMOVER</button>`:''}`;host.appendChild(row);row.querySelector('[data-remove]')?.addEventListener('click',()=>removeCombatant(c.id));});bindSelectors();}
  function bindSelectors(){const actors=$('actorSelect'),targets=$('targetSelect');if(actors){const old=actors.value;actors.innerHTML=combatants.filter(c=>!c.defeated_at).map(c=>`<option value="${esc(c.id)}">${esc(c.display_name)}</option>`).join('');actors.value=combatants.some(c=>c.id===old&&!c.defeated_at)?old:(actor()?.id||'');}if(targets){const old=targets.value;targets.innerHTML='<option value="">Selecione o alvo</option>'+combatants.filter(c=>!c.defeated_at).map(c=>`<option value="${esc(c.id)}">${esc(c.display_name)}</option>`).join('');targets.value=combatants.some(c=>c.id===old&&!c.defeated_at)?old:'';}}
  function renderActions(){const masterHost=$('masterActionGrid'),playerHost=$('playerActionGrid');const fill=(host,c)=>{if(!host)return;host.replaceChildren();if(!c){host.innerHTML='<span class="combat-hint">Nenhum atuante disponível.</span>';return;}actionList(c).forEach(([key,label,needsTarget])=>{const b=document.createElement('button');b.type='button';b.className='combat-action';b.textContent=label;b.disabled=busy||!allowed(c);b.onclick=()=>doAction(c.id,key,needsTarget?$('targetSelect')?.value:null);host.appendChild(b);});};fill(masterHost,role==='master'?combatants.find(c=>c.id===$('actorSelect')?.value):null);fill(playerHost,ownNow());if($('playerActionHint'))$('playerActionHint').textContent=ownNow()?`Seu turno: ${ownNow().display_name}.`:'Aguardando seu turno.';}
  function renderPanels(){$('masterSetup').hidden=role!=='master'||Boolean(combat&&combat.status!=='setup');$('masterActions').hidden=role!=='master'||!combat||combat.status!=='active';$('playerActions').hidden=role==='master'||!combat||combat.status!=='active';}
  function renderLog(){const host=$('combatLog');host.replaceChildren();events.slice().reverse().slice(0,40).forEach(e=>{const p=e.payload||{},text=e.event_type==='attack'?`${nameOf(e.actor_combatant_id)} atacou ${nameOf(e.target_combatant_id)} · ${p.total??'—'} vs DEF ${p.defense??'—'} · dano ${p.damage??0}${p.target_defeated?' · DERROTADO':''}`:e.event_type==='turn_started'?`Turno de ${nameOf(e.actor_combatant_id)}`:e.event_type==='combat_started'?'Combate iniciado.':e.event_type==='combat_ended'?'Combate encerrado.':e.event_type==='defend'?`${nameOf(e.actor_combatant_id)} preparou defesa +${p.defense_bonus||2}`:`${nameOf(e.actor_combatant_id)} usou ${e.action_key||e.event_type}`;const row=document.createElement('div');row.className='combat-log-row';row.innerHTML=`<span>R${e.round||0}</span><p>${esc(text)}</p>`;host.appendChild(row);});if(!host.children.length)host.innerHTML='<small>Nenhum evento ainda.</small>';}
  function renderRewards(){const host=$('combatRewards');host.replaceChildren();rewards.forEach(r=>{const killer=nameOf(r.killer_combatant_id),loot=Array.isArray(r.loot)?r.loot:[],killerCombatant=combatants.find(c=>c.id===r.killer_combatant_id),own=killerCombatant?.owner_user_id===userId;const card=document.createElement('div');card.className='reward-card';card.innerHTML=`<div><strong>Último golpe: ${esc(killer)}</strong><span>XP recebido: ${r.xp_amount||0}</span></div><div class="reward-loot">${loot.length?loot.map(x=>`<span>${esc(x.name||'Item')} ×${Number(x.quantity||1)}</span>`).join(''):'Sem loot configurado'}</div>${own&&!r.loot_claimed?'<button class="combat-btn combat-btn--primary" data-claim>PEGAR LOOT</button>':r.loot_claimed?'<small>Loot coletado.</small>':''}`;host.appendChild(card);card.querySelector('[data-claim]')?.addEventListener('click',()=>claimLoot(r.id));});if(!host.children.length)host.innerHTML='<small>Nenhuma recompensa ainda.</small>';}
  function render(){renderState();renderRoster();renderPanels();renderActions();renderLog();renderRewards();}

  async function createCombat(){if(busy||role!=='master')return;busy=true;try{const r=await aeriom.rpc('create_campaign_combat',{p_campaign_id:campaign.id});if(r.error)throw r.error;combat=r.data;combatants=[];events=[];rewards=[];status('Combate criado. Adicione os participantes.');}catch(e){status(e?.message||'Não foi possível criar o combate.');}finally{busy=false;render();}}
  async function addCharacter(){if(busy||!combat||combat.status!=='setup')return;const id=$('characterSelect')?.value;if(!id)return;busy=true;try{const r=await aeriom.rpc('add_campaign_combat_character',{p_combat_id:combat.id,p_character_id:id});if(r.error)throw r.error;await loadDetails();}catch(e){status(e?.message||'Não foi possível adicionar o personagem.');}finally{busy=false;render();}}
  async function addCreature(){if(busy||!combat||combat.status!=='setup')return;const name=$('creatureName')?.value?.trim()||'Criatura';const hp=Math.max(1,Number($('creatureHp')?.value)||12),defense=Math.max(0,Number($('creatureDefense')?.value)||10),movement=Math.max(0,Number($('creatureMovement')?.value)||0),initiative=Math.max(4,Number($('creatureInitiative')?.value)||8);let meta={initiative_die:initiative};try{const raw=$('creatureMeta')?.value?.trim();if(raw)meta={...meta,...JSON.parse(raw)};}catch{status('JSON de XP/Loot inválido.');return;}busy=true;try{const r=await aeriom.rpc('add_campaign_combat_creature',{p_combat_id:combat.id,p_name:name,p_hp_max:hp,p_defense:defense,p_movement:movement,p_metadata:meta});if(r.error)throw r.error;$('creatureName').value='';await loadDetails();}catch(e){status(e?.message||'Não foi possível adicionar a criatura.');}finally{busy=false;render();}}
  async function startCombat(){if(busy||!combat)return;busy=true;try{const r=await aeriom.rpc('start_campaign_combat',{p_combat_id:combat.id});if(r.error)throw r.error;combat=r.data;await loadDetails();status('Iniciativa definida. Combate iniciado.');}catch(e){status(e?.message||'Não foi possível iniciar o combate.');}finally{busy=false;render();}}
  async function doAction(actorId,key,targetId){if(busy||!combat||combat.status!=='active')return;if(!allowed(combatants.find(c=>c.id===actorId)))return;if(!['move','defend'].includes(key)&&!targetId){status('Selecione um alvo.');return;}busy=true;try{const r=await aeriom.rpc('resolve_campaign_combat_action',{p_combat_id:combat.id,p_actor_id:actorId,p_target_id:targetId||null,p_action_key:key});if(r.error)throw r.error;await loadDetails();if(r.data?.target_defeated)status(`${nameOf(actorId)} deu o último golpe em ${nameOf(targetId)}.`);else status(key==='move'?'Movimento usado.':key==='defend'?'Defesa preparada.':`Ação resolvida · ${r.data?.damage??0} dano.`);}catch(e){status(e?.message||'Não foi possível resolver a ação.');}finally{busy=false;render();}}
  async function advanceTurn(){if(busy||!combat||role!=='master')return;busy=true;try{const r=await aeriom.rpc('advance_campaign_combat_turn',{p_combat_id:combat.id});if(r.error)throw r.error;combat=r.data;await loadDetails();}catch(e){status(e?.message||'Não foi possível avançar o turno.');}finally{busy=false;render();}}
  async function endCombat(){if(busy||!combat||role!=='master'||!confirm('Encerrar este combate?'))return;busy=true;try{const r=await aeriom.rpc('end_campaign_combat',{p_combat_id:combat.id});if(r.error)throw r.error;combat=r.data;await loadDetails();status('Combate encerrado.');}catch(e){status(e?.message||'Não foi possível encerrar o combate.');}finally{busy=false;render();}}
  async function removeCombatant(id){if(busy||role!=='master'||!confirm('Remover este participante do combate?'))return;busy=true;try{const r=await aeriom.rpc('remove_campaign_combatant',{p_combatant_id:id});if(r.error)throw r.error;await loadDetails();}catch(e){status(e?.message||'Não foi possível remover.');}finally{busy=false;render();}}
  async function claimLoot(id){if(busy)return;busy=true;try{const r=await aeriom.rpc('claim_campaign_combat_loot',{p_reward_id:id});if(r.error)throw r.error;await loadDetails();status('Loot adicionado ao inventário.');}catch(e){status(e?.message||'Não foi possível coletar o loot.');}finally{busy=false;render();}}
  function subscribeCampaign(){if(combatChannel){try{aeriom.removeChannel(combatChannel);}catch{}}if(detailChannel){try{aeriom.removeChannel(detailChannel);}catch{}}combatChannel=aeriom.channel(`afterlife-combat-list:${campaign.id}`).on('postgres_changes',{event:'*',schema:'public',table:'campaign_combats',filter:`campaign_id=eq.${campaign.id}`},()=>loadCombats(combat?.id).catch(()=>{})).subscribe();if(combat){detailChannel=aeriom.channel(`afterlife-combat-detail:${combat.id}`).on('postgres_changes',{event:'*',schema:'public',table:'campaign_combatants',filter:`combat_id=eq.${combat.id}`},()=>loadDetails().catch(()=>{})).on('postgres_changes',{event:'*',schema:'public',table:'campaign_combat_events',filter:`combat_id=eq.${combat.id}`},()=>loadDetails().catch(()=>{})).on('postgres_changes',{event:'*',schema:'public',table:'campaign_combat_rewards',filter:`combat_id=eq.${combat.id}`},()=>loadDetails().catch(()=>{})).subscribe();}}
  function startPolling(){clearInterval(poll);poll=setInterval(()=>{if(!document.hidden)loadCombats(combat?.id).catch(()=>{});},5000);}
  function bind(){
    $('createCombat').onclick=createCombat;$('addCharacter').onclick=addCharacter;$('addCreature').onclick=addCreature;$('startCombat').onclick=startCombat;$('advanceTurn').onclick=advanceTurn;$('endCombat').onclick=endCombat;$('actorSelect')?.addEventListener('change',renderActions);$('targetSelect')?.addEventListener('change',renderActions);
  }
  async function boot(){try{await bootData();bind();await loadCharacters();await loadCombats();subscribeCampaign();startPolling();render();status(combat?'Combate sincronizado em tempo real.':'Aguardando o Mestre criar um combate.');}catch(e){console.error('[AFTERLIFE][COMBAT][BOOT]',e);status(e?.message||'Não foi possível carregar o combate.');}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();