import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const slides = [...document.querySelectorAll('.builder-slide')];
  const steps = [...document.querySelectorAll('.builder-step')];
  const track = $('carouselTrack');
  const dots = $('carouselDots');
  const AERIOM_URL = 'https://kitlpowgcugvlxwhwhqv.supabase.co';
  const AERIOM_KEY = 'sb_publishable_WDlPiR0b8T6mlQfYMbwjGg_BGvQPZDW';
  const sb = createClient(AERIOM_URL, AERIOM_KEY, { auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true} });

  let index=0, classIndex=1, previewObjectUrl=null, touchX=null, touchY=null;
  const spriteMap={AU:{row:0,col:0},ZA:{row:0,col:2},EG:{row:0,col:4},DE:{row:1,col:0},IT:{row:1,col:2},ES:{row:1,col:4},PT:{row:2,col:0},IN:{row:2,col:2},CA:{row:2,col:4},MX:{row:3,col:0},AR:{row:3,col:2},GB:{row:3,col:4},FR:{row:4,col:0},BR:{row:4,col:2},JP:{row:4,col:4},KR:{row:5,col:0},CN:{row:5,col:2},US:{row:5,col:4}};
  const genderOffset={Masculino:0,Feminino:1};
  const countries=[['BR','Brasil','🇧🇷'],['JP','Japão','🇯🇵'],['KR','Coreia do Sul','🇰🇷'],['CN','China','🇨🇳'],['US','Estados Unidos','🇺🇸'],['CA','Canadá','🇨🇦'],['MX','México','🇲🇽'],['AR','Argentina','🇦🇷'],['GB','Reino Unido','🇬🇧'],['FR','França','🇫🇷'],['DE','Alemanha','🇩🇪'],['IT','Itália','🇮🇹'],['ES','Espanha','🇪🇸'],['PT','Portugal','🇵🇹'],['IN','Índia','🇮🇳'],['AU','Austrália','🇦🇺'],['ZA','África do Sul','🇿🇦'],['EG','Egito','🇪🇬']];
  const attrs={forca:8,agilidade:8,vigor:8,percepcao:8,mente:8,vontade:8}; const BASE=8,MAX=15,POINTS=12;
  const formulas=()=>({hp:10+(attrs.vigor-8)*2,def:10+(attrs.agilidade-8)+Math.floor((attrs.percepcao-8)/2),stamina:6+Math.floor((attrs.vigor-8+attrs.agilidade-8)/2),attack:5+(attrs.forca-8),focus:5+Math.floor((attrs.mente-8+attrs.vontade-8)/2)});
  const countryInfo=()=>countries.find(x=>x[0]===($('countryOrigin')?.value||'BR'))||countries[0];
  const currentGender=()=>$('characterGender')?.value||'Masculino';
  function spritePosition(code,gender){const b=spriteMap[code]||spriteMap.BR;return{x:(b.col+genderOffset[gender||'Masculino'])*20,y:b.row*20};}
  function setSprite(el,code,gender){if(!el)return;const p=spritePosition(code,gender);el.style.backgroundPosition=`${p.x}% ${p.y}%`;}
  function renderDots(){dots?.replaceChildren();slides.forEach((_,i)=>{const b=document.createElement('button');b.type='button';b.className=i===index?'is-active':'';b.setAttribute('aria-label',`Ir para etapa ${i+1}`);b.addEventListener('click',()=>goTo(i));dots?.appendChild(b);});}
  function updatePreview(){const [code,name,flag]=countryInfo(),gender=currentGender(),cls=$('classReadout')?.textContent||'Sobrevivente';if($('previewSub'))$('previewSub').textContent=`Humano · ${cls} · ${name}`;setSprite($('previewSprite'),code,gender);setSprite($('originCharacterSprite'),code,gender);setSprite($('appearancePresetSprite'),code,gender);setSprite($('finalSprite'),code,gender);if($('originGenderLabel'))$('originGenderLabel').textContent=gender.toUpperCase();if($('originReferenceCountry'))$('originReferenceCountry').textContent=name;}
  function updateStepStatus(){const labels=['IDENTIDADE','ORIGEM','APARÊNCIA','CLASSE','ATRIBUTOS','CONCEITO','REVISÃO FINAL'];if($('stepStatusLabel'))$('stepStatusLabel').textContent=labels[index]||'CONFIGURAÇÃO';}
  function goTo(next){index=Math.max(0,Math.min(next,slides.length-1));slides.forEach((s,i)=>s.classList.toggle('is-active',i===index));steps.forEach((s,i)=>{s.classList.toggle('is-active',i===index);s.classList.toggle('is-complete',i<index);});if($('stepCount'))$('stepCount').textContent=`${String(index+1).padStart(2,'0')} / ${String(slides.length).padStart(2,'0')}`;if($('progressBar'))$('progressBar').style.width=`${((index+1)/slides.length)*100}%`;if($('prevStep'))$('prevStep').disabled=index===0;if($('backStep'))$('backStep').disabled=index===0;if($('nextStep'))$('nextStep').disabled=index===slides.length-1;if($('nextAction'))$('nextAction').textContent=index===slides.length-1?'FINALIZAR FICHA ✓':'CONTINUAR →';updateStepStatus();renderDots();renderFinalReview();}
  function populateCountries(){const s=$('countryOrigin');if(!s)return;s.replaceChildren();countries.forEach(([code,name])=>{const o=document.createElement('option');o.value=code;o.textContent=name;s.appendChild(o);});s.value='BR';updateCountry();}
  function updateCountry(){const [code,name,flag]=countryInfo();$('countryFlag')&&($('countryFlag').textContent=flag);$('countryName')&&($('countryName').textContent=name);$('countryHint')&&($('countryHint').textContent='Modelo de referência por nacionalidade · totalmente ajustável.');$('appearancePresetTitle')&&($('appearancePresetTitle').textContent=`Preset de origem · ${name}`);$('appearancePresetText')&&($('appearancePresetText').textContent='Personagem-base carregado para essa nacionalidade e gênero.');updatePreview();renderFinalReview();}
  function selectClass(card){const cards=[...document.querySelectorAll('.class-card')],i=cards.indexOf(card);if(i<0)return;cards.forEach((c,n)=>{c.classList.toggle('selected',n===i);c.classList.toggle('side',n!==i);});classIndex=i;if($('classReadout'))$('classReadout').textContent=card.dataset.class||card.querySelector('b')?.textContent||'Sobrevivente';if($('classIndex'))$('classIndex').textContent=`${i+1} / ${cards.length}`;updatePreview();renderFinalReview();}
  function moveClass(d){const cards=[...document.querySelectorAll('.class-card')];if(!cards.length)return;let i=cards.findIndex(c=>c.classList.contains('selected'));if(i<0)i=classIndex;selectClass(cards[(i+d+cards.length)%cards.length]);}
  function renderAttrs(){const spent=Object.values(attrs).reduce((s,v)=>s+(v-BASE),0),left=Math.max(0,POINTS-spent);$('pointsRemaining')&&($('pointsRemaining').textContent=left);Object.entries(attrs).forEach(([k,v])=>{const box=document.querySelector(`[data-attr="${k}"]`);if(!box)return;const strong=box.querySelector('strong');if(strong)strong.textContent=v;const em=box.querySelector('em');if(em)em.style.width=`${Math.round(v/MAX*100)}%`;box.querySelector(`[data-minus="${k}"]`)?.toggleAttribute('disabled',v<=BASE);box.querySelector(`[data-plus="${k}"]`)?.toggleAttribute('disabled',v>=MAX||left<=0);});updateLiveStats();renderFinalReview();}
  function changeAttr(k,d){if(!(k in attrs))return;const spent=Object.values(attrs).reduce((s,v)=>s+(v-BASE),0),left=POINTS-spent;if(d>0&&(attrs[k]>=MAX||left<=0))return;if(d<0&&attrs[k]<=BASE)return;attrs[k]+=d;renderAttrs();}
  function setBar(id,v,min,max){const pct=Math.max(5,Math.min(100,(v-min)/(max-min)*100));if($(id+'Value'))$(id+'Value').textContent=v;if($(id+'Bar'))$(id+'Bar').style.width=`${pct}%`;}
  function updateLiveStats(){const f=formulas();setBar('liveHp',f.hp,10,24);setBar('liveDef',f.def,10,20);setBar('liveStamina',f.stamina,6,13);setBar('liveAttack',f.attack,5,12);setBar('liveFocus',f.focus,5,12);if($('previewHp'))$('previewHp').textContent=f.hp;if($('previewDef'))$('previewDef').textContent=f.def;if($('previewStamina'))$('previewStamina').textContent=f.stamina;if($('previewStaminaCylinder'))$('previewStaminaCylinder').textContent=f.stamina;if($('previewStaminaMax'))$('previewStaminaMax').textContent=13;if($('finalHp'))$('finalHp').textContent=f.hp;if($('finalDef'))$('finalDef').textContent=f.def;if($('finalStamina'))$('finalStamina').textContent=f.stamina;if($('liveHpHint'))$('liveHpHint').textContent=`Vigor ${attrs.vigor}`;if($('liveDefHint'))$('liveDefHint').textContent=`Agilidade ${attrs.agilidade} + Percepção ${attrs.percepcao}`;if($('liveStaminaHint'))$('liveStaminaHint').textContent=`Vigor ${attrs.vigor} + Agilidade ${attrs.agilidade}`;if($('liveAttackHint'))$('liveAttackHint').textContent=`Força ${attrs.forca}`;if($('liveFocusHint'))$('liveFocusHint').textContent=`Mente ${attrs.mente} + Vontade ${attrs.vontade}`;updateStaminaCylinder(f.stamina);}
  function updateStaminaCylinder(current){const max=13,segments=[...document.querySelectorAll('#staminaCylinderCard .stamina-body i')];segments.forEach((seg,i)=>seg.style.opacity=i<current?'1':'.16');}
  function updateHeight(){const m=parseFloat(($('appearanceHeight')?.value||'1,70').replace(',','.'))||1.7;const scale=Math.max(.88,Math.min(1.12,1+(m-1.7)*.55));document.documentElement.style.setProperty('--character-height-scale',scale.toFixed(3));if($('heightReadout'))$('heightReadout').textContent=`${m.toFixed(2).replace('.',',')} m`;renderFinalReview();}
  function updateWeight(v=Number($('appearanceWeight')?.value||70)){if($('appearanceWeight'))$('appearanceWeight').value=v;const pct=(v-45)/75*100;if($('weightReadout'))$('weightReadout').textContent=`${v} kg`;if($('weightBar'))$('weightBar').style.width=`${Math.max(0,Math.min(100,pct))}%`;document.querySelectorAll('[data-weight]').forEach(b=>b.classList.toggle('is-active',Number(b.dataset.weight)===v));renderFinalReview();}
  function handleImage(file){const max=5*1024*1024,types=new Set(['image/jpeg','image/png','image/webp','image/gif']);if(!file)return;if(!types.has(file.type))return alert('Formato não permitido. Use JPG, PNG, WEBP ou GIF.');if(file.size>max)return alert('A imagem precisa ter no máximo 5 MB.');if(previewObjectUrl)URL.revokeObjectURL(previewObjectUrl);previewObjectUrl=URL.createObjectURL(file);$('portraitImg').src=previewObjectUrl;$('portraitImg').hidden=false;$('portraitEmpty').hidden=true;$('removeCharacterImage').hidden=false;$('appearancePresetSprite')?.setAttribute('hidden','hidden');}
  function text(id){return($(id)?.value||'').trim()} function val(id,f='—'){return text(id)||f;}
  function renderFinalReview(){if(!$('finalName'))return;const [code,name,flag]=countryInfo(),gender=currentGender(),f=formulas();$('finalName').textContent=val('characterName','Sem nome');$('finalNickname').textContent=val('characterNickname');$('finalAge').textContent=$('characterAge')?.value?`${$('characterAge').value} anos`:'—';$('finalClass').textContent=$('classReadout')?.textContent||'Sobrevivente';$('finalCountryLine').textContent=`${flag} ${name} · ${gender}`;$('finalSkin').textContent=`Pele: ${$('appearanceSkin')?.value||'Claro'}`;$('finalHair').textContent=`Cabelo: ${$('appearanceHair')?.value||'Preto'}`;$('finalEyes').textContent=`Olhos: ${$('appearanceEyes')?.value||'Castanhos'}`;$('finalAppearanceSummary').textContent=`${$('appearanceHeight')?.value||'1,70 m'} · ${$('appearanceWeight')?.value||'70 kg'}`;$('finalAppearanceDetails').textContent=[text('appearanceScar')?`Marca: ${text('appearanceScar')}`:'',text('appearanceFeatures'),text('appearanceDescription')].filter(Boolean).join(' · ')||'Sem características adicionais.';$('finalPersonality').textContent=val('characterPersonality');$('finalObjective').textContent=val('characterObjective');$('finalFear').textContent=val('characterFear');$('finalHistory').textContent=val('characterHistory');const root=$('finalAttributes');root&&root.replaceChildren();Object.entries(attrs).forEach(([k,v])=>{const names={forca:'Força',agilidade:'Agilidade',vigor:'Vigor',percepcao:'Percepção',mente:'Mente',vontade:'Vontade'};const el=document.createElement('span');el.innerHTML=`<b>${names[k]}</b><strong>${v}</strong>`;root?.appendChild(el);});setSprite($('finalSprite'),code,gender);if($('finalHp'))$('finalHp').textContent=f.hp;if($('finalDef'))$('finalDef').textContent=f.def;if($('finalStamina'))$('finalStamina').textContent=f.stamina;}
  function setupProfile(){const chip=$('profileChip'),drop=$('profileDropdown'),wrap=$('profileWrap');if(!chip||!drop)return;const close=()=>{drop.hidden=true;chip.setAttribute('aria-expanded','false')};chip.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const open=drop.hidden;drop.hidden=!open;chip.setAttribute('aria-expanded',String(open));});document.addEventListener('click',e=>{if(!wrap?.contains(e.target))close()});$('profileSignOut')?.addEventListener('click',async()=>{try{await sb.auth.signOut()}finally{location.replace('../index.html')}});}
  async function loadProfile(){try{const {data}=await sb.auth.getSession();const user=data?.session?.user;if(!user){$('profileName').textContent='Sobrevivente';$('profileDropdownName').textContent='Sobrevivente';return;}const fallback=user.user_metadata?.display_name||user.user_metadata?.full_name||user.email?.split('@')[0]||'Sobrevivente';let name=fallback,avatar=null;const {data:p}=await sb.from('profiles').select('display_name,avatar_path').eq('id',user.id).maybeSingle();if(p?.display_name)name=p.display_name;if(p?.avatar_path){const {data:u}=await sb.storage.from('avatars').createSignedUrl(p.avatar_path,3600);avatar=u?.signedUrl||null;}if($('profileName'))$('profileName').textContent=name;if($('profileDropdownName'))$('profileDropdownName').textContent=name;if($('profileDropdownEmail'))$('profileDropdownEmail').textContent=user.email||'Conta Afterlife';document.querySelectorAll('#profileAvatar,#profileDropdownAvatar').forEach(el=>{el.replaceChildren();if(avatar){const img=document.createElement('img');img.src=avatar;img.alt='';el.appendChild(img)}else el.textContent=name.charAt(0).toUpperCase();});}catch{if($('profileName'))$('profileName').textContent='Sobrevivente';}}

  function bindAppearanceEvents(){
    ['appearanceSkin','appearanceHair','appearanceEyes','appearanceEyeShape','appearanceStyle'].forEach(id=>$(id)?.addEventListener('change',renderFinalReview));
    $('appearanceHeight')?.addEventListener('change',updateHeight);
    document.querySelectorAll('[data-weight]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();updateWeight(Number(b.dataset.weight))}));
  }
  function bindInputs(){
    $('characterName')?.addEventListener('input',e=>{if($('previewName'))$('previewName').textContent=e.target.value.trim()||'Sem nome';renderFinalReview()});
    ['characterNickname','characterAge','characterPersonality','characterObjective','characterFear','characterHistory','appearanceScar','appearanceFeatures','appearanceDescription'].forEach(id=>$(id)?.addEventListener('input',renderFinalReview));
    $('characterGender')?.addEventListener('change',()=>{updatePreview();renderFinalReview()});
    $('countryOrigin')?.addEventListener('change',updateCountry);
  }

  steps.forEach(s=>s.addEventListener('click',()=>goTo(Number(s.dataset.step))));
  $('prevStep')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();goTo(index-1)});
  $('nextStep')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();goTo(index+1)});
  $('backStep')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();goTo(index-1)});
  $('nextAction')?.addEventListener('click',()=>{if(index<slides.length-1)goTo(index+1);else $('nextAction').textContent='FICHA PREPARADA ✓';});
  document.querySelectorAll('.class-card').forEach(c=>c.addEventListener('click',()=>selectClass(c)));
  document.querySelectorAll('[data-class-prev]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();moveClass(-1)}));
  document.querySelectorAll('[data-class-next]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();moveClass(1)}));
  document.querySelectorAll('[data-plus]').forEach(b=>b.addEventListener('click',()=>changeAttr(b.dataset.plus,1)));
  document.querySelectorAll('[data-minus]').forEach(b=>b.addEventListener('click',()=>changeAttr(b.dataset.minus,-1)));
  $('uploadCharacterImage')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();$('characterImageFile')?.click()});
  $('characterImageFile')?.addEventListener('change',e=>handleImage(e.target.files?.[0]));
  $('removeCharacterImage')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(previewObjectUrl)URL.revokeObjectURL(previewObjectUrl);previewObjectUrl=null;$('portraitImg').src='';$('portraitImg').hidden=true;$('portraitEmpty').hidden=false;$('removeCharacterImage').hidden=true;$('appearancePresetSprite')?.removeAttribute('hidden');});
  track?.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'||e.target.closest('input,select,textarea,button,a,label')){touchX=touchY=null;return}touchX=e.clientX;touchY=e.clientY},{passive:true});
  track?.addEventListener('pointerup',e=>{if(e.pointerType!=='touch'||touchX===null||touchY===null)return;const dx=e.clientX-touchX,dy=e.clientY-touchY;touchX=touchY=null;if(Math.abs(dx)<55||Math.abs(dx)<Math.abs(dy)*1.2)return;goTo(index+(dx<0?1:-1))},{passive:true});
  document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT','BUTTON','A'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight')goTo(index+1);if(e.key==='ArrowLeft')goTo(index-1)});
  setupProfile();bindInputs();bindAppearanceEvents();populateCountries();updateWeight(70);updateHeight();renderAttrs();selectClass(document.querySelector('.class-card.selected')||document.querySelector('.class-card'));updatePreview();updateLiveStats();renderFinalReview();goTo(0);loadProfile();
})();
