import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const slides = [...document.querySelectorAll('.builder-slide')];
  const steps = [...document.querySelectorAll('.builder-step')];
  const track = $('carouselTrack');
  const dots = $('carouselDots');
  const AERIOM_URL = 'https://kitlpowgcugvlxwhwhqv.supabase.co';
  const AERIOM_KEY = 'sb_publishable_WDlPiR0b8T6mlQfYMbwjGg_BGvQPZDW';
  const sb = createClient(AERIOM_URL, AERIOM_KEY, {auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});

  let index = 0;
  let classIndex = 1;
  let previewObjectUrl = null;
  let touchX = null;
  let touchY = null;

  const spriteMap = {
    AU:{row:0,col:0}, ZA:{row:0,col:2}, EG:{row:0,col:4},
    DE:{row:1,col:0}, IT:{row:1,col:2}, ES:{row:1,col:4},
    PT:{row:2,col:0}, IN:{row:2,col:2}, CA:{row:2,col:4},
    MX:{row:3,col:0}, AR:{row:3,col:2}, GB:{row:3,col:4},
    FR:{row:4,col:0}, BR:{row:4,col:2}, JP:{row:4,col:4},
    KR:{row:5,col:0}, CN:{row:5,col:2}, US:{row:5,col:4}
  };
  const genderOffset = {Masculino:0,Feminino:1};
  const countries = [
    ['BR','Brasil','🇧🇷'],['JP','Japão','🇯🇵'],['KR','Coreia do Sul','🇰🇷'],['CN','China','🇨🇳'],['US','Estados Unidos','🇺🇸'],['CA','Canadá','🇨🇦'],
    ['MX','México','🇲🇽'],['AR','Argentina','🇦🇷'],['GB','Reino Unido','🇬🇧'],['FR','França','🇫🇷'],['DE','Alemanha','🇩🇪'],['IT','Itália','🇮🇹'],
    ['ES','Espanha','🇪🇸'],['PT','Portugal','🇵🇹'],['IN','Índia','🇮🇳'],['AU','Austrália','🇦🇺'],['ZA','África do Sul','🇿🇦'],['EG','Egito','🇪🇬']
  ];
  const attrs = {forca:8,agilidade:8,vigor:8,percepcao:8,mente:8,vontade:8};
  const BASE=8, MAX=15, POINTS=12;
  const formulas = () => ({hp:10+(attrs.vigor-8)*2,def:10+(attrs.agilidade-8)+Math.floor((attrs.percepcao-8)/2),stamina:6+Math.floor((attrs.vigor-8+attrs.agilidade-8)/2),attack:5+(attrs.forca-8),focus:5+Math.floor((attrs.mente-8+attrs.vontade-8)/2)});
  function countryInfo(){return countries.find(x=>x[0]===($('countryOrigin')?.value||'BR'))||countries[0];}
  function spritePosition(code,gender){const base=spriteMap[code]||spriteMap.BR;return {x:(base.col+genderOffset[gender||'Masculino'])*20,y:base.row*20};}
  function setSprite(el,code,gender){if(!el)return;const p=spritePosition(code,gender);el.style.backgroundPosition=`${p.x}% ${p.y}%`;}
  function currentGender(){return $('characterGender')?.value||'Masculino';}
  function renderDots(){dots?.replaceChildren();slides.forEach((_,i)=>{const b=document.createElement('button');b.type='button';b.className=i===index?'is-active':'';b.setAttribute('aria-label',`Ir para etapa ${i+1}`);b.addEventListener('click',()=>goTo(i));dots?.appendChild(b);});}
  function updatePreview(){const info=countryInfo(),gender=currentGender(),cls=$('classReadout')?.textContent||'Sobrevivente';if($('previewSub'))$('previewSub').textContent=`Humano · ${cls} · ${info[1]}`;setSprite($('previewSprite'),info[0],gender);setSprite($('originCharacterSprite'),info[0],gender);setSprite($('appearancePresetSprite'),info[0],gender);setSprite($('finalSprite'),info[0],gender);if($('originGenderLabel'))$('originGenderLabel').textContent=gender.toUpperCase();if($('originReferenceCountry'))$('originReferenceCountry').textContent=info[1];}
  function updateStepStatus(){const labels=['IDENTIDADE','ORIGEM','APARÊNCIA','CLASSE','ATRIBUTOS','CONCEITO','REVISÃO FINAL'];if($('stepStatusLabel'))$('stepStatusLabel').textContent=labels[index]||'CONFIGURAÇÃO';}
  function goTo(next){index=Math.max(0,Math.min(next,slides.length-1));slides.forEach((s,i)=>s.classList.toggle('is-active',i===index));steps.forEach((s,i)=>{s.classList.toggle('is-active',i===index);s.classList.toggle('is-complete',i<index);});if($('stepCount'))$('stepCount').textContent=`${String(index+1).padStart(2,'0')} / ${String(slides.length).padStart(2,'0')}`;if($('progressBar'))$('progressBar').style.width=`${((index+1)/slides.length)*100}%`;if($('prevStep'))$('prevStep').disabled=index===0;if($('backStep'))$('backStep').disabled=index===0;if($('nextStep'))$('nextStep').disabled=index===slides.length-1;if($('nextAction'))$('nextAction').textContent=index===slides.length-1?'FINALIZAR FICHA ✓':'CONTINUAR →';updateStepStatus();renderDots();renderFinalReview();}
  function populateCountries(){const s=$('countryOrigin');if(!s)return;s.replaceChildren();countries.forEach(([code,name,flag])=>{const o=document.createElement('option');o.value=code;o.textContent=name;s.appendChild(o);});s.value='BR';updateCountry();}
  function updateCountry(){const [code,name,flag]=countryInfo();$('countryFlag')&&($('countryFlag').textContent=flag);$('countryName')&&($('countryName').textContent=name);$('countryHint')&&($('countryHint').textContent='Modelo de referência por nacionalidade · totalmente ajustável.');$('appearancePresetTitle')&&($('appearancePresetTitle').textContent=`Preset de origem · ${name}`);$('appearancePresetText')&&($('appearancePresetText').textContent='Personagem-base carregado para essa nacionalidade e gênero.');updatePreview();renderFinalReview();}
  function selectClass(card){const cards=[...document.querySelectorAll('.class-card')],i=cards.indexOf(card);if(i<0)return;cards.forEach((c,n)=>{c.classList.toggle('selected',n===i);c.classList.toggle('side',n!==i);});classIndex=i;$('classReadout').textContent=card.dataset.class||card.querySelector('b')?.textContent||'Sobrevivente';$('classIndex').textContent=`${i+1} / ${cards.length}`;updatePreview();renderFinalReview();}
  function moveClass(d){const cards=[...document.querySelectorAll('.class-card')];if(!cards.length)return;let i=cards.findIndex(c=>c.classList.contains('selected'));if(i<0)i=classIndex;selectClass(cards[(i+d+cards.length)%cards.length]);}
  function renderAttrs(){const spent=Object.values(attrs).reduce((s,v)=>s+(v-BASE),0),left=Math.max(0,POINTS-spent);$('pointsRemaining')&&($('pointsRemaining').textContent=left);Object.entries(attrs).forEach(([k,v])=>{const box=document.querySelector(`[data-attr="${k}"]`);if(!box)return;box.querySelector('strong').textContent=v;const em=box.querySelector('em');if(em)em.style.width=`${Math.round(v/MAX*100)}%`;box.querySelector(`[data-minus="${k}"]`)?.toggleAttribute('disabled',v<=BASE);box.querySelector(`[data-plus="${k}"]`)?.toggleAttribute('disabled',v>=MAX||left<=0);});updateLiveStats();renderFinalReview();}
  function changeAttr(k,d){if(!(k in attrs))return;const spent=Object.values(attrs).reduce((s,v)=>s+(v-BASE),0),left=POINTS-spent;if(d>0&&(attrs[k]>=MAX||left<=0))return;if(d<0&&attrs[k]<=BASE)return;attrs[k]+=d;renderAttrs();}
  function setBar(id,v,min,max){$(id+'Value')&&($(id+'Value').textContent=v);$(id+'Bar')&&($(id+'Bar').style.width=`${Math.max(5,Math.min(100,(v-min)/(max-min)*100))}%`);}
  function updateLiveStats(){const f=formulas();setBar('liveHp',f.hp,10,24);setBar('liveDef',f.def,10,20);setBar('liveStamina',f.stamina,6,13);setBar('liveAttack',f.attack,5,12);setBar('liveFocus',f.focus,5,12);$('previewHp')&&($('previewHp').textContent=f.hp);$('previewDef')&&($('previewDef').textContent=f.def);$('previewStamina')&&($('previewStamina').textContent=f.stamina);$('previewStaminaCylinder')&&($('previewStaminaCylinder').textContent=f.stamina);$('finalHp')&&($('finalHp').textContent=f.hp);$('finalDef')&&($('finalDef').textContent=f.def);$('finalStamina')&&($('finalStamina').textContent=f.stamina);}
  function updateHeight(){const m=parseFloat(($('appearanceHeight')?.value||'1,70').replace(',','.'))||1.7;const scale=Math.max(.88,Math.min(1.12,1+(m-1.7)*.55));document.documentElement.style.setProperty('--character-height-scale',scale.toFixed(3));$('heightReadout')&&($('heightReadout').textContent=`${m.toFixed(2).replace('.',',')} m`);renderFinalReview();}
  function updateWeight(v=Number($('appearanceWeight')?.value||70)){if($('appearanceWeight'))$('appearanceWeight').value=v;const pct=(v-45)/(120-45)*100;$('weightReadout')&&($('weightReadout').textContent=`${v} kg`);$('weightBar')&&($('weightBar').style.width=`${Math.max(0,Math.min(100,pct))}%`);document.querySelectorAll('[data-weight]').forEach(b=>b.classList.toggle('is-active',Number(b.dataset.weight)===v));renderFinalReview();}
  function handleImage(file){const max=5*1024*1024,types=new Set(['image/jpeg','image/png','image/webp','image/gif']);if(!file)return;if(!types.has(file.type))return alert('Formato não permitido. Use JPG, PNG, WEBP ou GIF.');if(file.size>max)return alert('A imagem precisa ter no máximo 5 MB.');if(previewObjectUrl)URL.revokeObjectURL(previewObjectUrl);previewObjectUrl=URL.createObjectURL(file);$('portraitImg').src=previewObjectUrl;$('portraitImg').hidden=false;$('portraitEmpty').hidden=true;$('removeCharacterImage').hidden=false;$('appearancePresetSprite')?.setAttribute('hidden','hidden');}
  function text(id){return($(id)?.value||'').trim()}function val(id,f='—'){return text(id)||f}
  function renderFinalReview(){if(!$('finalName'))return;const [code,name,flag]=countryInfo(),gender=currentGender(),f=formulas();$('finalName').textContent=val('characterName','Sem nome');$('finalNickname').textContent=val('characterNickname');$('finalAge').textContent=$('characterAge')?.value?`${$('characterAge').value} anos`:'—';$('finalClass').textContent=$('classReadout')?.textContent||'Sobrevivente';$('finalCountryLine').textContent=`${flag} ${name} · ${gender}`;$('finalSkin').textContent=`Pele: ${$('appearanceSkin')?.value||'Claro'}`;$('finalHair').textContent=`Cabelo: ${$('appearanceHair')?.value||'Preto'}`;$('finalEyes').textContent=`Olhos: ${$('appearanceEyes')?.value||'Castanhos'}`;$('finalAppearanceSummary').textContent=`${$('appearanceHeight')?.value||'1,70 m'} · ${$('appearanceWeight')?.value||'70 kg'}`;$('finalAppearanceDetails').textContent=[text('appearanceScar')?`Marca: ${text('appearanceScar')}`:'',text('appearanceFeatures'),text('appearanceDescription')].filter(Boolean).join(' · ')||'Sem características adicionais.';$('finalPersonality').textContent=val('characterPersonality');$('finalObjective').textContent=val('characterObjective');$('finalFear').textContent=val('characterFear');$('finalHistory').textContent=val('characterHistory');const root=$('finalAttributes');root&&root.replaceChildren();Object.entries(attrs).forEach(([k,v])=>{const names={forca:'Força',agilidade:'Agilidade',vigor:'Vigor',percepcao:'Percepção',mente:'Mente',vontade:'Vontade'};const el=document.createElement('span');el.innerHTML=`<b>${names[k]}</b><strong>${v}</strong>`;root?.appendChild(el);});setSprite($('finalSprite'),code,gender);}

  function ensureUi(){
    const preview=document.querySelector('.character-preview');
    if(preview && !document.getElementById('staminaCylinderCard')){const card=document.createElement('div');card.id='staminaCylinderCard';card.className='stamina-cylinder-card';card.innerHTML='<div class="stamina-cylinder" aria-hidden="true"><span class="stamina-valve"></span><div class="stamina-body"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="stamina-cylinder-copy"><span>ESTAMINA</span><b><em id="previewStaminaCylinder">6</em> / <span id="previewStaminaMax">13</span></b><small>Representação visual em formato de cilindro.</small></div>';preview.appendChild(card);}
    const os=slides[1],oc=os?.querySelector('.origin-country-card');
    if(os&&oc&&!os.querySelector('.origin-layout')){const layout=document.createElement('div');layout.className='origin-layout';oc.parentNode.insertBefore(layout,oc);layout.appendChild(oc);const ref=document.createElement('div');ref.className='origin-reference-card';ref.innerHTML='<div class="origin-reference-head"><span>PERSONAGEM DE REFERÊNCIA</span><b id="originGenderLabel">MASCULINO</b></div><div class="origin-character-frame"><div class="country-sprite" id="originCharacterSprite"></div></div><div class="origin-reference-foot"><span id="originReferenceCountry">Brasil</span><small>Modelo visual da nacionalidade selecionada</small></div>';layout.appendChild(ref);}
    const as=slides[2],stage=as?.querySelector('.portrait-stage');
    if(as)as.querySelector('.appearance-builder-v2')?.classList.add('appearance-builder-v4');
    if(stage&&!stage.querySelector('#appearancePresetSprite')){const badge=document.createElement('div');badge.className='portrait-reference-badge';badge.textContent='REFERÊNCIA';stage.prepend(badge);const sprite=document.createElement('div');sprite.className='country-sprite portrait-sprite';sprite.id='appearancePresetSprite';stage.prepend(sprite);}
    const panel=as?.querySelector('.portrait-panel');
    if(panel&&!panel.querySelector('.weight-control-card')){const oldScale=panel.querySelector('.weight-scale');const wrap=document.createElement('div');wrap.className='weight-control-card';wrap.innerHTML='<div class="weight-control-head"><span>PESO DO PERSONAGEM</span><b id="weightReadout">70 kg</b></div><div class="weight-quick-buttons">'+[45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120].map(v=>`<button type="button" data-weight="${v}">${v}</button>`).join('')+'</div><div class="weight-thermometer"><span id="weightBar"></span></div><div class="weight-labels"><span>45 kg</span><span>120 kg</span></div></div>';if(oldScale)oldScale.replaceWith(wrap);else panel.appendChild(wrap);}
    const weightSelect=$('appearanceWeight');if(weightSelect?.closest('label'))weightSelect.closest('label').style.display='none';
    document.querySelectorAll('.preview-mini-stats>div,.live-stat-row,.review-stat-strip>span').forEach(el=>{const t=el.textContent.trim().toUpperCase();if(t.startsWith('O₂')||t.startsWith('O2')||t.includes('O₂ / TANQUE')||t.includes('O2 / TANQUE'))el.remove();});
    const rg=slides[6]?.querySelector('.final-review-grid');if(rg)rg.classList.add('final-review-layout-v4');
  }
  function setupProfile(){const chip=$('profileChip'),drop=$('profileDropdown'),wrap=$('profileWrap');const close=()=>{if(drop)drop.hidden=true;chip?.setAttribute('aria-expanded','false')};chip?.addEventListener('click',e=>{e.stopPropagation();const open=drop.hidden;drop.hidden=!open;chip.setAttribute('aria-expanded',String(open));});document.addEventListener('click',e=>{if(!wrap?.contains(e.target))close()});$('profileSignOut')?.addEventListener('click',async()=>{try{await sb.auth.signOut();location.replace('../index.html')}catch{}});}
  async function loadProfile(){try{const {data}=await sb.auth.getSession();const user=data?.session?.user;if(!user)return;const fallback=user.user_metadata?.display_name||user.user_metadata?.full_name||user.email?.split('@')[0]||'Sobrevivente';let name=fallback,avatar=null;const p=await sb.from('profiles').select('display_name,avatar_path').eq('id',user.id).maybeSingle();if(p.data?.display_name)name=p.data.display_name;if(p.data?.avatar_path){const u=await sb.storage.from('avatars').createSignedUrl(p.data.avatar_path,3600);avatar=u.data?.signedUrl||null;}$('profileName').textContent=name;$('profileDropdownName').textContent=name;$('profileDropdownEmail').textContent=user.email||'Conta Afterlife';document.querySelectorAll('#profileAvatar,#profileDropdownAvatar').forEach(el=>{el.replaceChildren();if(avatar){const img=document.createElement('img');img.src=avatar;el.appendChild(img)}else el.textContent=name.charAt(0).toUpperCase();});}catch(e){}}

  steps.forEach(s=>s.addEventListener('click',()=>goTo(Number(s.dataset.step))));$('prevStep')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();goTo(index-1)});$('nextStep')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();goTo(index+1)});$('backStep')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();goTo(index-1)});$('nextAction')?.addEventListener('click',()=>index<slides.length-1?goTo(index+1):($('nextAction').textContent='FICHA PREPARADA ✓'));
  $('characterName')?.addEventListener('input',e=>{$('previewName').textContent=e.target.value.trim()||'Sem nome';renderFinalReview()});['characterNickname','characterGender','characterAge','characterPersonality','characterObjective','characterFear','characterHistory','appearanceScar','appearanceFeatures','appearanceDescription'].forEach(id=>$(id)?.addEventListener('input',()=>{if(id==='characterGender')updatePreview();renderFinalReview()}));$('characterGender')?.addEventListener('change',updatePreview);$('countryOrigin')?.addEventListener('change',updateCountry);['appearanceSkin','appearanceHair','appearanceEyes','appearanceEyeShape','appearanceStyle'].forEach(id=>$(id)?.addEventListener('change',renderFinalReview));$('appearanceHeight')?.addEventListener('change',updateHeight);document.addEventListener('click',e=>{const b=e.target.closest?.('[data-weight]');if(b)updateWeight(Number(b.dataset.weight))});
  document.querySelectorAll('.class-card').forEach(c=>c.addEventListener('click',()=>selectClass(c)));document.querySelectorAll('[data-class-prev]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();moveClass(-1)}));document.querySelectorAll('[data-class-next]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();moveClass(1)}));document.querySelectorAll('[data-plus]').forEach(b=>b.addEventListener('click',()=>changeAttr(b.dataset.plus,1)));document.querySelectorAll('[data-minus]').forEach(b=>b.addEventListener('click',()=>changeAttr(b.dataset.minus,-1)));
  $('uploadCharacterImage')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();$('characterImageFile')?.click()});$('characterImageFile')?.addEventListener('change',e=>handleImage(e.target.files?.[0]));$('removeCharacterImage')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(previewObjectUrl)URL.revokeObjectURL(previewObjectUrl);previewObjectUrl=null;$('portraitImg').src='';$('portraitImg').hidden=true;$('portraitEmpty').hidden=false;$('removeCharacterImage').hidden=true;$('appearancePresetSprite')?.removeAttribute('hidden')});
  track?.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'||e.target.closest('input,select,textarea,button,a,label')){touchX=touchY=null;return}touchX=e.clientX;touchY=e.clientY},{passive:true});track?.addEventListener('pointerup',e=>{if(e.pointerType!=='touch'||touchX===null||touchY===null)return;const dx=e.clientX-touchX,dy=e.clientY-touchY;touchX=touchY=null;if(Math.abs(dx)<55||Math.abs(dx)<Math.abs(dy)*1.2)return;goTo(index+(dx<0?1:-1))},{passive:true});document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT','BUTTON','A'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight')goTo(index+1);if(e.key==='ArrowLeft')goTo(index-1)});
  ensureUi();populateCountries();updateWeight(70);updateHeight();renderAttrs();selectClass(document.querySelector('.class-card.selected')||document.querySelector('.class-card'));updatePreview();goTo(0);setupProfile();loadProfile();
})();
