(() => {
'use strict';
const $=id=>document.getElementById(id), $$=s=>Array.from(document.querySelectorAll(s));
const slides=$$('.builder-slide'),steps=$$('.builder-step');
const labels=['IDENTIDADE','ORIGEM','APARÊNCIA','CLASSE','ATRIBUTOS','CONCEITO','REVISÃO FINAL'];
let currentStep=0,currentClass=1,objectUrl=null;
const attrs={forca:8,agilidade:8,vigor:8,percepcao:8,mente:8,vontade:8},BASE=8,MAX=15,POINTS=12;
const countries=[['BR','Brasil','🇧🇷'],['JP','Japão','🇯🇵'],['KR','Coreia do Sul','🇰🇷'],['CN','China','🇨🇳'],['US','Estados Unidos','🇺🇸'],['CA','Canadá','🇨🇦'],['MX','México','🇲🇽'],['AR','Argentina','🇦🇷'],['GB','Reino Unido','🇬🇧'],['FR','França','🇫🇷'],['DE','Alemanha','🇩🇪'],['IT','Itália','🇮🇹'],['ES','Espanha','🇪🇸'],['PT','Portugal','🇵🇹'],['IN','Índia','🇮🇳'],['AU','Austrália','🇦🇺'],['ZA','África do Sul','🇿🇦'],['EG','Egito','🇪🇬']];
const sprite={AU:[0,0],ZA:[0,2],EG:[0,4],DE:[1,0],IT:[1,2],ES:[1,4],PT:[2,0],IN:[2,2],CA:[2,4],MX:[3,0],AR:[3,2],GB:[3,4],FR:[4,0],BR:[4,2],JP:[4,4],KR:[5,0],CN:[5,2],US:[5,4]};
const setText=(id,v)=>{const e=$(id);if(e)e.textContent=v};
const val=(id,f='')=>{const e=$(id);return e&&String(e.value||'').trim()?String(e.value).trim():f};
const country=()=>countries.find(c=>c[0]===($('countryOrigin')?.value||'BR'))||countries[0];
const gender=()=>$('characterGender')?.value||'Masculino';
const setSprite=(id,code,g)=>{const e=$(id),b=sprite[code]||sprite.BR;if(e)e.style.backgroundPosition=`${(b[1]+(g==='Feminino'?1:0))*20}% ${b[0]*20}%`};
const formulas=()=>({hp:10+(attrs.vigor-8)*2,def:10+(attrs.agilidade-8)+Math.floor((attrs.percepcao-8)/2),stamina:6+Math.floor((attrs.vigor-8+attrs.agilidade-8)/2),attack:5+attrs.forca-8,focus:5+Math.floor((attrs.mente-8+attrs.vontade-8)/2)});
function updateStatus(){const f=formulas();[['previewHp',f.hp],['previewDef',f.def],['previewStaminaCylinder',f.stamina],['previewStaminaMax',13],['liveHpValue',f.hp],['liveDefValue',f.def],['liveStaminaValue',f.stamina],['liveAttackValue',f.attack],['liveFocusValue',f.focus],['finalHp',f.hp],['finalDef',f.def],['finalStamina',f.stamina]].forEach(x=>setText(x[0],x[1]));[['liveHpBar',f.hp,10,24],['liveDefBar',f.def,10,20],['liveStaminaBar',f.stamina,6,13],['liveAttackBar',f.attack,5,12],['liveFocusBar',f.focus,5,12]].forEach(([id,v,min,max])=>{const e=$(id);if(e)e.style.width=Math.max(5,Math.min(100,(v-min)/(max-min)*100))+'%'});const c=$('staminaCylinderCard');if(c)c.style.setProperty('--stamina-fill',Math.max(10,Math.min(100,f.stamina/13*100))+'%')}
function updateHeight(){const m=parseFloat(String($('appearanceHeight')?.value||'1,70 m').replace(',','.'))||1.7;document.documentElement.style.setProperty('--character-height-scale',Math.max(.88,Math.min(1.12,1+(m-1.7)*.55)).toFixed(3));setText('heightReadout',m.toFixed(2).replace('.',',')+' m')}
function populateCountries(){const s=$('countryOrigin');if(!s)return;s.replaceChildren();countries.forEach(c=>{const o=document.createElement('option');o.value=c[0];o.textContent=c[1];s.appendChild(o)});s.value='BR'}
function updateWeight(v){const n=Number(v)||70;if($('appearanceWeight'))$('appearanceWeight').value=n;setText('weightReadout',n+' kg');if($('weightBar'))$('weightBar').style.width=Math.max(0,Math.min(100,(n-45)/75*100))+'%';$$('[data-weight]').forEach(b=>b.classList.toggle('is-active',Number(b.dataset.weight)===n));renderReview()}
function updatePreview(){const [code,name,flag]=country(),g=gender();setText('originGenderLabel',g.toUpperCase());setText('originReferenceCountry',name);setText('countryFlag',flag);setText('countryName',name);setText('countryHint','Referência visual opcional e ajustável.');setText('finalCountryLine',flag+' '+name+' · '+g);setText('appearancePresetTitle','REFERÊNCIA VISUAL · '+name);setText('appearancePresetText','Modelo-base '+g.toLowerCase()+' de '+name+', usado apenas como referência.');['previewSprite','originCharacterSprite','appearancePresetSprite','finalSprite'].forEach(id=>setSprite(id,code,g));updateHeight();updateStatus();renderReview()}
function renderAttributes(){const used=Object.keys(attrs).reduce((s,k)=>s+attrs[k]-BASE,0),left=Math.max(0,POINTS-used);setText('pointsRemaining',left);Object.keys(attrs).forEach(k=>{const box=document.querySelector(`[data-attr="${k}"]`);if(!box)return;const n=box.querySelector('strong'),fill=box.querySelector('i em'),mi=box.querySelector(`[data-minus="${k}"]`),pl=box.querySelector(`[data-plus="${k}"]`);if(n)n.textContent=attrs[k];if(fill)fill.style.width=Math.round(attrs[k]/MAX*100)+'%';if(mi)mi.disabled=attrs[k]<=BASE;if(pl)pl.disabled=attrs[k]>=MAX||left<=0});updateStatus();renderReview()}
function changeAttr(k,d){if(!Object.hasOwn(attrs,k))return;const used=Object.keys(attrs).reduce((s,x)=>s+attrs[x]-BASE,0),left=POINTS-used;if(d>0&&(left<=0||attrs[k]>=MAX)||d<0&&attrs[k]<=BASE)return;attrs[k]+=d;renderAttributes()}
function selectClass(i){const cards=$$('.class-card');if(!cards.length)return;currentClass=((Number(i)||0)%cards.length+cards.length)%cards.length;cards.forEach((c,n)=>{c.classList.toggle('selected',n===currentClass);c.classList.toggle('side',n!==currentClass)});setText('classReadout',cards[currentClass].dataset.class||cards[currentClass].querySelector('b')?.textContent||'Sobrevivente');setText('classIndex',String(currentClass+1).padStart(2,'0')+' / '+String(cards.length).padStart(2,'0'));updatePreview()}
function renderReview(){const [code,name,flag]=country(),g=gender();setText('finalName',val('characterName','Sem nome'));setText('finalNickname',val('characterNickname','—'));const age=val('characterAge');setText('finalAge',age?age+' anos':'—');setText('finalClass',val('classReadout','Sobrevivente'));setText('finalCountryLine',flag+' '+name+' · '+g);setText('finalSkin','Pele: '+val('appearanceSkin','Claro'));setText('finalHair','Cabelo: '+val('appearanceHair','Preto'));setText('finalEyes','Olhos: '+val('appearanceEyes','Castanhos'));setText('finalAppearanceSummary',val('appearanceHeight','1,70 m')+' · '+val('appearanceWeight','70')+' kg');const extra=[val('appearanceScar'),val('appearanceFeatures'),val('appearanceDescription')].filter(Boolean);setText('finalAppearanceDetails',extra.length?extra.join(' · '):'Sem características adicionais.');setText('finalPersonality',val('characterPersonality','—'));setText('finalObjective',val('characterObjective','—'));setText('finalFear',val('characterFear','—'));setText('finalHistory',val('characterHistory','—'));const host=$('finalAttributes');if(host){host.replaceChildren();const names={forca:'Força',agilidade:'Agilidade',vigor:'Vigor',percepcao:'Percepção',mente:'Mente',vontade:'Vontade'};Object.keys(attrs).forEach(k=>{const e=document.createElement('span');e.innerHTML='<b>'+names[k]+'</b><strong>'+attrs[k]+'</strong>';host.appendChild(e)})}setSprite('finalSprite',code,g)}
function renderDots(){const h=$('carouselDots');if(!h)return;h.replaceChildren();slides.forEach((_,i)=>{const b=document.createElement('button');b.type='button';b.className=i===currentStep?'is-active':'';b.dataset.dotStep=i;b.setAttribute('aria-label','Ir para etapa '+(i+1));h.appendChild(b)})}
function goTo(t){if(!slides.length)return;currentStep=Math.max(0,Math.min(slides.length-1,Number(t)||0));slides.forEach((s,i)=>{s.classList.toggle('is-active',i===currentStep);s.setAttribute('aria-hidden',i===currentStep?'false':'true')});steps.forEach((s,i)=>{s.classList.toggle('is-active',i===currentStep);s.classList.toggle('is-complete',i<currentStep)});setText('stepCount',String(currentStep+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0'));setText('stepStatusLabel',labels[currentStep]);if($('progressBar'))$('progressBar').style.width=((currentStep+1)/slides.length*100)+'%';if($('prevStep'))$('prevStep').disabled=currentStep===0;if($('backStep'))$('backStep').disabled=currentStep===0;if($('nextStep'))$('nextStep').disabled=currentStep===slides.length-1;setText('nextAction',currentStep===slides.length-1?'FINALIZAR FICHA ✓':'CONTINUAR →');renderDots();const a=slides[currentStep];if(a){a.classList.remove('afterlife-step-enter');void a.offsetWidth;a.classList.add('afterlife-step-enter')}window.scrollTo({top:0,behavior:'smooth'})}
function injectBuilderCSS(){const s=document.createElement('style');s.textContent=`
.character-builder .character-preview{display:block!important;padding:12px!important;overflow:visible!important}.character-builder .character-preview>.preview-art,.character-builder .character-preview>.preview-info{display:none!important}
.character-builder .stamina-cylinder-card{display:grid!important;grid-template-columns:120px minmax(220px,1fr) minmax(330px,380px)!important;gap:30px!important;align-items:center!important;min-height:210px!important;margin:0!important;padding:22px 28px!important;box-sizing:border-box!important}.character-builder .combat-status{display:grid!important;grid-template-columns:repeat(2,minmax(145px,1fr))!important;gap:18px!important;min-width:0!important}.character-builder .combat-status-card{min-height:170px!important;padding:14px!important;box-sizing:border-box!important}.character-builder .combat-status-ring{width:104px!important;height:104px!important}
.character-builder .combat-status-card.hp .combat-status-ring{animation:afterlifeHpRing 2.8s linear infinite!important}.character-builder .combat-status-card.hp .combat-status-icon{animation:afterlifeHeartBeat 1.25s ease-in-out infinite!important;display:inline-block!important}.character-builder .combat-status-card.def .combat-status-ring{animation:afterlifeDefRing 3.8s linear infinite!important}.character-builder .stamina-cylinder{animation:afterlifeCylinderFloat 3.2s ease-in-out infinite!important;transform-origin:50% 90%!important}.character-builder .stamina-valve{animation:afterlifeValve 2.4s ease-in-out infinite!important}.character-builder .stamina-body::after{animation:afterlifeStaminaPulse 2.2s ease-in-out infinite!important}
@keyframes afterlifeHpRing{to{transform:rotate(360deg)}}@keyframes afterlifeDefRing{to{transform:rotate(-360deg)}}@keyframes afterlifeHeartBeat{0%,100%{transform:scale(1)}12%{transform:scale(1.16)}24%{transform:scale(.96)}36%{transform:scale(1.1)}50%{transform:scale(1)}}@keyframes afterlifeCylinderFloat{0%,100%{transform:translateY(0) rotate(0)}50%{transform:translateY(-5px) rotate(.7deg)}}@keyframes afterlifeValve{0%,100%{transform:rotate(0)}50%{transform:rotate(-3deg)}}@keyframes afterlifeStaminaPulse{0%,100%{filter:brightness(1)}50%{filter:brightness(1.18)}}
.character-builder .afterlife-global-profile-menu,.character-builder .afterlife-profile-dropdown,.character-builder .afterlife-account-menu{width:286px!important;z-index:5000!important}.character-builder .afterlife-global-profile-actions a,.character-builder .afterlife-global-profile-actions button,.character-builder .afterlife-profile-dropdown a,.character-builder .afterlife-profile-dropdown button{display:flex!important;align-items:center!important;width:100%!important;min-height:42px!important;padding:11px 12px!important;border:1px solid transparent!important;border-radius:9px!important;background:transparent!important;color:#dfe8e2!important;text-decoration:none!important;font:600 10px/1.2 Inter,sans-serif!important;text-align:left!important;cursor:pointer!important;box-sizing:border-box!important}.character-builder .afterlife-global-profile-actions a:hover,.character-builder .afterlife-global-profile-actions button:hover,.character-builder .afterlife-profile-dropdown a:hover,.character-builder .afterlife-profile-dropdown button:hover{background:rgba(57,245,138,.09)!important;border-color:rgba(57,245,138,.12)!important;color:#39f58a!important}
@media(max-width:980px){.character-builder .stamina-cylinder-card{grid-template-columns:105px minmax(0,1fr)!important}.character-builder .combat-status{grid-column:1/-1!important;grid-template-columns:1fr 1fr!important}}@media(max-width:620px){.character-builder .stamina-cylinder-card{grid-template-columns:86px 1fr!important;gap:16px!important;padding:16px!important}.character-builder .combat-status-card{min-height:135px!important}.character-builder .combat-status-ring{width:82px!important;height:82px!important}}
`;document.head.appendChild(s)}
function bind(){steps.forEach(s=>s.addEventListener('click',e=>{e.preventDefault();goTo(s.dataset.step)}));$('prevStep')?.addEventListener('click',e=>{e.preventDefault();goTo(currentStep-1)});$('nextStep')?.addEventListener('click',e=>{e.preventDefault();goTo(currentStep+1)});$('backStep')?.addEventListener('click',e=>{e.preventDefault();goTo(currentStep-1)});$('nextAction')?.addEventListener('click',e=>{e.preventDefault();if(currentStep<slides.length-1)goTo(currentStep+1)});$('cancelBuilder')?.addEventListener('click',()=>location.href='./index.html');$('carouselDots')?.addEventListener('click',e=>{const b=e.target.closest('[data-dot-step]');if(b)goTo(b.dataset.dotStep)});$('countryOrigin')?.addEventListener('change',updatePreview);$('characterGender')?.addEventListener('change',updatePreview);$('appearanceHeight')?.addEventListener('change',updatePreview);['characterName','characterNickname','characterAge','characterPersonality','characterObjective','characterFear','characterHistory','appearanceSkin','appearanceHair','appearanceEyes','appearanceEyeShape','appearanceStyle','appearanceScar','appearanceFeatures','appearanceDescription'].forEach(id=>$(id)?.addEventListener('input',updatePreview));$$('[data-weight]').forEach(b=>b.addEventListener('click',()=>updateWeight(b.dataset.weight)));$$('[data-plus]').forEach(b=>b.addEventListener('click',()=>changeAttr(b.dataset.plus,1)));$$('[data-minus]').forEach(b=>b.addEventListener('click',()=>changeAttr(b.dataset.minus,-1)));$$('.class-card').forEach((c,i)=>c.addEventListener('click',()=>selectClass(i)));$('[data-class-prev]')?.addEventListener('click',()=>selectClass(currentClass-1));$('[data-class-next]')?.addEventListener('click',()=>selectClass(currentClass+1));$('uploadCharacterImage')?.addEventListener('click',()=>$('characterImageFile')?.click());$('characterImageFile')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f||f.size>5*1024*1024)return;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(f);const img=$('portraitImg');if(img){img.src=objectUrl;img.hidden=false}$('portraitEmpty')?.setAttribute('hidden','true');$('removeCharacterImage')?.removeAttribute('hidden')});$('removeCharacterImage')?.addEventListener('click',()=>{if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=null;const i=$('characterImageFile'),img=$('portraitImg');if(i)i.value='';if(img){img.src='';img.hidden=true}$('portraitEmpty')?.removeAttribute('hidden');$('removeCharacterImage')?.setAttribute('hidden','true')});window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight')goTo(currentStep+1);if(e.key==='ArrowLeft')goTo(currentStep-1)})}
function normalizeBuilderNavigation(){const map=new Map([["inventário","./inventario.html"],["diário","./diario.html"],["configurações","./perfil.html"]]);document.querySelectorAll(".side-nav__item").forEach(link=>{const label=link.querySelector("span:last-child")?.textContent?.trim().toLowerCase();if(!label)return;if(map.has(label))link.setAttribute("href",map.get(label));if(["manual","comunidade","notícias"].includes(label))link.remove();});}\nfunction boot(){normalizeBuilderNavigation();injectBuilderCSS();populateCountries();bind();renderAttributes();selectClass(currentClass);goTo(0);window.dispatchEvent(new CustomEvent('afterlife:ficha-builder-ready',{detail:{steps:slides.length}}))}
function loadSharedProfile(){return new Promise((resolve,reject)=>{const src='./js/profile-global.js?v=20260920-2';if(window.__afterlifeGlobalProfileBooted)return resolve();const existing=document.querySelector(`script[src="${src}"]`);if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return;}const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
loadSharedProfile().then(boot).catch(error=>{console.error('[AFTERLIFE] Falha ao carregar perfil global:',error);boot()});
})();
