import { aeriom, ensureAfterlifeSession } from './aeriom-client-v2.js?v=20260919-map3';

(() => {
  'use strict';
  const qs = new URLSearchParams(location.search);
  const $ = id => document.getElementById(id);
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const num = (v,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f};
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const point=(lat,lng)=>Number.isFinite(Number(lat))&&Number.isFinite(Number(lng))?{lat:Number(lat),lng:Number(lng)}:null;
  const hav=(a,b)=>{const R=6371000,r=Math.PI/180,p1=num(a.lat)*r,p2=num(b.lat)*r,dp=(num(b.lat)-num(a.lat))*r,dl=(num(b.lng)-num(a.lng))*r,x=Math.sin(dp/2)**2+Math.sin(dl/2)**2*Math.cos(p1)*Math.cos(p2);return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(Math.max(0,1-x)))};
  const bearing=(a,b)=>{const r=Math.PI/180,p1=num(a.lat)*r,p2=num(b.lat)*r,dl=(num(b.lng)-num(a.lng))*r,y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return (Math.atan2(y,x)/r+360)%360};
  const cardinal=d=>['N','NE','E','SE','S','SW','W','NW'][Math.round((((num(d)%360)+360)%360)/45)%8];
  const fmtKm=m=>m<1000?Math.round(m)+' m':(m/1000).toFixed(m<10000?1:0)+' km';
  const poiIcon=t=>({Hospital:'🏥',Clínica:'🩺',Médico:'⚕️',Farmácia:'💊','Posto de combustível':'⛽',Banco:'🏦','Caixa eletrônico':'💳',Delegacia:'🚓',Bombeiros:'🚒',Restaurante:'🍽️',Café:'☕','Fast food':'🍔','Bar / Pub':'🍺',Mercado:'🛒',Conveniência:'🛍️',Padaria:'🥖',Açougue:'🥩',Ferragens:'🔩',Eletrônicos:'📱',Informática:'💻',Oficina:'🔧',Bicicletas:'🚲','Artigos esportivos':'⚽',Livraria:'📚','Pet shop':'🐾',Shopping:'🏬','Loja de departamentos':'🏬','Loja de roupas':'👕','Calçados':'👟',Escola:'🏫',Universidade:'🎓',Biblioteca:'📚','Igreja / culto':'✚','Centro comunitário':'🤝',Abrigo:'🏠',Parque:'🌳',Jardim:'🌿',Parquinho:'🛝','Centro esportivo':'🏋️',Estádio:'🏟️',Piscina:'🏊',Academia:'💪',Hotel:'🏨',Hostel:'🛏️',Museu:'🏛️',Atração:'📍',Mirante:'🔭',Camping:'🏕️',Floresta:'🌲',Praia:'🏖️',Montanha:'⛰️',Água:'💧',Monumento:'🗿',Memorial:'🕯️',Ruínas:'🏚️','Castelo / ruínas':'🏰','Sítio arqueológico':'🏺'})[t]||'📍';
  const poiType=tags=>{const a=String(tags.amenity||'').toLowerCase(),s=String(tags.shop||'').toLowerCase(),l=String(tags.leisure||'').toLowerCase(),t=String(tags.tourism||'').toLowerCase(),n=String(tags.natural||'').toLowerCase(),h=String(tags.historic||'').toLowerCase();const A={hospital:'Hospital',clinic:'Clínica',doctors:'Médico',dentist:'Dentista',pharmacy:'Farmácia',fuel:'Posto de combustível',bank:'Banco',atm:'Caixa eletrônico',police:'Delegacia',fire_station:'Bombeiros',restaurant:'Restaurante',cafe:'Café',fast_food:'Fast food',bar:'Bar / Pub',pub:'Bar / Pub',marketplace:'Mercado',school:'Escola',university:'Universidade',library:'Biblioteca',place_of_worship:'Igreja / culto',community_centre:'Centro comunitário',shelter:'Abrigo'},S={supermarket:'Mercado',convenience:'Conveniência',bakery:'Padaria',butcher:'Açougue',hardware:'Ferragens',electronics:'Eletrônicos',computer:'Informática',car_repair:'Oficina',bicycle:'Bicicletas',sports:'Artigos esportivos',books:'Livraria',pet:'Pet shop',mall:'Shopping',department_store:'Loja de departamentos',clothes:'Loja de roupas',shoes:'Calçados'},L={park:'Parque',garden:'Jardim',playground:'Parquinho',sports_centre:'Centro esportivo',stadium:'Estádio',swimming_pool:'Piscina',fitness_centre:'Academia'},T={hotel:'Hotel',hostel:'Hostel',museum:'Museu',attraction:'Atração',viewpoint:'Mirante',camp_site:'Camping'},N={forest:'Floresta',wood:'Floresta',beach:'Praia',peak:'Montanha',water:'Água'},H={monument:'Monumento',memorial:'Memorial',ruins:'Ruínas',castle:'Castelo / ruínas',archaeological_site:'Sítio arqueológico'};return A[a]||S[s]||L[l]||T[t]||N[n]||H[h]||(tags.craft?'Oficina':null)};

  const state={map:null,campaign:null,session:null,role:'player',members:[],locations:[],entities:[],infection:[],hordes:[],factions:[],npcs:[],vehicles:[],stations:[],travels:[],positions:new Map(),mapPosition:null,geoloc:null,selected:null,poiCache:new Map(),realtime:[],compass:{active:false,bound:false,heading:0},editorMode:null,drawing:null,layers:{locations:L.layerGroup(),members:L.layerGroup(),entities:L.layerGroup(),pois:L.layerGroup(),infection:L.layerGroup(),hordes:L.layerGroup(),factions:L.layerGroup(),npcs:L.layerGroup(),vehicles:L.layerGroup(),stations:L.layerGroup(),route:L.layerGroup(),vision:L.layerGroup(),device:L.layerGroup()}};
  const master=()=>state.role==='master';
  const center=()=>point(state.campaign?.latitude,state.campaign?.longitude)||{lat:-14.235,lng:-51.925};
  const current=()=>state.mapPosition||state.geoloc||center();
  function status(t,type='info'){if($('mapStatus'))$('mapStatus').textContent=t;if($('mapLiveText'))$('mapLiveText').textContent=type==='error'?'ERRO':type==='loading'?'SINCRONIZANDO':'SINCRONIZADO'}
  function toast(t,type='info'){status(t,type)}
  function icon(emoji,kind='default'){return L.divIcon({className:'al-mini-wrap',html:'<div class="al-mini al-mini--'+esc(kind)+'">'+esc(emoji)+'</div>',iconSize:[34,34],iconAnchor:[17,17]})}
  function entityEmoji(t){return ({house:'🏚️',commerce:'🏪',fuel:'⛽',hospital:'🏥',workshop:'🔧',factory:'🏭',police:'🚓',military:'🪖',school:'🏫',forest:'🌲',abandoned:'🏢',contaminated:'☢️',zombie:'🧟',horde:'🧟‍♂️',npc:'👤',survivors:'👥',faction:'🏴',shelter:'🏕️',vehicle:'🚙',barricade:'🚧',watchtower:'🗼',station:'⚒️',hazard:'☣️',custom:'✦'}[t]||'✦')}
  function marker(emoji,label,kind='default'){return L.divIcon({className:'al-marker-wrap',html:'<div class="al-marker al-marker--'+esc(kind)+'"><span>'+esc(emoji)+'</span><b>'+esc(String(label||'').slice(0,18))+'</b></div>',iconSize:[104,40],iconAnchor:[52,40]})}

  async function boot(){try{state.session=await ensureAfterlifeSession();if(!state.session?.user){location.href='../index.html';return}const id=qs.get('campaign')||qs.get('id')||sessionStorage.getItem('afterlife_current_campaign_id');if(!id)throw Error('Campanha não informada.');const c=await aeriom.from('campaigns').select('id,created_by,name,description,country,tone,scale,latitude,longitude').eq('id',id).maybeSingle();if(c.error)throw c.error;if(!c.data)throw Error('Campanha não encontrada.');state.campaign=c.data;const m=await aeriom.rpc('list_campaign_members',{p_campaign_id:id});if(m.error)throw m.error;state.members=Array.isArray(m.data)?m.data:[];const me=state.members.find(x=>String(x.user_id)===state.session.user.id);if(!me)throw Error('Você não participa desta campanha.');state.role=me.role==='master'||state.campaign.created_by===state.session.user.id?'master':'player';setup();initMap();await refresh();subscribe();status('Mundo pronto para a mesa.')}catch(e){console.error('[AFTERLIFE][MAP]',e);status(e.message||'Falha ao carregar mapa.','error');openModal('MAPA INDISPONÍVEL','<div class="map-empty-state">'+esc(e.message||'Erro desconhecido')+'</div>')}}
  function setup(){$('mapCampaignName').textContent=state.campaign.name||'Campanha';$('mapTitle').textContent=state.campaign.name||'Mapa da campanha';$('mapRoleBadge').textContent=master()?'MESTRE':'SOBREVIVENTE';$('mapRoleBadge').dataset.role=state.role;$('drawerTitle').textContent=master()?'Mapa + Controle do Mestre':'Mapa + Exploração';const b=$('mapBackCampaign');if(b)b.href='./campanha.html?campaign='+encodeURIComponent(state.campaign.id);$('mapOpenPanel').onclick=()=>drawer(true);$('mapClosePanel').onclick=()=>drawer(false);$('mapCenterCampaign').onclick=()=>go(center(),13);$('mapCenterMe').onclick=()=>go(current(),15);$('mapLocateDevice').onclick=locate;$('mapZoomIn').onclick=()=>state.map.zoomIn();$('mapZoomOut').onclick=()=>state.map.zoomOut();$('mapCompass').onclick=compass;document.querySelectorAll('[data-map-tab]').forEach(x=>x.onclick=()=>tab(x.dataset.mapTab));document.querySelectorAll('[data-open-tab]').forEach(x=>x.onclick=()=>tab(x.dataset.openTab));document.querySelectorAll('[data-open-systems]').forEach(x=>x.onclick=()=>tab('systems',x.dataset.openSystems));$('masterTab').hidden=!master();$('mapModalClose').onclick=closeModal;$('mapModalBackdrop').onclick=e=>{if(e.target===$('mapModalBackdrop'))closeModal()}}
  function initMap(){const c=center();state.map=L.map('worldMap',{center:[c.lat,c.lng],zoom:5,minZoom:2,maxZoom:19,worldCopyJump:false,zoomControl:false,preferCanvas:true,zoomAnimation:false,fadeAnimation:false,markerZoomAnimation:false,inertia:true,easeLinearity:.18,wheelDebounceTime:80,wheelPxPerZoomLevel:120});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{subdomains:['a','b','c'],maxZoom:19,noWrap:true,updateWhenZooming:false,updateWhenIdle:true,keepBuffer:1,crossOrigin:true,attribution:'&copy; OpenStreetMap contributors'}).addTo(state.map);Object.values(state.layers).forEach(x=>x.addTo(state.map));let moveTimer;state.map.on('moveend zoomend',()=>{readout();clearTimeout(moveTimer);moveTimer=setTimeout(()=>{if(state.map.getZoom()>=16)loadPois().catch(()=>{})},120)});state.map.on('click',mapClick);readout()}
  function readout(){if(!state.map)return;const c=state.map.getCenter(),z=state.map.getZoom();if($('mapCoordinates'))$('mapCoordinates').textContent=c.lat.toFixed(6)+'°, '+c.lng.toFixed(6)+'°';if($('mapZoomLabel'))$('mapZoomLabel').textContent='Z'+z;if($('mapScaleLabel'))$('mapScaleLabel').textContent=z<7?'MUNDO':z<12?'REGIÃO':z<15?'CIDADE':'RUA'}
  function drawer(open){$('mapDrawer').classList.toggle('is-open',open);$('mapDrawer').setAttribute('aria-hidden',String(!open));$('mapOpenPanel').setAttribute('aria-expanded',String(open))}
  function go(p,z){if(p)state.map.setView([p.lat,p.lng],clamp(z,2,19),{animate:true})}
  function tab(name,focus){document.querySelectorAll('[data-map-tab]').forEach(x=>x.classList.toggle('is-active',x.dataset.mapTab===name));document.querySelectorAll('[data-map-panel]').forEach(x=>x.classList.toggle('is-active',x.dataset.mapPanel===name));if(name==='explore'){renderLocationList();renderPoiList()}if(name==='systems')systems(focus);if(name==='master')masterPanel()}
  function openModal(title,html){$('mapModalEyebrow').textContent=master()?'CONTROLE DA MESA':'AFTERLIFE · MAPA';$('mapModalTitle').textContent=title;$('mapModalBody').innerHTML=html;$('mapModalBackdrop').hidden=false}
  function closeModal(){$('mapModalBackdrop').hidden=true}

  async function refresh(){status('Sincronizando mundo…','loading');await Promise.allSettled([members(),locations(),entities(),infection(),hordes(),factions(),npcs(),vehicles(),stations(),travels()]);if(!master())await playerPosition();renderAll();systems();masterPanel();status('Mundo pronto para a mesa.')}
  async function members(){const r=await aeriom.rpc('list_campaign_map_members',{p_campaign_id:state.campaign.id});if(r.error)return;state.members=Array.isArray(r.data)?r.data:[];state.positions.clear();state.members.forEach(m=>{const p=point(m.latitude,m.longitude);if(p)state.positions.set(String(m.user_id),p);if(String(m.user_id)===state.session.user.id&&p)state.mapPosition=p});renderMembers()}
  async function locations(){const r=await aeriom.from('campaign_world_locations').select('*').eq('campaign_id',state.campaign.id).order('updated_at',{ascending:false}).limit(450);state.locations=r.error?[]:(r.data||[])}
  async function entities(){try{const r=await aeriom.rpc('list_campaign_map_entities',{p_campaign_id:state.campaign.id});state.entities=r.error?[]:(Array.isArray(r.data)?r.data:[])}catch{state.entities=[]}}
  async function infection(){if(!master()){state.infection=[];return}let r=await aeriom.rpc('list_campaign_infection_zones',{p_campaign_id:state.campaign.id});if(r.error||!Array.isArray(r.data)||!r.data.length)r=await aeriom.rpc('ensure_campaign_infection_zones',{p_campaign_id:state.campaign.id,p_city_name:state.campaign.name||'Cidade'});state.infection=r.error?[]:(Array.isArray(r.data)?r.data:[])}
  async function hordes(){if(!master()){state.hordes=[];return}const r=await aeriom.from('campaign_hordes').select('*').eq('campaign_id',state.campaign.id).limit(180);state.hordes=r.error?[]:(r.data||[])}
  async function listTable(t){try{const r=await aeriom.from(t).select('*').eq('campaign_id',state.campaign.id);return r.error?[]:(r.data||[])}catch{return[]}}
  async function factions(){state.factions=await listTable('campaign_factions')}
  async function npcs(){state.npcs=await listTable('campaign_npcs')}
  async function vehicles(){state.vehicles=await listTable('campaign_vehicles')}
  async function stations(){state.stations=await listTable('crafting_stations')}
  async function travels(){const r=await aeriom.rpc('list_campaign_travels',{p_campaign_id:state.campaign.id,p_limit:12});state.travels=r.error?[]:(Array.isArray(r.data)?r.data:[])}
  async function playerPosition(){try{const r=await aeriom.rpc('ensure_campaign_map_position',{p_campaign_id:state.campaign.id});state.mapPosition=point(r.data?.latitude,r.data?.longitude)||center()}catch{state.mapPosition=center()}}

  function renderAll(){renderLocations();renderMembers();renderEntities();renderInfection();renderHordes();renderFactions();renderNpcs();renderStations();renderVehicles();renderVision();readout();stats()}
  function renderLocations(){state.layers.locations.clearLayers();const bounds=state.map?.getBounds()?.pad(.12);const source=master()?state.locations:state.locations.filter(l=>l.discovered!==false||(state.mapPosition&&hav(state.mapPosition,{lat:num(l.latitude),lng:num(l.longitude)})<760));const list=source.map(l=>({l,p:point(l.latitude,l.longitude)})).filter(x=>x.p&&(!bounds||bounds.contains([x.p.lat,x.p.lng]))).slice(0,state.map.getZoom()<=7?45:state.map.getZoom()<=11?70:110);list.forEach(({l,p})=>{const p=point(l.latitude,l.longitude);if(!p)return;const m=L.marker([p.lat,p.lng],{icon:icon(poiIcon(l.category||''),'location'),title:l.name}).addTo(state.layers.locations);m.on('click',e=>{L.DomEvent.stopPropagation(e);openLocation(l)})})}
  function renderMembers(){state.layers.members.clearLayers();const bounds=state.map?.getBounds()?.pad(.12);state.members.forEach(m=>{const p=point(m.latitude,m.longitude);if(!p||(!bounds||bounds.contains([p.lat,p.lng])))return;const me=String(m.user_id)===state.session.user.id,isM=m.role==='master';L.marker([p.lat,p.lng],{icon:icon(isM?'♛':me?'◎':'●',isM?'master':me?'me':'player'),zIndexOffset:800}).addTo(state.layers.members).bindTooltip((m.display_name||'Sobrevivente')+(me?' · VOCÊ':''))});const list=$('mapMemberList');if(list)list.innerHTML=state.members.map(m=>'<div class="map-member-row"><span class="map-member-avatar">'+esc((m.display_name||'S').charAt(0).toUpperCase())+'</span><span><strong>'+esc(m.display_name||'Sobrevivente')+'</strong><small>'+esc(m.role==='master'?'MESTRE':'SOBREVIVENTE')+'</small></span></div>').join('')}
  function renderEntities(){state.layers.entities.clearLayers();const bounds=state.map?.getBounds()?.pad(.12);state.entities.slice(0,state.map.getZoom()<=9?60:120).forEach(e=>{const g=e.geometry||{};let l;if(g.type==='polygon'&&Array.isArray(g.coordinates))l=L.polygon(g.coordinates,{color:'#d6b66c',fillColor:'#d6b66c',fillOpacity:.12});else if(g.type==='polyline'&&Array.isArray(g.coordinates))l=L.polyline(g.coordinates,{color:'#63f6a8',weight:5});else{const p=point(e.latitude,e.longitude);if(!p||(!bounds||bounds.contains([p.lat,p.lng])))return;l=L.marker([p.lat,p.lng],{icon:marker(entityEmoji(e.entity_type),e.name,e.entity_type),draggable:master()});if(master())l.on('dragend',ev=>moveEntity(e,ev.target.getLatLng()))}l.addTo(state.layers.entities).on('click',ev=>{L.DomEvent.stopPropagation(ev);openEntity(e)})})}
  function renderInfection(){state.layers.infection.clearLayers();if(!master())return;state.infection.forEach(z=>{const p=point(z.latitude,z.longitude);if(!p)return;const n=num(z.infection_percent),c=n>80?'#ff5b63':n>60?'#ff9f43':n>40?'#ffc95c':'#63f6a8';L.circle([p.lat,p.lng],{radius:Math.max(120,num(z.radius_m,650)),color:c,fillColor:c,fillOpacity:.1,weight:2}).addTo(state.layers.infection).bindTooltip('☣ '+esc(z.zone_name||'Zona')+' · '+Math.round(n)+'%')})}
  function renderHordes(){state.layers.hordes.clearLayers();if(!master())return;state.hordes.forEach(h=>{const p=point(h.latitude,h.longitude);if(!p)return;const m=L.marker([p.lat,p.lng],{icon:icon('☢','horde'),zIndexOffset:900}).addTo(state.layers.hordes);m.bindTooltip('🧟 '+esc(h.name||'Horda')+' · '+Math.round(num(h.size))+' zumbis · '+cardinal(num(h.direction_deg)))} )}
  function renderFactions(){state.layers.factions.clearLayers();state.factions.forEach(f=>{const t=f.territory||{},c=t.coordinates||t.polygon;if(Array.isArray(c)&&c.length>=3)L.polygon(c,{color:'#d6b66c',fillColor:'#d6b66c',fillOpacity:.07,dashArray:'8 7'}).addTo(state.layers.factions)})}
  function renderNpcs(){state.layers.npcs.clearLayers();state.npcs.forEach(n=>{const p=point(n.latitude,n.longitude);if(p)L.marker([p.lat,p.lng],{icon:icon('👤','npc')}).addTo(state.layers.npcs)})}
  function renderStations(){state.layers.stations.clearLayers();state.stations.forEach(s=>{const p=point(s.latitude,s.longitude);if(p)L.marker([p.lat,p.lng],{icon:icon('⚒️','station')}).addTo(state.layers.stations)})}
  function renderVehicles(){state.layers.vehicles.clearLayers();state.vehicles.forEach(v=>{const p=point(v.latitude,v.longitude);if(p)L.marker([p.lat,p.lng],{icon:icon('🚙','vehicle')}).addTo(state.layers.vehicles)})}
  function renderVision(){state.layers.vision.clearLayers();if(master()||!state.mapPosition)return;L.circle([state.mapPosition.lat,state.mapPosition.lng],{radius:380,color:'#63f6a8',fillColor:'#63f6a8',fillOpacity:.03,dashArray:'6 6'}).addTo(state.layers.vision)}
  function stats(){if($('statMembers'))$('statMembers').textContent=state.members.length;if($('statLocations'))$('statLocations').textContent=state.locations.length;if($('statThreats'))$('statThreats').textContent=state.hordes.length}

  async function openLocation(l){state.selected=l;drawer(true);tab('explore');let areas=[];try{const r=await aeriom.rpc('list_campaign_location_areas',{p_location_id:l.id});if(!r.error)areas=r.data||[]}catch{}openModal('FICHA DO LOCAL','<div class="map-location-sheet"><div class="map-location-kpis"><div><span>PERIGO</span><b>'+esc(l.danger||'unknown')+'</b></div><div><span>ESTADO</span><b>'+esc(l.state?.condition||'unknown')+'</b></div><div><span>SAQUE</span><b>'+num(l.state?.looted_percent)+'%</b></div></div><p class="map-location-address">'+esc(l.address||'Local registrado no mundo da campanha.')+'</p><div class="map-section-title">ÁREAS DO LOCAL</div><div class="map-area-list">'+(areas.length?areas.map(a=>'<article class="map-area-card"><strong>'+esc(a.name)+'</strong><small>'+esc(a.category||'Área')+' · '+esc(a.danger||'unknown')+'</small><p>'+esc(a.description||'Nenhuma descrição.')+'</p><div class="map-area-actions"><button type="button" data-area="'+esc(a.id)+'">OBSERVAR</button><button type="button" data-area="'+esc(a.id)+'">VASCULHAR</button></div></article>').join(''):'<div class="map-empty-state">Nenhuma área preparada.</div>')+'</div></div>')}
  function renderSelected(){return}
  function renderLocationList(){const list=$('locationList');if(!list)return;const p=current(),rows=state.locations.slice().sort((a,b)=>hav(p,{lat:num(a.latitude),lng:num(a.longitude)})-hav(p,{lat:num(b.latitude),lng:num(b.longitude)})).slice(0,20);list.innerHTML=rows.length?rows.map(l=>'<button class="map-list-row" type="button" data-loc="'+esc(l.id)+'"><span class="map-list-icon">'+esc(poiIcon(l.category||''))+'</span><span><strong>'+esc(l.name)+'</strong><small>'+esc(l.category||'Local')+' · '+fmtKm(hav(p,{lat:num(l.latitude),lng:num(l.longitude)}))+'</small></span><b>→</b></button>').join(''):'<div class="map-empty-state">Nenhum local salvo.</div>';list.querySelectorAll('[data-loc]').forEach(b=>b.onclick=()=>{const l=state.locations.find(x=>x.id===b.dataset.loc);if(l)openLocation(l)})}
  function renderPoiList(){const list=$('poiList');if(!list)return;const p=visiblePois();list.innerHTML=p.slice(0,20).map(x=>'<button class="map-list-row" type="button" data-poi="'+esc(x.key)+'"><span class="map-list-icon">'+esc(poiIcon(x.type))+'</span><span><strong>'+esc(x.name)+'</strong><small>'+esc(x.type)+' · '+fmtKm(hav(current(),x))+'</small></span><b>+</b></button>').join('')||'<div class="map-empty-state">Aproxime até a rua para carregar locais.</div>';list.querySelectorAll('[data-poi]').forEach(b=>b.onclick=()=>{const x=visiblePois().find(v=>v.key===b.dataset.poi);if(x)openPoi(x)})}
  function visiblePois(){let out=[];for(const x of state.poiCache.values())out.push(...x.items);const seen=new Set();return out.filter(x=>!seen.has(x.key)&&seen.add(x.key))}
  function poiKey(){const c=state.map.getCenter();return c.lat.toFixed(3)+':'+c.lng.toFixed(3)+':'+Math.floor(state.map.getZoom())}
  async function loadPois(){if(state.map.getZoom()<15){state.layers.pois.clearLayers();renderPoiList();return}const k=poiKey(),old=state.poiCache.get(k);if(old&&Date.now()-old.ts<300000){drawPois(old.items);return}const c=state.map.getCenter(),q='[out:json][timeout:7];(nwr(around:1000,'+c.lat+','+c.lng+')[name][amenity];nwr(around:1000,'+c.lat+','+c.lng+')[name][shop];nwr(around:1000,'+c.lat+','+c.lng+')[name][tourism];nwr(around:1000,'+c.lat+','+c.lng+')[name][craft];nwr(around:1000,'+c.lat+','+c.lng+')[name][historic];);out center tags;';let data=null;for(const ep of ['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter']){try{const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),7000),r=await fetch(ep,{method:'POST',body:q,signal:ac.signal,headers:{'Content-Type':'text/plain;charset=UTF-8'}});clearTimeout(tm);if(r.ok){data=await r.json();break}}catch{}}if(!data)return;const items=(data.elements||[]).map(e=>{const tags=e.tags||{},type=poiType(tags);return{key:'osm:'+e.type+':'+e.id,name:tags.name||tags.brand||'Local sem nome',type,lat:num(e.lat??e.center?.lat),lng:num(e.lon??e.center?.lon),tags}}).filter(x=>x.lat&&x.lng&&x.type).slice(0,90);state.poiCache.set(k,{ts:Date.now(),items});drawPois(items)}
  function drawPois(items){state.layers.pois.clearLayers();items.forEach(p=>L.marker([p.lat,p.lng],{icon:icon(poiIcon(p.type),'poi'),zIndexOffset:100}).addTo(state.layers.pois).on('click',e=>{L.DomEvent.stopPropagation(e);openPoi(p)}));renderPoiList()}
  function openPoi(p){go(p,16);openModal('PONTO REAL','<div class="entity-sheet"><div class="entity-badge">'+esc(poiIcon(p.type))+'</div><h3>'+esc(p.name)+'</h3><span>'+esc(p.type)+'</span><p>Fonte: OpenStreetMap</p><div class="map-location-kpis"><div><span>DISTÂNCIA</span><b>'+fmtKm(hav(current(),p))+'</b></div><div><span>TIPO</span><b>'+esc(p.type)+'</b></div></div></div>')}

  function systems(focus){const h=$('systemsCards');if(!h)return;const w=focus||'world';h.innerHTML='<div class="systems-switch">'+['world','radar','travel','survival'].map(k=>'<button type="button" class="'+(k===w?'is-active':'')+'" data-sys="'+k+'">'+k.toUpperCase()+'</button>').join('')+'</div>'+(w==='radar'?radar():w==='survival'?'<div class="system-intro"><span>VISÃO</span><strong>'+fmtKm(380)+'</strong><small>O sobrevivente vê apenas a região próxima.</small></div>':w==='travel'?'<div class="system-intro"><span>VIAGENS</span><strong>'+state.travels.length+' registrada(s)</strong></div>':'<div class="system-intro"><span>MUNDO</span><strong>Facções, NPCs e infraestrutura.</strong></div>');h.querySelectorAll('[data-sys]').forEach(b=>b.onclick=()=>systems(b.dataset.sys))}
  function radar(){if(!master())return '<div class="system-intro"><span>RADAR</span><strong>Controlado pelo Mestre.</strong></div>';return '<div class="system-intro"><span>☢ RADAR DE HORDAS</span><strong>'+state.hordes.length+' onda(s)</strong><small>Distância e direção calculadas a partir da posição atual.</small></div><div class="radar-list">'+state.hordes.map(h=>{const p=point(h.latitude,h.longitude)||center();return '<div class="radar-row"><span class="radar-signal"></span><span><strong>'+esc(h.name||'Horda')+'</strong><small>'+fmtKm(hav(current(),p))+' · '+cardinal(bearing(current(),p))+'</small></span><b>'+Math.round(num(h.size))+'</b></div>'}).join('')+'</div>'}
  function masterPanel(){const h=$('masterPanel');if(!h)return;if(!master()){h.innerHTML='<div class="system-intro"><span>MAPA</span><strong>Visão de sobrevivente.</strong></div>';return}h.innerHTML='<div class="system-intro"><span>MESTRE</span><strong>Controle do mundo</strong><small>Infecção: '+state.infection.length+' · Hordas: '+state.hordes.length+' · Elementos: '+state.entities.length+'</small></div>'}

  function mapClick(e){if(state.editorMode==='entity'){state.editorMode=null;return openEntityEditor(null,e.latlng)}if(state.editorMode==='horde'){state.editorMode=null;return openHordeEditor(null,e.latlng)}if(state.editorMode==='travel'){state.editorMode=null;go(e.latlng,15)}if($('mapCoordinates'))$('mapCoordinates').textContent=e.latlng.lat.toFixed(6)+'°, '+e.latlng.lng.toFixed(6)+'°'}
  function openEntityEditor(entity,p){openModal('NOVO ELEMENTO','<form id="mapEntityForm" class="map-form"><label>TIPO<select name="type"><option value="commerce">🏪 Comércio</option><option value="hospital">🏥 Hospital</option><option value="fuel">⛽ Posto</option><option value="shelter">🏕️ Abrigo</option><option value="barricade">🚧 Barricada</option><option value="custom">✦ Outro</option></select></label><label>NOME<input name="name" required value="'+esc(entity?.name||'Elemento')+'"></label><label>DESCRIÇÃO<textarea name="description"></textarea></label><input type="hidden" name="lat" value="'+(p?.lat??entity?.latitude??'')+'"><input type="hidden" name="lng" value="'+(p?.lng??entity?.longitude??'')+'"><footer><button type="button" data-close>Cancelar</button><button type="submit">SALVAR</button></footer></form>');const f=$('mapEntityForm');f.onsubmit=async e=>{e.preventDefault();const r=await aeriom.rpc('create_campaign_map_entity',{p_campaign_id:state.campaign.id,p_entity_type:f.type.value,p_name:f.name.value.trim(),p_description:f.description.value.trim()||null,p_latitude:num(f.lat.value),p_longitude:num(f.lng.value),p_geometry:null,p_state:{},p_metadata:{}});if(r.error)return toast(r.error.message,'error');await entities();renderEntities();closeModal();toast('Elemento salvo.')}}
  function openHordeEditor(h,p){openModal('NOVA HORDA','<form id="hordeForm" class="map-form"><input type="hidden" name="lat" value="'+(p?.lat??'')+'"><input type="hidden" name="lng" value="'+(p?.lng??'')+'"><label>NOME<input name="name" value="Horda detectada"></label><label>ZUMBIS<input name="size" type="number" min="1" value="30"></label><footer><button type="button" data-close>Cancelar</button><button type="submit">CRIAR HORDA</button></footer></form>');const f=$('hordeForm');f.onsubmit=async e=>{e.preventDefault();const r=await aeriom.rpc('create_campaign_horde',{p_campaign_id:state.campaign.id,p_latitude:num(f.lat.value),p_longitude:num(f.lng.value),p_size:num(f.size.value),p_speed_kmh:10,p_direction_deg:0,p_source_zone_id:null});if(r.error)return toast(r.error.message,'error');await hordes();renderHordes();closeModal();toast('Horda criada.')}}
  function locate(){if(!navigator.geolocation)return toast('GPS indisponível.','error');navigator.geolocation.getCurrentPosition(async p=>{state.geoloc={lat:p.coords.latitude,lng:p.coords.longitude};state.layers.device.clearLayers();L.marker([state.geoloc.lat,state.geoloc.lng],{icon:icon('◎','gps')}).addTo(state.layers.device);go(state.geoloc,16);if(!master()){try{await aeriom.from('campaign_map_positions').upsert({campaign_id:state.campaign.id,user_id:state.session.user.id,latitude:state.geoloc.lat,longitude:state.geoloc.lng,updated_at:new Date().toISOString()},{onConflict:'campaign_id,user_id'});state.mapPosition=state.geoloc;renderVision()}catch{}}},()=>toast('Não foi possível obter o GPS.','error'),{enableHighAccuracy:true,timeout:9000,maximumAge:15000})}
  async function compass(){try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){if(await DeviceOrientationEvent.requestPermission()!=='granted')return toast('Permissão da bússola recusada.','error')}if(!state.compass.bound){state.compass.bound=true;addEventListener('deviceorientationabsolute',orient,true);addEventListener('deviceorientation',orient,true)}state.compass.active=!state.compass.active;$('mapCompass').classList.toggle('is-active',state.compass.active)}catch{toast('Bússola indisponível.','error')}}
  function orient(e){if(!state.compass.active)return;const h=Number.isFinite(e.webkitCompassHeading)?e.webkitCompassHeading:Number.isFinite(e.alpha)?360-e.alpha:null;if(h!=null){state.compass.heading=(h+360)%360;$('mapCompass').textContent=cardinal(state.compass.heading)}}
  function moveEntity(e,p){return aeriom.rpc('update_campaign_map_entity',{p_entity_id:e.id,p_name:e.name,p_description:e.description||null,p_latitude:p.lat,p_longitude:p.lng,p_geometry:e.geometry||null,p_state:e.state||{},p_metadata:e.metadata||{}}).then(()=>entities().then(renderEntities))}
  function subscribe(){const cid=state.campaign.id;['campaign_map_positions','campaign_world_locations','campaign_map_entities','campaign_hordes','campaign_infection_zones','campaign_factions','campaign_npcs','crafting_stations','campaign_vehicles','campaign_travels'].forEach(t=>{const c=aeriom.channel('afterlife-map-'+t+'-'+cid).on('postgres_changes',{event:'*',schema:'public',table:t,filter:'campaign_id=eq.'+cid},()=>{clearTimeout(c.__timer);c.__timer=setTimeout(()=>refresh().catch(()=>{}),250)}).subscribe();state.realtime.push(c)})}

  window.__afterlifeCampaignMap={refresh};
  boot();
})();
