import { aeriom, ensureAfterlifeSession } from './aeriom-client-v2.js?v=20260919-map1';

(() => {
  'use strict';

  const qs = new URLSearchParams(location.search);
  if (qs.get('select') === '1') {
    location.replace('./campanha-local.html?return=create');
    return;
  }

  const $ = (id) => document.getElementById(id);
  const POI_ENDPOINTS = [
    'https://overpass-api.de/api/interpreter',
    'https://overpass.kumi.systems/api/interpreter'
  ];
  const POI_TTL = 5 * 60 * 1000;
  const PLAYER_VISION_M = 380;
  const MAX_POIS = 110;

  const state = {
    map:null,campaign:null,session:null,role:'player',members:[],positions:new Map(),
    locations:[],entities:[],factions:[],npcs:[],vehicles:[],stations:[],infection:[],hordes:[],travels:[],travelEvents:[],
    selectedLocation:null,selectedPoi:null,selectedEntity:null,geoloc:null,mapPosition:null,
    editorMode:null,drawing:null,travelDraft:null,activeSystemsTab:'world',toastTimer:null,
    compass:{active:false,heading:0,bound:false},realtime:[],
    poiCache:new Map(),layers:{locations:L.layerGroup(),members:L.layerGroup(),entities:L.layerGroup(),
    pois:L.layerGroup(),infection:L.layerGroup(),hordes:L.layerGroup(),factions:L.layerGroup(),
    npcs:L.layerGroup(),stations:L.layerGroup(),vehicles:L.layerGroup(),travelEvents:L.layerGroup(),route:L.layerGroup(),vision:L.layerGroup(),device:L.layerGroup()}
  };

  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const num=(v,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f};
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
  const fmtKm=m=>{const n=Math.max(0,num(m));if(n<1000)return Math.round(n)+' m';if(n<100000)return (n/1000).toFixed(1).replace('.0','')+' km';return Math.round(n/1000)+' km'};
  const hav=(a,b)=>{const R=6371000,r=Math.PI/180,p1=num(a.lat)*r,p2=num(b.lat)*r,dp=(num(b.lat)-num(a.lat))*r,dl=(num(b.lng)-num(a.lng))*r,x=Math.sin(dp/2)**2+Math.sin(dl/2)**2*Math.cos(p1)*Math.cos(p2);return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(Math.max(0,1-x)))};
  const bearing=(a,b)=>{const r=Math.PI/180,p1=num(a.lat)*r,p2=num(b.lat)*r,dl=(num(b.lng)-num(a.lng))*r,y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return (Math.atan2(y,x)/r+360)%360};
  const cardinal=d=>['N','NE','E','SE','S','SW','W','NW'][Math.round((((num(d)%360)+360)%360)/45)%8];
  const point=(lat,lng)=>Number.isFinite(Number(lat))&&Number.isFinite(Number(lng))?{lat:Number(lat),lng:Number(lng)}:null;
  const campaignCenter=()=>point(state.campaign?.latitude,state.campaign?.longitude)||{lat:-14.235,lng:-51.925};
  const currentPoint=()=>state.mapPosition||state.geoloc||campaignCenter();
  const initials=n=>String(n||'S').trim().charAt(0).toUpperCase()||'S';
  const master=()=>state.role==='master';

  function setStatus(text,type='info'){const el=$('mapStatus');if(el){el.textContent=text;el.dataset.type=type}const live=$('mapLiveText');if(live)live.textContent=type==='error'?'ERRO DE SINCRONIA':type==='loading'?'SINCRONIZANDO':'SINCRONIZADO'}
  function toast(text,type='info'){setStatus(text,type);clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>setStatus('Mundo pronto para a mesa.','info'),4200)}
  function simpleIcon(emoji,kind='default'){return L.divIcon({className:'al-mini-wrap',html:'<div class="al-mini al-mini--'+esc(kind)+'">'+esc(emoji||'•')+'</div>',iconSize:[34,34],iconAnchor:[17,17],popupAnchor:[0,-18]})}
  function markerIcon(emoji,label,kind='default'){const html='<div class="al-marker al-marker--'+esc(kind)+'"><span>'+esc(emoji||'✦')+'</span><b>'+esc(String(label||'').slice(0,18))+'</b></div>';return L.divIcon({className:'al-marker-wrap',html,iconSize:[104,40],iconAnchor:[52,40],popupAnchor:[0,-34]})}
  const entityEmoji=t=>({house:'🏚️',commerce:'🏪',fuel:'⛽',hospital:'🏥',workshop:'🔧',factory:'🏭',police:'🚓',military:'🪖',school:'🏫',forest:'🌲',abandoned:'🏢',contaminated:'☢️',zombie:'🧟',horde:'🧟‍♂️',npc:'👤',survivors:'👥',faction:'🏴',shelter:'🏕️',vehicle:'🚙',barricade:'🚧',watchtower:'🗼',station:'⚒️',hazard:'☣️',custom:'✦'}[t]||'✦');

  function poiType(tags={}){
    const amen={hospital:'Hospital',clinic:'Clínica',doctors:'Médico',dentist:'Dentista',pharmacy:'Farmácia',fuel:'Posto de combustível',bank:'Banco',atm:'Caixa eletrônico',police:'Delegacia',fire_station:'Bombeiros',restaurant:'Restaurante',cafe:'Café',fast_food:'Fast food',bar:'Bar / Pub',pub:'Bar / Pub',marketplace:'Mercado',school:'Escola',university:'Universidade',library:'Biblioteca',library:'Biblioteca',place_of_worship:'Igreja / culto',community_centre:'Centro comunitário',shelter:'Abrigo'};
    const shop={supermarket:'Mercado',convenience:'Conveniência',bakery:'Padaria',butcher:'Açougue',hardware:'Ferragens',electronics:'Eletrônicos',computer:'Informática',car_repair:'Oficina',bicycle:'Bicicletas',sports:'Artigos esportivos',books:'Livraria',pet:'Pet shop',mall:'Shopping',department_store:'Loja de departamentos',clothes:'Loja de roupas',shoes:'Calçados'};
    const leisure={park:'Parque',garden:'Jardim',playground:'Parquinho',sports_centre:'Centro esportivo',stadium:'Estádio',swimming_pool:'Piscina',fitness_centre:'Academia'};
    const tourism={hotel:'Hotel',hostel:'Hostel',museum:'Museu',attraction:'Atração',viewpoint:'Mirante',camp_site:'Camping'};
    const natural={forest:'Floresta',wood:'Floresta',beach:'Praia',peak:'Montanha',water:'Água'};
    const historic={monument:'Monumento',memorial:'Memorial',ruins:'Ruínas',castle:'Castelo / ruínas',archaeological_site:'Sítio arqueológico'};
    const a=String(tags.amenity||'').toLowerCase(),s=String(tags.shop||'').toLowerCase(),l=String(tags.leisure||'').toLowerCase(),t=String(tags.tourism||'').toLowerCase(),n=String(tags.natural||'').toLowerCase(),h=String(tags.historic||'').toLowerCase();
    return amen[a]||shop[s]||leisure[l]||tourism[t]||natural[n]||historic[h]||(tags.craft?'Oficina':'Ponto de interesse');
  }
  const poiEmoji=type=>({Hospital:'🏥',Clínica:'🩺',Médico:'⚕️',Farmácia:'💊','Posto de combustível':'⛽',Banco:'🏦','Caixa eletrônico':'💳',Delegacia:'🚓',Bombeiros:'🚒',Restaurante:'🍽️',Café:'☕','Fast food':'🍔','Bar / Pub':'🍺',Mercado:'🛒',Conveniência:'🛍️',Padaria:'🥖',Açougue:'🥩',Ferragens:'🔩',Eletrônicos:'📱',Informática:'💻',Oficina:'🔧',Bicicletas:'🚲','Artigos esportivos':'⚽',Livraria:'📚','Pet shop':'🐾',Shopping:'🏬','Loja de departamentos':'🏬','Loja de roupas':'👕','Calçados':'👟',Escola:'🏫',Universidade:'🎓',Biblioteca:'📚','Igreja / culto':'✚','Centro comunitário':'🤝',Abrigo:'🏠',Parque:'🌳',Jardim:'🌿',Parquinho:'🛝','Centro esportivo':'🏋️',Estádio:'🏟️',Piscina:'🏊',Academia:'💪',Hotel:'🏨',Hostel:'🛏️',Museu:'🏛️',Atração:'📍',Mirante:'🔭',Camping:'🏕️',Floresta:'🌲',Praia:'🏖️',Montanha:'⛰️',Água:'💧',Monumento:'🗿',Memorial:'🕯️',Ruínas:'🏚️','Castelo / ruínas':'🏰','Sítio arqueológico':'🏺'})[type]||'📍';

  async function boot(){
    try{
      state.session=await ensureAfterlifeSession();
      if(!state.session?.user){const target=new URL('../index.html',location.href);target.searchParams.set('afterlife','1');target.searchParams.set('returnTo',location.pathname+location.search);location.replace(target.href);return}
      const id=qs.get('campaign')||qs.get('id')||sessionStorage.getItem('afterlife_current_campaign_id');if(!id)throw new Error('Campanha não informada.');
      const campaign=await aeriom.from('campaigns').select('id,created_by,name,description,country,tone,scale,latitude,longitude').eq('id',id).maybeSingle();
      if(campaign.error)throw campaign.error;if(!campaign.data)throw new Error('Campanha não encontrada.');state.campaign=campaign.data;
      const members=await aeriom.rpc('list_campaign_members',{p_campaign_id:id});if(members.error)throw members.error;
      state.members=(Array.isArray(members.data)?members.data:members.data?[members.data]:[]).map(x=>({user_id:String(x.user_id||''),role:String(x.role||'player'),display_name:x.display_name||'Sobrevivente',avatar_path:x.avatar_path||null,latitude:x.latitude,longitude:x.longitude})).filter(x=>x.user_id);
      const me=state.members.find(x=>x.user_id===state.session.user.id);if(!me)throw new Error('Você não participa desta campanha.');
      state.role=me.role==='master'||state.campaign.created_by===state.session.user.id?'master':'player';
      setupUi();initMap();await loadAll();subscribeRealtime();emitReady();
    }catch(error){console.error('[AFTERLIFE][MAP][REBUILD]',error);setStatus(error?.message||'Falha ao iniciar o mapa.','error');openModal('MAPA INDISPONÍVEL','<div class="map-empty-state">'+esc(error?.message||'Não foi possível carregar o mundo.')+'</div>')}
  }

  function setupUi(){
    $('mapCampaignName').textContent=state.campaign.name||'Campanha';$('mapTitle').textContent=state.campaign.name||'Mapa da campanha';$('mapRoleBadge').textContent=master()?'MESTRE':'SOBREVIVENTE';$('mapRoleBadge').dataset.role=state.role;$('drawerTitle').textContent=master()?'Mapa + Controle do Mestre':'Mapa + Exploração';
    const back=$('mapBackCampaign');if(back)back.href='./campanha.html?campaign='+encodeURIComponent(state.campaign.id);
    document.querySelectorAll('[data-map-tab]').forEach(b=>b.addEventListener('click',()=>openTab(b.dataset.mapTab)));
    $('mapOpenPanel').onclick=()=>toggleDrawer(true);$('mapClosePanel').onclick=()=>toggleDrawer(false);$('mapCenterCampaign').onclick=()=>centerOn(campaignCenter(),Math.max(state.map.getZoom(),13));$('mapCenterMe').onclick=()=>centerOn(currentPoint(),Math.max(state.map.getZoom(),15));$('mapLocateDevice').onclick=locateDevice;
    $('mapZoomIn').onclick=()=>state.map.zoomIn();$('mapZoomOut').onclick=()=>state.map.zoomOut();$('mapCompass').onclick=toggleCompass;$('mapModalClose').onclick=closeModal;
    $('mapModalBackdrop').addEventListener('click',e=>{if(e.target===$('mapModalBackdrop'))closeModal()});
    document.querySelectorAll('[data-open-tab]').forEach(b=>b.addEventListener('click',()=>openTab(b.dataset.openTab)));document.querySelectorAll('[data-open-systems]').forEach(b=>b.addEventListener('click',()=>openTab('systems',b.dataset.openSystems)));
    $('masterTab').toggleAttribute('hidden',!master());
    $('profileChip')?.addEventListener('click',()=>{$('profileMenu').classList.toggle('is-open')});
    $('profileLogout')?.addEventListener('click',async()=>{await aeriom.auth.signOut();location.href='../index.html'});
  }

  function initMap(){
    const c=campaignCenter();state.map=L.map('worldMap',{center:[c.lat,c.lng],zoom:5,minZoom:2,maxZoom:19,worldCopyJump:true,zoomControl:false,preferCanvas:true});
    L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{subdomains:'abcd',maxZoom:20,attribution:'&copy; OpenStreetMap &copy; CARTO'}).addTo(state.map);
    Object.values(state.layers).forEach(x=>x.addTo(state.map));state.map.on('moveend zoomend',()=>{updateReadout();renderPoisIfNeeded()});state.map.on('click',handleMapClick);updateReadout();
  }

  function emitReady(){window.__afterlifeCampaignMap={map:state.map,campaign:state.campaign,role:state.role,user:state.session.user,refresh:loadAll,refreshMembers:loadMembers,getSelfPosition:currentPoint};window.dispatchEvent(new CustomEvent('afterlife:map-ready',{detail:window.__afterlifeCampaignMap}))}
  async function loadAll(){setStatus('Sincronizando mundo…','loading');await Promise.allSettled([loadMembers(),loadLocations(),loadEntities(),loadInfection(),loadHordes(),loadFactions(),loadNpcs(),loadVehicles(),loadStations(),loadTravels()]);if(!master())await ensurePlayerPosition();renderAll();buildSystemsPanel();renderMasterPanel();setStatus('Mundo pronto para a mesa.','info')}
  async function loadMembers(){const r=await aeriom.rpc('list_campaign_map_members',{p_campaign_id:state.campaign.id});if(r.error){console.warn('[MAP][members]',r.error);return}state.members=Array.isArray(r.data)?r.data:[];state.positions.clear();state.members.forEach(m=>{const p=point(m.latitude,m.longitude);if(p)state.positions.set(String(m.user_id),p);if(String(m.user_id)===state.session.user.id&&p)state.mapPosition=p});renderMembers();updateStats()}
  async function loadLocations(){const r=await aeriom.from('campaign_world_locations').select('*').eq('campaign_id',state.campaign.id).order('updated_at',{ascending:false}).limit(450);state.locations=r.error?[]:(r.data||[]);window.__afterlifeWorldLocationsCache=state.locations;updateStats()}
  async function loadEntities(){try{const r=await aeriom.rpc('list_campaign_map_entities',{p_campaign_id:state.campaign.id});if(r.error)throw r.error;state.entities=Array.isArray(r.data)?r.data:[]}catch(e){console.warn('[MAP][entities]',e);state.entities=[]}}
  async function loadInfection(){if(!master()){state.infection=[];return}let r=await aeriom.rpc('list_campaign_infection_zones',{p_campaign_id:state.campaign.id});if(r.error||!Array.isArray(r.data)||!r.data.length)r=await aeriom.rpc('ensure_campaign_infection_zones',{p_campaign_id:state.campaign.id,p_city_name:state.campaign.name||'Cidade da campanha'});state.infection=r.error?[]:(Array.isArray(r.data)?r.data:[])}
  async function loadHordes(){if(!master()){state.hordes=[];return}const r=await aeriom.from('campaign_hordes').select('*').eq('campaign_id',state.campaign.id).order('updated_at',{ascending:false}).limit(150);state.hordes=r.error?[]:(r.data||[]);updateStats()}
  async function tableList(table){try{const r=await aeriom.from(table).select('*').eq('campaign_id',state.campaign.id);return r.error?[]:(r.data||[])}catch{return[]}}
  async function loadFactions(){state.factions=await tableList('campaign_factions')}
  async function loadNpcs(){state.npcs=await tableList('campaign_npcs')}
  async function loadVehicles(){state.vehicles=await tableList('campaign_vehicles')}
  async function loadStations(){state.stations=await tableList('crafting_stations')}
  async function loadTravels(){const r=await aeriom.rpc('list_campaign_travels',{p_campaign_id:state.campaign.id,p_limit:12});state.travels=r.error?[]:(Array.isArray(r.data)?r.data:[]);state.travelEvents=[];const active=state.travels.find(x=>['planned','in_transit'].includes(x.status));if(active){const ev=await aeriom.rpc('list_campaign_travel_events',{p_travel_id:active.id});state.travelEvents=ev.error?[]:(Array.isArray(ev.data)?ev.data:[])}}

  async function ensurePlayerPosition(){try{const r=await aeriom.rpc('ensure_campaign_map_position',{p_campaign_id:state.campaign.id});if(r.error)throw r.error;state.mapPosition=point(r.data?.latitude,r.data?.longitude)||campaignCenter()}catch{state.mapPosition=campaignCenter()}}
  function renderAll(){renderLocations();renderMembers();renderEntities();renderInfection();renderHordes();renderFactions();renderNpcs();renderStations();renderVehicles();renderTravelRoute();renderVision();renderSelectedLocation();updateReadout();updateStats()}

  function renderLocations(){
    state.layers.locations.clearLayers();
    const shown=master()?state.locations:state.locations.filter(l=>l.discovered!==false||(state.mapPosition&&hav(state.mapPosition,{lat:num(l.latitude),lng:num(l.longitude)})<=PLAYER_VISION_M*2));
    shown.forEach(l=>{const p=point(l.latitude,l.longitude);if(!p)return;const m=L.marker([p.lat,p.lng],{icon:simpleIcon(poiEmoji(l.category||''),'location'),title:l.name}).addTo(state.layers.locations);m.on('click',e=>{L.DomEvent.stopPropagation(e);openLocation(l)});m.bindTooltip((l.name||'Local')+' · '+(l.category||'Ponto de interesse'),{direction:'top',offset:[0,-15]})});
  }
  function renderMembers(){
    state.layers.members.clearLayers();state.members.forEach(m=>{const p=point(m.latitude,m.longitude);if(!p)return;const me=String(m.user_id)===state.session.user.id,isM=m.role==='master';const mk=L.marker([p.lat,p.lng],{icon:simpleIcon(isM?'♛':me?'◎':'●',isM?'master':me?'me':'player'),zIndexOffset:isM?800:700}).addTo(state.layers.members);mk.bindTooltip((m.display_name||'Sobrevivente')+(me?' · VOCÊ':''),{direction:'top',offset:[0,-15]})});
    const list=$('mapMemberList');if(!list)return;list.innerHTML=state.members.map(m=>'<button type="button" class="map-member-row" data-member="'+esc(m.user_id)+'"><span class="map-member-avatar">'+esc(initials(m.display_name))+'</span><span><strong>'+esc(m.display_name||'Sobrevivente')+'</strong><small>'+esc(m.role==='master'?'MESTRE':'SOBREVIVENTE')+(m.latitude!=null?' · POSIÇÃO ATIVA':' · SEM POSIÇÃO')+'</small></span><b>'+((m.latitude!=null&&m.longitude!=null)?'●':'—')+'</b></button>').join('');
    list.querySelectorAll('[data-member]').forEach(b=>b.onclick=()=>{const m=state.members.find(x=>String(x.user_id)===b.dataset.member),p=point(m?.latitude,m?.longitude);if(p)centerOn(p,Math.max(state.map.getZoom(),15))});
  }
  function renderEntities(){
    state.layers.entities.clearLayers();state.entities.forEach(e=>{const g=e.geometry||{};let layer=null;if(g.type==='polygon'&&Array.isArray(g.coordinates)&&g.coordinates.length>=3)layer=L.polygon(g.coordinates,{color:'#d6b66c',fillColor:'#d6b66c',fillOpacity:.12,weight:2,dashArray:'7 6'}).addTo(state.layers.entities);else if(g.type==='polyline'&&Array.isArray(g.coordinates)&&g.coordinates.length>=2)layer=L.polyline(g.coordinates,{color:'#63f6a8',weight:5,opacity:.85}).addTo(state.layers.entities);else{const p=point(e.latitude,e.longitude);if(!p)return;layer=L.marker([p.lat,p.lng],{icon:markerIcon(entityEmoji(e.entity_type),e.name,e.entity_type),draggable:master()}).addTo(state.layers.entities);if(master())layer.on('dragend',ev=>moveEntity(e,ev.target.getLatLng()))}layer.bindTooltip(entityEmoji(e.entity_type)+' '+(e.name||'Elemento'),{direction:'top',sticky:true});layer.on('click',ev=>{L.DomEvent.stopPropagation(ev);openEntity(e)})});
  }
  function renderInfection(){
    state.layers.infection.clearLayers();if(!master())return;state.infection.forEach(z=>{const p=point(z.latitude,z.longitude);if(!p)return;const n=num(z.infection_percent),c=n>=82?'#ff5b63':n>=62?'#ff9f43':n>=40?'#ffc95c':'#63f6a8';const circle=L.circle([p.lat,p.lng],{radius:Math.max(120,num(z.radius_m,650)),color:c,fillColor:c,fillOpacity:.08+n/400,weight:1.5}).addTo(state.layers.infection);circle.bindTooltip('☣ '+(z.zone_name||'Zona')+' · '+Math.round(n)+'%');circle.on('click',e=>{L.DomEvent.stopPropagation(e);openInfectionEditor(z)})});
  }
  function renderHordes(){
    state.layers.hordes.clearLayers();if(!master())return;state.hordes.forEach(h=>{const p=point(h.latitude,h.longitude);if(!p)return;const threat=clamp(Math.round(num(h.threat_level,1)),1,10);const html='<div class="al-horde" data-threat="'+threat+'"><span>☢</span><b>'+Math.round(num(h.size))+'</b><i style="transform:rotate('+Math.round(num(h.direction_deg))+'deg)"></i></div>';const m=L.marker([p.lat,p.lng],{icon:L.divIcon({className:'al-horde-wrap',html,iconSize:[52,52],iconAnchor:[26,26]}),zIndexOffset:900}).addTo(state.layers.hordes);m.bindTooltip('🧟 '+(h.name||'Horda')+' · '+Math.round(num(h.size))+' · ameaça '+threat+'/10');m.on('click',e=>{L.DomEvent.stopPropagation(e);openHordeEditor(h)})});
  }
  function renderFactions(){state.layers.factions.clearLayers();state.factions.forEach(f=>{const t=f.territory||{},c=Array.isArray(t.coordinates)?t.coordinates:(Array.isArray(t.polygon)?t.polygon:null);if(!c||c.length<3)return;const p=L.polygon(c,{color:'#d6b66c',fillColor:'#d6b66c',fillOpacity:.06,weight:2,dashArray:'8 7'}).addTo(state.layers.factions);p.bindTooltip('🏴 '+(f.name||'Facção'));p.on('click',e=>{L.DomEvent.stopPropagation(e);openFactionEditor(f)})})}
  function renderNpcs(){state.layers.npcs.clearLayers();state.npcs.forEach(n=>{const p=point(n.latitude,n.longitude);if(!p)return;const m=L.marker([p.lat,p.lng],{icon:simpleIcon('👤','npc'),zIndexOffset:500}).addTo(state.layers.npcs);m.on('click',e=>{L.DomEvent.stopPropagation(e);openEntity({entity_type:'npc',name:n.name,description:n.profession||n.description,latitude:p.lat,longitude:p.lng,state:n.state||{},metadata:n})})})}
  function renderStations(){state.layers.stations.clearLayers();state.stations.forEach(s=>{const p=point(s.latitude,s.longitude);if(!p)return;const m=L.marker([p.lat,p.lng],{icon:simpleIcon('⚒️','station'),zIndexOffset:450}).addTo(state.layers.stations);m.on('click',e=>{L.DomEvent.stopPropagation(e);openEntity({entity_type:'station',name:s.name,description:s.station_type,latitude:p.lat,longitude:p.lng,state:{condition:s.condition},metadata:s})})})}
  function renderVehicles(){state.layers.vehicles.clearLayers();state.vehicles.forEach(v=>{const p=point(v.latitude,v.longitude);if(!p)return;const m=L.marker([p.lat,p.lng],{icon:simpleIcon('🚙','vehicle'),zIndexOffset:400}).addTo(state.layers.vehicles);m.bindTooltip('🚙 '+(v.name||'Veículo')+' · '+(v.vehicle_type||'veículo'));m.on('click',e=>{L.DomEvent.stopPropagation(e);openEntity({entity_type:'vehicle',name:v.name,description:v.vehicle_type||'Veículo',latitude:p.lat,longitude:p.lng,state:{condition:v.condition,fuel_current:v.fuel_current,fuel_max:v.fuel_max},metadata:v})})})}
  function renderTravelRoute(){state.layers.route.clearLayers();state.layers.travelEvents.clearLayers();const t=state.travels.find(x=>['planned','in_transit'].includes(x.status));if(!t)return;const coords=t.route?.geometry?.coordinates;if(Array.isArray(coords)&&coords.length>=2)L.polyline(coords.map(c=>[c[1],c[0]]),{color:'#63f6a8',weight:4,dashArray:'10 8',opacity:.75}).addTo(state.layers.route);else L.polyline([[t.origin_latitude,t.origin_longitude],[t.destination_latitude,t.destination_longitude]],{color:'#63f6a8',weight:4,dashArray:'10 8',opacity:.75}).addTo(state.layers.route);const o={lat:num(t.origin_latitude),lng:num(t.origin_longitude)},d={lat:num(t.destination_latitude),lng:num(t.destination_longitude)};state.travelEvents.forEach(ev=>{const p=num(ev.progress_percent)/100,lat=o.lat+(d.lat-o.lat)*p,lng=o.lng+(d.lng-o.lng)*p,m=L.marker([lat,lng],{icon:simpleIcon(ev.type==='zombie'?'🧟':ev.type==='hazard'?'⚠️':'◆','event'),zIndexOffset:350}).addTo(state.layers.travelEvents);m.bindTooltip((ev.title||'Evento de viagem')+' · '+Math.round(num(ev.progress_percent))+'%');});}
  function renderVision(){state.layers.vision.clearLayers();if(master()||!state.mapPosition)return;L.circle([state.mapPosition.lat,state.mapPosition.lng],{radius:PLAYER_VISION_M,color:'#63f6a8',fillColor:'#63f6a8',fillOpacity:.03,weight:1,dashArray:'6 6'}).addTo(state.layers.vision)}
  function renderSelectedLocation(){const box=$('selectedLocationCard');if(!box)return;if(!state.selectedLocation){box.classList.add('is-empty');box.innerHTML='<div class="map-selected-icon">⌖</div><div><strong>Nenhum local selecionado</strong><small>Clique em um marcador para abrir a ficha.</small></div>';return}const l=state.selectedLocation;box.classList.remove('is-empty');box.innerHTML='<div class="map-selected-icon">'+esc(poiEmoji(l.category||''))+'</div><div><strong>'+esc(l.name)+'</strong><small>'+esc(l.category||'Local')+' · '+fmtKm(hav(currentPoint(),{lat:num(l.latitude),lng:num(l.longitude)}))+'</small><div class="map-selected-actions"><button type="button" data-selected-open>FICHA</button><button type="button" data-selected-center>CENTRALIZAR</button></div></div>';box.querySelector('[data-selected-open]').onclick=()=>openLocation(l);box.querySelector('[data-selected-center]').onclick=()=>centerOn({lat:num(l.latitude),lng:num(l.longitude)},16)}
  function updateStats(){if($('statMembers'))$('statMembers').textContent=state.members.length;if($('statLocations'))$('statLocations').textContent=state.locations.length;if($('statThreats'))$('statThreats').textContent=state.hordes.length+state.infection.filter(x=>num(x.infection_percent)>40).length}
  function updateReadout(){if(!state.map)return;const z=state.map.getZoom();$('mapZoomLabel').textContent='Z'+z;$('mapScaleLabel').textContent=z<7?'MUNDO':z<12?'REGIÃO':z<15?'CIDADE':'RUA';const c=state.map.getCenter();$('mapCoordinates').textContent=c.lat.toFixed(6)+'°, '+c.lng.toFixed(6)+'°'}

  function toggleDrawer(open){$('mapDrawer').classList.toggle('is-open',open);$('mapDrawer').setAttribute('aria-hidden',open?'false':'true');$('mapOpenPanel').setAttribute('aria-expanded',open?'true':'false')}
  function centerOn(p,z){if(!p)return;state.map.setView([p.lat,p.lng],clamp(z,2,19),{animate:true})}
  function openTab(tab,focus){document.querySelectorAll('[data-map-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.mapTab===tab));document.querySelectorAll('[data-map-panel]').forEach(p=>p.classList.toggle('is-active',p.dataset.mapPanel===tab));if(tab==='explore'){renderLocationList();renderPoiList()}if(tab==='systems'&&focus){state.activeSystemsTab=focus;buildSystemsPanel()}if(tab==='master')renderMasterPanel()}
  function openModal(title,html){$('mapModalEyebrow').textContent=master()?'CONTROLE DA MESA':'AFTERLIFE · MAPA';$('mapModalTitle').textContent=title;$('mapModalBody').innerHTML=html;$('mapModalBackdrop').hidden=false}
  function closeModal(){$('mapModalBackdrop').hidden=true}

  async function openLocation(loc){
    state.selectedLocation=loc;renderSelectedLocation();openTab('explore');toggleDrawer(true);let areas=[];try{const r=await aeriom.rpc('list_campaign_location_areas',{p_location_id:loc.id});if(!r.error)areas=Array.isArray(r.data)?r.data:[]}catch{}
    const danger=loc.danger||'unknown',condition=loc.state?.condition||'unknown',loot=Number(loc.state?.looted_percent||0);
    const cards=areas.length?areas.map(a=>'<article class="map-area-card"><div><strong>'+esc(a.name)+'</strong><small>'+esc(a.category||'Área')+' · '+esc(a.danger||'unknown')+(a.difficulty?' · CD '+a.difficulty:'')+'</small></div><p>'+esc(a.description||'Nenhuma descrição revelada.')+'</p><div class="map-area-actions"><button type="button" data-area-action="observe" data-area="'+esc(a.id)+'">OBSERVAR</button><button type="button" data-area-action="search" data-area="'+esc(a.id)+'">VASCULHAR</button><button type="button" data-area-action="investigate" data-area="'+esc(a.id)+'">INVESTIGAR</button></div></article>').join(''):'<div class="map-empty-state">Este local ainda não possui áreas preparadas pelo Mestre.</div>';
    openModal('FICHA DO LOCAL','<div class="map-location-sheet"><div class="map-location-kpis"><div><span>PERIGO</span><b>'+esc(danger)+'</b></div><div><span>ESTADO</span><b>'+esc(condition)+'</b></div><div><span>SAQUE</span><b>'+loot+'%</b></div></div><p class="map-location-address">'+esc(loc.address||'Local registrado no mundo da campanha.')+'</p>'+(master()?'<div class="map-sheet-actions"><button type="button" data-edit-location>EDITAR LOCAL</button><button type="button" data-create-area>+ CRIAR ÁREA</button></div>':'')+'<div class="map-section-title">ÁREAS DO LOCAL</div><div class="map-area-list">'+cards+'</div><div id="mapActionResult" class="map-action-result"></div></div>');
    $('mapModalBody').querySelectorAll('[data-area-action]').forEach(b=>b.onclick=()=>resolveAreaAction(b.dataset.area,b.dataset.areaAction,$('mapModalBody')));$('mapModalBody').querySelector('[data-edit-location]')?.addEventListener('click',()=>openLocationEditor(loc));$('mapModalBody').querySelector('[data-create-area]')?.addEventListener('click',()=>openCreateArea(loc));
  }

  async function resolveAreaAction(areaId,action){
    const out=$('mapActionResult');if(out)out.innerHTML='<div class="map-spinner">ROLANDO TESTE…</div>';
    try{const r=await aeriom.rpc('resolve_location_area_action',{p_area_id:areaId,p_action_key:action});if(r.error)throw r.error;const d=r.data||{},loot=Array.isArray(d.loot)?d.loot:[];if(out)out.innerHTML='<div class="map-result-head"><span>'+esc(d.die||'D?')+' · '+num(d.natural_roll)+' + '+num(d.training_bonus)+' + '+num(d.modifier)+'</span><strong>'+esc(String(d.result||'RESULTADO').replaceAll('_',' ').toUpperCase())+'</strong></div><p>'+esc(d.consequence||'')+'</p>'+(d.revealed_information?'<div class="map-result-block"><span>INFORMAÇÃO</span><p>'+esc(d.revealed_information)+'</p></div>':'')+(d.revealed_secrets?.length?'<div class="map-result-block"><span>SEGREDOS</span><p>'+d.revealed_secrets.map(x=>esc(typeof x==='string'?x:JSON.stringify(x))).join('<br>')+'</p></div>':'')+(loot.length?'<div class="map-result-block"><span>SAQUE</span><div class="map-loot-list">'+loot.map(x=>'<button type="button" data-loot="'+esc(x.id)+'"><span>◆</span><b>'+esc(x.item_name)+'</b><small>'+esc(x.item_category)+' · x'+num(x.quantity,1)+' · '+esc(x.rarity)+'</small></button>').join('')+'</div></div>':'');out?.querySelectorAll('[data-loot]').forEach(b=>b.onclick=async()=>{const x=await aeriom.rpc('claim_area_loot',{p_loot_id:b.dataset.loot});if(x.error){toast(x.error.message||'Falha ao coletar.','error');return}b.disabled=true;b.textContent='COLETADO'});toast('Teste concluído.','info')}catch(e){if(out)out.innerHTML='<div class="map-result-error">'+esc(e?.message||'Não foi possível realizar o teste.')+'</div>';toast(e?.message||'Falha no teste.','error')}
  }

  function openCreateArea(loc){openModal('NOVA ÁREA','<form id="areaForm" class="map-form"><label>NOME<input name="name" required value="Área principal"></label><label>CATEGORIA<input name="category" value="área"></label><label>DESCRIÇÃO<textarea name="description" rows="3"></textarea></label><div class="map-form-grid"><label>CD<input name="difficulty" type="number" min="1" max="20" value="10"></label><label>PERIGO<select name="danger"><option>unknown</option><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select></label></div><label>INFORMAÇÃO<textarea name="information" rows="3"></textarea></label><footer><button type="button" data-close>Cancelar</button><button type="submit">CRIAR ÁREA</button></footer></form>');const f=$('areaForm');f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),r=await aeriom.rpc('create_campaign_location_area',{p_location_id:loc.id,p_name:String(fd.get('name')),p_category:String(fd.get('category')),p_description:String(fd.get('description')||'')||null,p_difficulty:num(fd.get('difficulty')),p_danger:String(fd.get('danger')),p_information:String(fd.get('information')||'')||null,p_event:{},p_loot_profile:{},p_creatures:[],p_secrets:[]});if(r.error){toast(r.error.message||'Falha ao criar área.','error');return}closeModal();toast('Área criada.','info');openLocation(loc)};f.querySelector('[data-close]').onclick=closeModal}

  function openLocationEditor(loc){openModal('EDITAR LOCAL','<form id="locForm" class="map-form"><label>CONDIÇÃO<input name="condition" value="'+esc(loc.state?.condition||'unknown')+'"></label><label>PERIGO<input name="danger" value="'+esc(loc.danger||'unknown')+'"></label><label>NOTA<textarea name="note" rows="4">'+esc(loc.note||'')+'</textarea></label><footer><button type="button" data-close>Cancelar</button><button type="submit">SALVAR LOCAL</button></footer></form>');const f=$('locForm');f.onsubmit=async e=>{e.preventDefault();const r=await aeriom.rpc('update_campaign_world_location',{p_id:loc.id,p_condition:f.condition.value,p_resources:loc.resources||{},p_danger:f.danger.value,p_note:f.note.value});if(r.error){toast(r.error.message||'Falha ao salvar.','error');return}await loadLocations();renderLocations();closeModal();toast('Local atualizado.','info')};f.querySelector('[data-close]').onclick=closeModal}

  function openEntityEditor(entity,p){
    const types=[['house','🏚️','Casa'],['commerce','🏪','Comércio'],['hospital','🏥','Hospital'],['workshop','🔧','Oficina'],['police','🚓','Delegacia'],['military','🪖','Base militar'],['forest','🌲','Floresta'],['shelter','🏕️','Abrigo'],['vehicle','🚙','Veículo'],['station','⚒️','Estação de craft'],['hazard','☣️','Perigo'],['barricade','🚧','Barricada'],['custom','✦','Outro']];
    const first=entity?.geometry?.coordinates?.[0];const base=p||((entity?.geometry?.type==='polyline'&&Array.isArray(first))?{lat:first[0],lng:first[1]}:null);
    openModal(entity?.id?'EDITAR ELEMENTO':'NOVO ELEMENTO','<form id="mapEntityForm" class="map-form"><input type="hidden" name="id" value="'+esc(entity?.id||'')+'"><label>TIPO<select name="type">'+types.map(t=>'<option value="'+t[0]+'" '+(entity?.entity_type===t[0]?'selected':'')+'>'+t[1]+' '+t[2]+'</option>').join('')+'</select></label><label>NOME<input name="name" maxlength="100" required value="'+esc(entity?.name||'Novo elemento')+'"></label><label>DESCRIÇÃO<textarea name="description" rows="3" maxlength="600">'+esc(entity?.description||'')+'</textarea></label><div class="map-form-grid"><label>ESTADO<input name="status" value="'+esc(entity?.state?.status||'')+'"></label><label>PERIGO<select name="danger"><option value="low">Baixo</option><option value="medium" selected>Médio</option><option value="high">Alto</option><option value="critical">Crítico</option></select></label></div><input type="hidden" name="lat" value="'+(base?base.lat:'')+'"><input type="hidden" name="lng" value="'+(base?base.lng:'')+'"><footer><button type="button" data-close>Cancelar</button><button type="submit">SALVAR</button></footer></form>');
    const f=$('mapEntityForm');f.onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(f);const geometry=entity?.geometry||null;const payload={p_name:String(fd.get('name')).trim(),p_description:String(fd.get('description')||'').trim()||null,p_latitude:fd.get('lat')===''?null:num(fd.get('lat')),p_longitude:fd.get('lng')===''?null:num(fd.get('lng')),p_geometry:geometry,p_state:{status:String(fd.get('status')||''),danger:String(fd.get('danger')||'medium')},p_metadata:{}};try{let r;if(fd.get('id'))r=await aeriom.rpc('update_campaign_map_entity',{p_entity_id:fd.get('id'),...payload});else if(String(fd.get('type'))==='station'){r=await aeriom.rpc('create_campaign_crafting_station',{p_campaign_id:state.campaign.id,p_name:String(fd.get('name')).trim(),p_station_type:'workbench',p_latitude:payload.p_latitude,p_longitude:payload.p_longitude});if(r.error)throw r.error;await loadStations();renderStations();buildSystemsPanel();renderMasterPanel();closeModal();toast('Estação de craft criada.','info');return}else r=await aeriom.rpc('create_campaign_map_entity',{p_campaign_id:state.campaign.id,p_entity_type:String(fd.get('type')), ...payload});if(r.error)throw r.error;await loadEntities();renderEntities();renderMasterPanel();closeModal();toast('Elemento salvo.','info')}catch(e){toast(e?.message||'Não foi possível salvar.','error')}};f.querySelector('[data-close]').onclick=closeModal;
  }
  function openEntity(e){state.selectedEntity=e;openModal('ELEMENTO DO MUNDO','<div class="entity-sheet"><div class="entity-badge">'+entityEmoji(e.entity_type)+'</div><h3>'+esc(e.name||'Elemento')+'</h3><span>'+esc(e.entity_type||'world')+'</span><p>'+esc(e.description||'Sem descrição.')+'</p><div class="map-location-kpis"><div><span>ESTADO</span><b>'+esc(e.state?.status||'—')+'</b></div><div><span>PERIGO</span><b>'+esc(e.state?.danger||'—')+'</b></div></div>'+(master()&&e.id?'<button type="button" class="system-primary" data-edit-entity>EDITAR</button><button type="button" class="system-danger" data-delete-entity>EXCLUIR</button>':'')+'</div>');$('mapModalBody').querySelector('[data-edit-entity]')?.addEventListener('click',()=>openEntityEditor(e));$('mapModalBody').querySelector('[data-delete-entity]')?.addEventListener('click',()=>deleteEntity(e))}
  async function moveEntity(e,p){try{const r=await aeriom.rpc('update_campaign_map_entity',{p_entity_id:e.id,p_name:e.name,p_description:e.description||null,p_latitude:p.lat,p_longitude:p.lng,p_geometry:e.geometry||null,p_state:e.state||{},p_metadata:e.metadata||{}});if(r.error)throw r.error;await loadEntities();renderEntities();toast('Posição atualizada.','info')}catch(x){toast(x?.message||'Não foi possível mover.','error')}}
  async function deleteEntity(e){if(!confirm('Excluir este elemento do mapa?'))return;const r=await aeriom.rpc('delete_campaign_map_entity',{p_entity_id:e.id});if(r.error){toast(r.error.message||'Falha ao excluir.','error');return}await loadEntities();renderEntities();renderMasterPanel();closeModal();toast('Elemento excluído.','info')}

  function startMasterMode(mode){state.editorMode=mode;state.drawing=null;const note=$('masterToolNote');const texts={entity:'Clique no mapa para colocar um elemento.',territory:'Clique para desenhar um território. Use duplo clique para finalizar.',barricade:'Clique para desenhar uma barricada. Use duplo clique para finalizar.',horde:'Clique no mapa para registrar uma nova horda.',travel:'Clique no mapa para escolher o destino da viagem.'};if((mode==='territory'||mode==='barricade')&&state.map){state.map.doubleClickZoom.disable();if(!state.drawDoubleBound){state.drawDoubleBound=true;state.map.on('dblclick',()=>finishDrawing())}}if(note)note.textContent=texts[mode]||'Modo ativo.';openTab('master');toggleDrawer(true);toast(texts[mode]||'Modo ativado.','info')}
  function handleMapClick(e){if(state.editorMode==='travel'){setTravelDestination(e.latlng);return}if(state.editorMode==='territory'||state.editorMode==='barricade'){addDrawingPoint(e.latlng);return}if(state.editorMode==='entity'){state.editorMode=null;openEntityEditor(null,e.latlng);return}if(state.editorMode==='horde'){state.editorMode=null;openHordeEditor(null,e.latlng);return}$('mapCoordinates').textContent=e.latlng.lat.toFixed(6)+'°, '+e.latlng.lng.toFixed(6)+'°'}
  function addDrawingPoint(p){if(!state.drawing)state.drawing={points:[],type:state.editorMode,layer:null};state.drawing.points.push([p.lat,p.lng]);if(!state.drawing.layer){state.drawing.layer=(state.editorMode==='territory'?L.polygon(state.drawing.points,{color:'#d6b66c',fillColor:'#d6b66c',fillOpacity:.1,weight:2,dashArray:'7 6'}):L.polyline(state.drawing.points,{color:'#63f6a8',weight:6,dashArray:'9 7'})).addTo(state.map)}else state.drawing.layer.setLatLngs(state.drawing.points);toast(state.drawing.points.length+' ponto(s) · duplo clique para finalizar.','info')}
  function finishDrawing(){if(!state.drawing||state.drawing.points.length<(state.editorMode==='territory'?3:2))return;const d={points:state.drawing.points.slice(),type:state.editorMode};state.drawing.layer?.remove();state.drawing=null;state.map.doubleClickZoom.enable();if(d.type==='territory')openTerritoryEditor(d.points);else openEntityEditor({entity_type:'barricade',name:'Barricada',geometry:{type:'polyline',coordinates:d.points}});state.editorMode=null}

  function openTerritoryEditor(points){const options=state.factions.map(f=>'<option value="'+esc(f.id)+'">'+esc(f.name)+'</option>').join('');openModal('TERRITÓRIO DE FACÇÃO','<form id="territoryForm" class="map-form"><label>FACÇÃO<select name="faction">'+options+'</select></label><p class="map-form-help">O território será salvo diretamente na ficha da facção.</p><footer><button type="button" data-close>Cancelar</button><button type="submit">SALVAR TERRITÓRIO</button></footer></form>');const f=$('territoryForm');f.onsubmit=async e=>{e.preventDefault();const id=f.faction.value,fac=state.factions.find(x=>x.id===id),r=await aeriom.rpc('update_campaign_faction',{p_id:id,p_name:fac.name,p_description:fac.description,p_reputation_default:fac.reputation_default,p_resources:fac.resources||{},p_territory:{type:'polygon',coordinates:points}});if(r.error){toast(r.error.message||'Falha ao salvar território.','error');return}await loadFactions();renderFactions();closeModal();toast('Território salvo.','info')};f.querySelector('[data-close]').onclick=closeModal}

  function openInfectionEditor(z){openModal('ZONA DE INFECÇÃO','<form id="infectionForm" class="map-form"><label>INFECÇÃO <output id="infOut">'+Math.round(num(z.infection_percent))+'%</output><input name="infection" type="range" min="0" max="100" value="'+num(z.infection_percent)+'"></label><label>DENSIDADE <output id="densOut">'+Math.round(num(z.zombie_density_percent))+'%</output><input name="density" type="range" min="0" max="100" value="'+num(z.zombie_density_percent)+'"></label><label>PROPAGAÇÃO<input name="spread" type="range" min="0" max="100" value="'+num(z.spread_rate)+'"></label><label>ESTÁGIO<select name="stage">'+['contained','active','severe','critical'].map(k=>'<option '+(z.outbreak_stage===k?'selected':'')+'>'+k+'</option>').join('')+'</select></label><footer><button type="button" data-close>Cancelar</button><button type="submit">SALVAR ZONA</button></footer></form>');const f=$('infectionForm');f.infection.oninput=()=>f.querySelector('#infOut').textContent=f.infection.value+'%';f.density.oninput=()=>f.querySelector('#densOut').textContent=f.density.value+'%';f.onsubmit=async e=>{e.preventDefault();const r=await aeriom.rpc('update_campaign_infection_zone',{p_id:z.id,p_infection:num(f.infection.value),p_zombie_density:num(f.density.value),p_spread_rate:num(f.spread.value),p_stage:f.stage.value});if(r.error){toast(r.error.message||'Falha ao salvar zona.','error');return}await loadInfection();renderInfection();renderMasterPanel();closeModal();toast('Zona atualizada.','info')};f.querySelector('[data-close]').onclick=closeModal}

  function openHordeEditor(h,p){openModal(h?'EDITAR HORDA':'NOVA HORDA','<form id="hordeForm" class="map-form"><input type="hidden" name="id" value="'+esc(h?.id||'')+'"><input type="hidden" name="lat" value="'+(h?.latitude??p?.lat??'')+'"><input type="hidden" name="lng" value="'+(h?.longitude??p?.lng??'')+'"><label>NOME<input name="name" value="'+esc(h?.name||'Onda detectada')+'"></label><div class="map-form-grid"><label>ZUMBIS<input name="size" type="number" min="1" value="'+num(h?.size,30)+'"></label><label>KM/H<input name="speed" type="number" min="0" value="'+num(h?.speed_kmh,12)+'"></label></div><div class="map-form-grid"><label>DIREÇÃO<input name="direction" type="number" min="0" max="359" value="'+num(h?.direction_deg,0)+'"></label><label>ETA<input name="eta" type="number" min="0" value="'+num(h?.eta_minutes,0)+'"></label></div><label>STATUS<select name="status"><option>moving</option><option '+(h?.status==='stationary'?'selected':'')+'>stationary</option><option '+(h?.status==='dispersed'?'selected':'')+'>dispersed</option></select></label><footer><button type="button" data-close>Cancelar</button><button type="submit">SALVAR</button></footer></form>');const f=$('hordeForm');f.onsubmit=async e=>{e.preventDefault();const r=f.id.value?await aeriom.rpc('update_campaign_horde',{p_id:f.id.value,p_latitude:num(f.lat.value),p_longitude:num(f.lng.value),p_size:num(f.size.value),p_speed_kmh:num(f.speed.value),p_direction_deg:num(f.direction.value),p_detected:true,p_status:f.status.value,p_eta_minutes:num(f.eta.value)||null}):await aeriom.rpc('create_campaign_horde',{p_campaign_id:state.campaign.id,p_latitude:num(f.lat.value),p_longitude:num(f.lng.value),p_size:num(f.size.value),p_speed_kmh:num(f.speed.value),p_direction_deg:num(f.direction.value),p_source_zone_id:null});if(r.error){toast(r.error.message||'Falha ao salvar horda.','error');return}await loadHordes();renderHordes();renderMasterPanel();buildSystemsPanel();closeModal();toast('Horda sincronizada no radar.','info')};f.querySelector('[data-close]').onclick=closeModal}

  function openFactionEditor(f){openModal('FACÇÃO','<div class="entity-sheet"><div class="entity-badge">🏴</div><h3>'+esc(f.name)+'</h3><span>'+esc(f.faction_type||'Facção')+'</span><p>'+esc(f.description||'Sem descrição.')+'</p><div class="map-location-kpis"><div><span>REPUTAÇÃO</span><b>'+num(f.reputation_default)+'</b></div><div><span>RECURSOS</span><b>'+Object.keys(f.resources||{}).length+'</b></div></div>'+(master()?'<button type="button" class="system-primary" data-faction-territory>DESENHAR TERRITÓRIO</button>':'')+'</div>');$('mapModalBody').querySelector('[data-faction-territory]')?.addEventListener('click',()=>{closeModal();startMasterMode('territory')})}

  async function savePoi(p){try{const r=await aeriom.rpc('upsert_campaign_world_location',{p_campaign_id:state.campaign.id,p_source:'osm',p_external_id:p.key,p_name:p.name,p_category:p.type,p_latitude:p.lat,p_longitude:p.lng,p_address:p.address||null,p_metadata:{tags:p.tags||{}}});if(r.error)throw r.error;await loadLocations();renderLocations();renderLocationList();closeModal();toast('Local salvo no mundo da campanha.','info')}catch(e){toast(e?.message||'Não foi possível salvar o local.','error')}}
  function openPoi(p){state.selectedPoi=p;centerOn({lat:p.lat,lng:p.lng},Math.max(state.map.getZoom(),16));openModal('PONTO REAL','<div class="entity-sheet"><div class="entity-badge">'+esc(poiEmoji(p.type))+'</div><h3>'+esc(p.name)+'</h3><span>'+esc(p.type)+'</span><p>'+esc(p.address||'Descoberto pelo OpenStreetMap.')+'</p><div class="map-location-kpis"><div><span>DISTÂNCIA</span><b>'+fmtKm(hav(currentPoint(),p))+'</b></div><div><span>FONTE</span><b>OSM</b></div></div><button type="button" class="system-primary" data-save-poi>SALVAR NO MUNDO</button></div>');$('mapModalBody').querySelector('[data-save-poi]').onclick=()=>savePoi(p)}

  function renderLocationList(){const list=$('locationList');if(!list)return;const p=currentPoint(),rows=state.locations.slice().sort((a,b)=>hav(p,{lat:num(a.latitude),lng:num(a.longitude)})-hav(p,{lat:num(b.latitude),lng:num(b.longitude)})).slice(0,16);list.innerHTML=rows.length?rows.map(l=>'<button type="button" class="map-list-row" data-location="'+esc(l.id)+'"><span class="map-list-icon">'+esc(poiEmoji(l.category||''))+'</span><span><strong>'+esc(l.name)+'</strong><small>'+esc(l.category||'Local')+' · '+fmtKm(hav(p,{lat:num(l.latitude),lng:num(l.longitude)}))+'</small></span><b>→</b></button>').join(''):'<div class="map-empty-state">Nenhum local salvo nesta campanha.</div>';list.querySelectorAll('[data-location]').forEach(b=>b.onclick=()=>{const l=state.locations.find(x=>x.id===b.dataset.location);if(l)openLocation(l)})}
  function renderPoiList(){const list=$('poiList');if(!list)return;const pois=getVisiblePois();list.innerHTML=pois.length?pois.slice(0,18).map(p=>'<button type="button" class="map-list-row map-list-row--poi" data-poi="'+esc(p.key)+'"><span class="map-list-icon">'+esc(poiEmoji(p.type))+'</span><span><strong>'+esc(p.name)+'</strong><small>'+esc(p.type)+' · '+fmtKm(hav(currentPoint(),p))+'</small></span><b>+</b></button>').join(''):'<div class="map-empty-state">Aproxime até a escala de rua para carregar pontos reais.</div>';list.querySelectorAll('[data-poi]').forEach(b=>b.onclick=()=>{const p=getVisiblePois().find(x=>x.key===b.dataset.poi);if(p)openPoi(p)})}
  function getVisiblePois(){const c=state.map?.getCenter();if(!c)return[];let out=[];for(const v of state.poiCache.values())out=out.concat(v.items||[]);const seen=new Set();return out.filter(x=>{if(seen.has(x.key))return false;seen.add(x.key);return true})}
  function poiCacheKey(){const c=state.map.getCenter();return c.lat.toFixed(3)+':'+c.lng.toFixed(3)+':'+Math.floor(state.map.getZoom())}
  function renderPoisIfNeeded(){if(state.map.getZoom()<15){state.layers.pois.clearLayers();const s=$('poiStatus');if(s)s.textContent='Aproxime até a escala de rua para descobrir pontos reais.';renderPoiList();return}loadPois().catch(()=>{})}
  async function loadPois(){const key=poiCacheKey(),cached=state.poiCache.get(key);if(cached&&Date.now()-cached.ts<POI_TTL){renderPois(cached.items);return}const c=state.map.getCenter(),q='[out:json][timeout:7];(nwr(around:1100,'+c.lat+','+c.lng+')[name][amenity];nwr(around:1100,'+c.lat+','+c.lng+')[name][shop];nwr(around:1100,'+c.lat+','+c.lng+')[name][leisure];nwr(around:1100,'+c.lat+','+c.lng+')[name][tourism];nwr(around:1100,'+c.lat+','+c.lng+')[name][craft];nwr(around:1100,'+c.lat+','+c.lng+')[name][natural];nwr(around:1100,'+c.lat+','+c.lng+')[name][historic];);out center tags qt;';let data=null;for(const endpoint of POI_ENDPOINTS){try{const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),8000),r=await fetch(endpoint,{method:'POST',body:q,signal:ctrl.signal,headers:{'Content-Type':'text/plain;charset=UTF-8'}});clearTimeout(timer);if(!r.ok)continue;data=await r.json();break}catch{}}if(!data){$('poiStatus').textContent='Serviço de pontos reais indisponível. O mapa continua funcionando.';return}const items=(data.elements||[]).map(el=>{const lat=num(el.lat??el.center?.lat),lng=num(el.lon??el.center?.lon),tags=el.tags||{},type=poiType(tags);return{key:'osm:'+el.type+':'+el.id,name:tags.name||tags.brand||'Local sem nome',type,lat,lng,address:tags['addr:street']?[tags['addr:street'],tags['addr:housenumber'],tags['addr:city']].filter(Boolean).join(', '):tags['addr:full']||'',tags}}).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lng)).slice(0,MAX_POIS);state.poiCache.set(key,{ts:Date.now(),items});renderPois(items)}
  function renderPois(items){state.layers.pois.clearLayers();if(!items?.length){$('poiStatus').textContent='Nenhum ponto real encontrado perto desta área.';renderPoiList();return}items.forEach(p=>{const m=L.marker([p.lat,p.lng],{icon:simpleIcon(poiEmoji(p.type),'poi'),zIndexOffset:150}).addTo(state.layers.pois);m.on('click',e=>{L.DomEvent.stopPropagation(e);openPoi(p)});m.bindTooltip(esc(p.name)+' · '+esc(p.type),{direction:'top',offset:[0,-15]})});$('poiStatus').textContent=items.length+' pontos reais carregados · OpenStreetMap.';renderPoiList()}

  function buildSystemsPanel(){
    const host=$('systemsCards');if(!host)return;const w=state.activeSystemsTab,nav='<div class="systems-switch">'+['world','radar','travel','survival'].map(k=>'<button type="button" class="'+(w===k?'is-active':'')+'" data-system="'+k+'">'+({world:'MUNDO',radar:'RADAR',travel:'VIAGEM',survival:'SOBREVIVÊNCIA'}[k])+'</button>').join('')+'</div>';let body=w==='radar'?renderRadarPanel():w==='travel'?renderTravelPanel():w==='survival'?renderSurvivalPanel():renderWorldPanel();host.innerHTML=nav+body;host.querySelectorAll('[data-system]').forEach(b=>b.onclick=()=>{state.activeSystemsTab=b.dataset.system;buildSystemsPanel()});host.querySelector('[data-start-mode="horde"]')?.addEventListener('click',()=>startMasterMode('horde'));host.querySelector('[data-start-mode="travel"]')?.addEventListener('click',()=>startMasterMode('travel'));host.querySelector('[data-refresh-hordes]')?.addEventListener('click',async()=>{await loadHordes();renderHordes();buildSystemsPanel()});host.querySelectorAll('[data-horde]').forEach(b=>b.onclick=()=>{const h=state.hordes.find(x=>x.id===b.dataset.horde);if(h)openHordeEditor(h)});host.querySelector('[data-gps]')?.addEventListener('click',locateDevice);host.querySelector('[data-center-me]')?.addEventListener('click',()=>centerOn(currentPoint(),15));host.querySelectorAll('[data-travel-action]').forEach(b=>b.onclick=()=>travelAction(b.dataset.travelAction));host.querySelectorAll('[data-faction]').forEach(b=>b.onclick=()=>{const f=state.factions.find(x=>x.id===b.dataset.faction);if(f)openFactionEditor(f)})}
  function renderWorldPanel(){const fs=state.factions.slice(0,8).map(f=>'<button class="system-row" type="button" data-faction="'+esc(f.id)+'"><span>🏴</span><span><strong>'+esc(f.name)+'</strong><small>'+esc(f.faction_type||'Facção')+' · reputação '+num(f.reputation_default)+'</small></span><b>→</b></button>').join(''),ns=state.npcs.slice(0,8).map(n=>'<div class="system-row"><span>👤</span><span><strong>'+esc(n.name)+'</strong><small>'+esc(n.profession||'NPC')+'</small></span></div>').join(''),ss=state.stations.slice(0,8).map(s=>'<div class="system-row"><span>⚒️</span><span><strong>'+esc(s.name)+'</strong><small>'+esc(s.station_type||'craft')+' · '+esc(s.condition||'operational')+'</small></span></div>').join('');return'<div class="system-intro"><span>MUNDO</span><strong>O mapa guarda a memória da mesa.</strong><small>Facções, NPCs e estações ficam onde realmente importam.</small></div><div class="map-section-title">FACÇÕES</div><div class="system-list">'+(fs||'<div class="map-empty-state">Nenhuma facção.</div>')+'</div><div class="map-section-title">NPCs</div><div class="system-list">'+(ns||'<div class="map-empty-state">Nenhum NPC com posição.</div>')+'</div><div class="map-section-title">CRAFT / FORJA</div><div class="system-list">'+(ss||'<div class="map-empty-state">Nenhuma estação no mapa.</div>')+'</div>'}
  function renderRadarPanel(){if(!master())return'<div class="system-intro"><span>RADAR DO SOBREVIVENTE</span><strong>As ondas são controladas pelo Mestre.</strong><small>Você recebe apenas sinais descobertos pela mesa.</small></div>';const c=currentPoint(),rows=state.hordes.slice().sort((a,b)=>hav(c,{lat:num(a.latitude),lng:num(a.longitude)})-hav(c,{lat:num(b.latitude),lng:num(b.longitude)})).map(h=>{const p={lat:num(h.latitude),lng:num(h.longitude)};return'<button class="radar-row" type="button" data-horde="'+esc(h.id)+'"><span class="radar-signal"></span><span><strong>'+esc(h.name||'Horda')+'</strong><small>'+fmtKm(hav(c,p))+' · '+cardinal(bearing(c,p))+' · ameaça '+num(h.threat_level,1)+'/10</small></span><b>'+num(h.size)+'</b></button>'}).join('');return'<div class="system-intro"><span>☢ RADAR DE HORDAS</span><strong>'+state.hordes.length+' onda(s).</strong><small>Posições sincronizadas em tempo real.</small></div><div class="system-actions"><button class="system-primary" data-start-mode="horde" type="button">+ CRIAR HORDA NO MAPA</button><button class="system-secondary" data-refresh-hordes type="button">ATUALIZAR</button></div><div class="map-section-title">SINAIS</div><div class="radar-list">'+(rows||'<div class="map-empty-state">Nenhuma horda detectada.</div>')+'</div>'}
  function renderTravelPanel(){const a=state.travels.find(t=>['planned','in_transit'].includes(t.status)),head=a?'<div class="travel-current"><span>VIAGEM '+esc(a.status.toUpperCase())+'</span><strong>'+esc(a.destination_name||'Destino')+'</strong><small>'+Math.round(num(a.progress_percent))+'% · '+fmtKm(a.distance_m)+'</small></div>':'<div class="travel-empty">Nenhuma viagem ativa.</div>';return'<div class="system-intro"><span>DESLOCAMENTO</span><strong>Faça a rota acontecer na mesa.</strong><small>O Mestre cria o destino, inicia e avança o trajeto.</small></div>'+head+(master()?'<div class="system-actions"><button class="system-primary" type="button" data-start-mode="travel">ESCOLHER DESTINO NO MAPA</button></div>':'')+(a&&master()?'<div class="travel-buttons"><button type="button" data-travel-action="start">INICIAR</button><button type="button" data-travel-action="advance">AVANÇAR +10%</button><button type="button" data-travel-action="complete">CONCLUIR</button><button type="button" data-travel-action="cancel">CANCELAR</button></div>':'')}
  function renderSurvivalPanel(){const p=currentPoint();return'<div class="system-intro"><span>POSIÇÃO ATUAL</span><strong>'+p.lat.toFixed(5)+'°, '+p.lng.toFixed(5)+'°</strong><small>Visão de '+PLAYER_VISION_M+' m.</small></div><div class="survival-position"><button type="button" data-gps>ATUALIZAR PELO GPS</button><button type="button" data-center-me>CENTRALIZAR</button></div>'}
  async function travelAction(action){const t=state.travels.find(x=>['planned','in_transit'].includes(x.status));if(!t)return;const fn={start:'start_campaign_travel',advance:'advance_campaign_travel_progress',complete:'complete_campaign_travel',cancel:'cancel_campaign_travel'}[action],args={p_travel_id:t.id};if(action==='advance')args.p_progress_percent=Math.min(100,num(t.progress_percent)+10);const r=await aeriom.rpc(fn,args);if(r.error){toast(r.error.message||'Falha na viagem.','error');return}await loadTravels();await loadMembers();renderAll();buildSystemsPanel();toast('Viagem atualizada.','info')}

  function renderMasterPanel(){const host=$('masterPanel');if(!host)return;if(!master()){host.innerHTML='<div class="system-intro"><span>MAPA</span><strong>Controles do Mestre ocultos.</strong><small>Você está na visão de sobrevivente.</small></div>';return}host.innerHTML='<div class="system-intro"><span>MESTRE · EDITOR</span><strong>Construa o mundo vivo.</strong><small>Coloque elementos, territórios, hordas, viagens e zonas.</small></div><div class="master-tools-grid">'+[['entity','✦','ELEMENTO'],['territory','🏴','TERRITÓRIO'],['barricade','🚧','BARRICADA'],['horde','☢','HORDA'],['travel','➜','VIAGEM']].map(x=>'<button type="button" data-master-mode="'+x[0]+'"><span>'+x[1]+'</span><b>'+x[2]+'</b></button>').join('')+'</div><div class="master-tool-note" id="masterToolNote">Nenhum modo de edição ativo.</div><div class="map-section-title">ZONAS DE INFECÇÃO</div><div class="master-zone-list">'+state.infection.slice(0,12).map(z=>'<button type="button" class="zone-row" data-zone="'+esc(z.id)+'"><span>☣</span><span><strong>'+esc(z.zone_name)+'</strong><small>'+Math.round(num(z.infection_percent))+'% · '+esc(z.outbreak_stage)+'</small></span><b>→</b></button>').join('')+'</div><div class="map-section-title">ELEMENTOS</div><div class="master-entity-list">'+state.entities.slice().reverse().slice(0,18).map(e=>'<button type="button" class="zone-row" data-entity="'+esc(e.id)+'"><span>'+entityEmoji(e.entity_type)+'</span><span><strong>'+esc(e.name)+'</strong><small>'+esc(e.entity_type)+'</small></span><b>→</b></button>').join('')+'</div>';host.querySelectorAll('[data-master-mode]').forEach(b=>b.onclick=()=>startMasterMode(b.dataset.masterMode));host.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{const z=state.infection.find(x=>x.id===b.dataset.zone);if(z)openInfectionEditor(z)});host.querySelectorAll('[data-entity]').forEach(b=>b.onclick=()=>{const e=state.entities.find(x=>x.id===b.dataset.entity);if(e)openEntity(e)})}

  function setTravelDestination(latlng){state.editorMode=null;state.travelDraft={origin:currentPoint(),destination:{lat:latlng.lat,lng:latlng.lng}};state.layers.route.clearLayers();L.polyline([[state.travelDraft.origin.lat,state.travelDraft.origin.lng],[latlng.lat,latlng.lng]],{color:'#63f6a8',weight:4,dashArray:'10 7'}).addTo(state.layers.route);openTravelCreator()}
  function openTravelCreator(){const o=state.travelDraft.origin,d=state.travelDraft.destination;openModal('PLANEJAR VIAGEM','<form id="travelForm" class="map-form"><div class="travel-current"><span>ORIGEM</span><strong>'+o.lat.toFixed(5)+'°, '+o.lng.toFixed(5)+'°</strong><small>DESTINO · '+d.lat.toFixed(5)+'°, '+d.lng.toFixed(5)+'°</small></div><label>NOME DO DESTINO<input name="name" value="Destino no mapa"></label><div class="map-form-grid"><label>KM/H<input name="speed" type="number" min=".1" max="300" step=".1" value="5"></label><label>EXPOSIÇÃO / KM<input name="exposure" type="number" min="0" step=".1" value="0"></label></div><div class="map-form-grid">'+state.members.filter(x=>x.role!=='master').map(m=>'<label class="check-row"><input type="checkbox" name="participant" value="'+esc(m.user_id)+'"> '+esc(m.display_name||'Sobrevivente')+'</label>').join('')+'</div><footer><button type="button" data-close>Cancelar</button><button type="submit">CRIAR VIAGEM</button></footer></form>');const f=$('travelForm');f.onsubmit=async e=>{e.preventDefault();const ids=[...f.querySelectorAll('[name="participant"]:checked')].map(x=>x.value);if(!ids.length){toast('Selecione pelo menos um sobrevivente.','error');return}const distance=hav(o,d),r=await aeriom.rpc('create_campaign_travel',{p_campaign_id:state.campaign.id,p_origin_latitude:o.lat,p_origin_longitude:o.lng,p_destination_latitude:d.lat,p_destination_longitude:d.lng,p_destination_location_id:null,p_destination_name:f.name.value.trim()||'Destino no mapa',p_route:{provider:'straight',geometry:{coordinates:[[o.lng,o.lat],[d.lng,d.lat]]}},p_distance_m:distance,p_speed_kmh:num(f.speed.value,5),p_fuel_per_km:0,p_energy_per_km:0,p_exposure_per_km:num(f.exposure.value),p_participant_user_ids:ids});if(r.error){toast(r.error.message||'Não foi possível criar a viagem.','error');return}await loadTravels();renderTravelRoute();buildSystemsPanel();closeModal();state.travelDraft=null;toast('Viagem planejada.','info')};f.querySelector('[data-close]').onclick=()=>{closeModal();state.travelDraft=null;state.layers.route.clearLayers()}}
  
  function locateDevice(){if(!navigator.geolocation){toast('GPS não disponível no navegador.','error');return}toast('Buscando GPS…','loading');navigator.geolocation.getCurrentPosition(async pos=>{state.geoloc={lat:pos.coords.latitude,lng:pos.coords.longitude};state.layers.device.clearLayers();L.marker([state.geoloc.lat,state.geoloc.lng],{icon:simpleIcon('◎','gps'),zIndexOffset:1000}).addTo(state.layers.device).bindTooltip('Sua posição física');centerOn(state.geoloc,16);if(!master())await persistPlayerPosition(state.geoloc);toast('Posição encontrada.','info')},err=>toast(err?.message||'Não foi possível obter o GPS.','error'),{enableHighAccuracy:true,timeout:9000,maximumAge:15000})}
  async function persistPlayerPosition(p){try{const r=await aeriom.from('campaign_map_positions').upsert({campaign_id:state.campaign.id,user_id:state.session.user.id,latitude:p.lat,longitude:p.lng,updated_at:new Date().toISOString()},{onConflict:'campaign_id,user_id'});if(r.error)throw r.error;state.mapPosition=p;await loadMembers();renderVision()}catch(e){toast('GPS encontrado, mas a posição da campanha não foi salva.','error')}}
  async function toggleCompass(){try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted'){toast('A bússola foi recusada pelo navegador.','error');return}}if(!state.compass.bound){state.compass.bound=true;window.addEventListener('deviceorientationabsolute',onOrientation,true);window.addEventListener('deviceorientation',onOrientation,true)}state.compass.active=!state.compass.active;$('mapCompass').classList.toggle('is-active',state.compass.active);$('mapCompass').setAttribute('aria-pressed',state.compass.active?'true':'false');toast(state.compass.active?'Bússola ativa.':'Bússola pausada.','info')}catch{toast('Não foi possível ativar a bússola.','error')}}
  function onOrientation(e){if(!state.compass.active)return;const h=Number.isFinite(e?.webkitCompassHeading)?Number(e.webkitCompassHeading):Number.isFinite(e?.alpha)?360-Number(e.alpha):null;if(h!=null){state.compass.heading=(h+360)%360;$('mapCompass').textContent=cardinal(state.compass.heading)}}

  function subscribeRealtime(){const cid=state.campaign.id;const specs=[['campaign_map_positions',loadMembers],['campaign_world_locations',async()=>{await loadLocations();renderLocations();renderLocationList()}],['campaign_map_entities',async()=>{await loadEntities();renderEntities();renderMasterPanel()}],['campaign_hordes',async()=>{await loadHordes();renderHordes();buildSystemsPanel()}],['campaign_infection_zones',async()=>{await loadInfection();renderInfection();renderMasterPanel()}],['campaign_factions',async()=>{await loadFactions();renderFactions();buildSystemsPanel()}],['campaign_npcs',async()=>{await loadNpcs();renderNpcs();buildSystemsPanel()}],['crafting_stations',async()=>{await loadStations();renderStations();buildSystemsPanel()}],['campaign_vehicles',async()=>{await loadVehicles();renderVehicles();}],['campaign_travel_events',async()=>{await loadTravels();renderTravelRoute();buildSystemsPanel()}],['campaign_travels',async()=>{await loadTravels();renderTravelRoute();buildSystemsPanel()}]];specs.forEach(([table,refresh])=>{const ch=aeriom.channel('afterlife-map-'+table+'-'+cid).on('postgres_changes',{event:'*',schema:'public',table:table,filter:'campaign_id=eq.'+cid},()=>{clearTimeout(ch.__timer);ch.__timer=setTimeout(()=>refresh().catch(()=>{}),180)}).subscribe();state.realtime.push(ch)})}

  boot();
})();