(() => {
'use strict';
if(window.__afterlifeGlobalProfileBooted)return;
window.__afterlifeGlobalProfileBooted=true;
const $=id=>document.getElementById(id),initial=name=>String(name||'A').trim().charAt(0).toUpperCase()||'A';
const icon=document.createElement('link');icon.rel='icon';icon.type='image/svg+xml';icon.href='./favicon.svg?v=20260913-1';document.head.appendChild(icon);
const css=document.createElement('link');css.rel='stylesheet';css.href='./css/afterlife-profile-global.css?v=20260913-6';document.head.appendChild(css);
let menu=null,chip=null;
function avatar(box,url,name,large=false){if(!box)return;box.replaceChildren();box.style.position='relative';box.style.overflow='hidden';box.style.flex='0 0 auto';box.style.width=large?'48px':'35px';box.style.height=large?'48px':'35px';box.style.minWidth=large?'48px':'35px';box.style.minHeight=large?'48px':'35px';box.style.maxWidth=large?'48px':'35px';box.style.maxHeight=large?'48px':'35px';if(!url){box.textContent=initial(name);return}const img=document.createElement('img');img.src=url;img.alt='';img.referrerPolicy='no-referrer';img.onerror=()=>{box.replaceChildren();box.textContent=initial(name)};box.appendChild(img)}
function ensureMenu(){chip=$('profileChip')||document.querySelector('.profile-chip');if(!chip)return null;chip.classList.add('afterlife-global-profile-chip');const wrap=chip.closest('.profile-wrap')||chip.parentElement;if(wrap)wrap.classList.add('afterlife-global-profile-wrap');menu=$('profileDropdown')||$('profileMenu')||document.querySelector('.afterlife-account-menu');if(menu){menu.classList.add('afterlife-global-profile-menu');menu.hidden=true;return menu}menu=document.createElement('div');menu.id='afterlifeGlobalProfileMenu';menu.className='afterlife-global-profile-menu';menu.hidden=true;menu.innerHTML='<div class="afterlife-global-profile-head"><span class="afterlife-global-profile-avatar" id="afterlifeGlobalProfileAvatar">A</span><div><strong id="afterlifeGlobalProfileName">Sobrevivente</strong><small id="afterlifeGlobalProfileEmail">Conta Afterlife</small></div></div><div class="afterlife-global-profile-actions"><a href="./perfil.html">Editar perfil</a><a href="../index.html">Trocar sistema</a><button type="button" class="danger" id="afterlifeGlobalLogout">Sair da conta</button></div></div>';(wrap||document.querySelector('.top-actions')||document.body).appendChild(menu);return menu}
function setProfile(name,url,email){const n=name||'Sobrevivente';['profileName','profileDropdownName','profileMenuName','afterlifeGlobalProfileName'].forEach(id=>{if($(id))$(id).textContent=n});if($('profileDropdownEmail'))$('profileDropdownEmail').textContent=email||'Conta Afterlife';if($('profileMenuEmail'))$('profileMenuEmail').textContent=email||'Perfil compartilhado com AERIOM';if($('afterlifeGlobalProfileEmail'))$('afterlifeGlobalProfileEmail').textContent=email||'Conta Afterlife';avatar($('profileAvatar'),url,n,false);avatar($('profileDropdownAvatar'),url,n,true);avatar($('profileMenuAvatar'),url,n,true);avatar($('afterlifeGlobalProfileAvatar'),url,n,true)}
function toggle(open){if(!menu||!chip)return;const state=typeof open==='boolean'?open:menu.hidden;menu.hidden=!state;if(menu.id==='profileMenu')document.body.classList.toggle('profile-open',state);chip.setAttribute('aria-expanded',String(state))}
async function loadProfile(){try{const mod=await import('./aeriom-client.js');const sb=mod.aeriom;const session=await sb.auth.getSession();const user=session?.data?.session?.user;if(!user){setProfile('Sobrevivente','','Faça login no AERIOM');return}let name=user.user_metadata?.display_name||user.user_metadata?.full_name||user.email?.split('@')[0]||'Sobrevivente',url='';const p=await sb.from('profiles').select('display_name,avatar_path').eq('id',user.id).maybeSingle();if(p.data?.display_name)name=p.data.display_name;if(p.data?.avatar_path){const signed=await sb.storage.from('avatars').createSignedUrl(p.data.avatar_path,3600);url=signed.data?.signedUrl||''}setProfile(name,url,user.email||'Conta Afterlife')}catch(error){console.warn('[AFTERLIFE] perfil global:',error);setProfile('Sobrevivente','','Conta Afterlife')}}
function bind(){ensureMenu();if(!chip||!menu)return;chip.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();toggle()},{capture:true});document.addEventListener('click',event=>{if(!menu.contains(event.target)&&!chip.contains(event.target))toggle(false)},{capture:true});document.addEventListener('keydown',event=>{if(event.key==='Escape')toggle(false)});menu.addEventListener('click',event=>event.stopPropagation());menu.querySelector('#profileLogout, #profileSignOut, #afterlifeGlobalLogout')?.addEventListener('click',async event=>{event.preventDefault();event.stopPropagation();try{await (await import('./aeriom-client.js')).aeriom.auth.signOut()}finally{location.replace('../index.html')}})}
async function boot(){bind();await loadProfile()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
